### ISSUE TITLE
Add more worlds

### ISSUE THREAD

**Issue by Peda1996** [BentoBoxWorld/BSkyBlock#100]
Hello,

I really like and apprechiate your work. Would it be possible to implement a method of generating more worlds like the nether and end, but also custom ones? Would be also cool, if someone needs to get a portal to get to these new worlds.

Lg

**Comment by tastybento** [comment]
That would not really be in scope for this add-on. If you would like to create other worlds, you can use plugins like MultiVerse and Multiverse Portals to create portals to them.

**Comment by Peda1996** [comment]
Ah, can I therefore use BSkyBlock as Generator?
