### ISSUE TITLE
ASkyblock to BSkyblock

### ISSUE THREAD

**Issue by PapiCapi** [BentoBoxWorld/BSkyBlock#103]
Hello, I know this question is asked a lot of time and i'm sorry to talk about this again but is a converter from ASkyblock to BSkyblock planed ? If today the answer is again 'Yes' , when do you think it will be available ?
Thanks a lot.

**Comment by Poslovitch** [comment]
The answer has always been yes. But we don't know when this will come as this is something difficult to implement.
