### ISSUE TITLE
World name has changed in 1.4.2 BSkyBlock_world to BSkyBlock-world

### ISSUE THREAD

**Issue by krustymk** [BentoBoxWorld/BSkyBlock#108]
https://github.com/BentoBoxWorld/BSkyBlock/issues/107

**Comment by Poslovitch** [comment]
May I now what's the issue here?

**Comment by tastybento** [comment]
Dupe??

**Comment by krustymk** [comment]
When i updated from 1.4.1 to 1.4.2 i changed my filenames back, then when i ran the server it generated 3 new worlds again. I guess 1.4.1 must have changed the config file and 1.4.3 didnt change it back just left it as is, i since learned the world name can be updated in the config and changed it so all good now

**Comment by Poslovitch** [comment]
Okay. Closing then.
