### ISSUE TITLE
cant interact with blocks/chests when returning to island after being in a team elsewhere

### ISSUE THREAD

**Issue by krustymk** [BentoBoxWorld/BSkyBlock#115]
**Description**
Cant interact with blocks/chests when returning to island after being in a team elsewhere and leaving it

**Steps to reproduce the behavior:**
1 Enter a team on another island
2 leave team
3 return to your own island

**Expected behavior**
To be able to interact with your own island blocks etc 

**Server Information:**

[Please complete the following information:]
Flatfile? default, not changed it
WIndows 10
Java 8
05.05 12:47:37 [Server] INFO Running SPIGOT 1.13.2.
05.05 12:47:37 [Server] INFO BentoBox version: 1.4.0
05.05 12:47:37 [Server] INFO Loaded Game Worlds:
05.05 12:47:37 [Server] INFO BSkyBlock_world (BSkyBlock)
05.05 12:47:37 [Server] INFO Loaded Addons:
05.05 12:47:37 [Server] INFO BentoBox-InvSwitcher 0.0.1-SNAPSHOT
05.05 12:47:37 [Server] INFO BSkyBlock 1.4.2
05.05 12:47:37 [Server] INFO Challenges 0.6.5-SNAPSHOT-#145
05.05 12:47:37 [Server] INFO Level 1.4.0
05.05 12:47:37 [Server] INFO WelcomeWarps 1.4.0

05.05 12:49:29 [Server] INFO Plugins (20): LuckPerms, WorldEdit, VotingPlugin, NamelessMC, CraftingStore, Vault, Votifier, ProtocolLib, DiscordSRV, BentoBox, Essentials, Herochat, QuickShop, EssentialsSpawn, AdvancedOreGen, MultiWorldMoney, Residence, PluginLibrary, Statz, Autorank

**Additional context**

Server restart doesnt help, 
/is restart works and restores players ability to interact with the island

**Comment by tastybento** [comment]
Can you explain more what the steps are in terms of commands? Especially step 3.

**Comment by krustymk** [comment]
/island team leave - to leave team
then
/island - to go to your island

**Comment by tastybento** [comment]
Weird. I can't seem replicate that right now (BTW, thanks for the gift card!).
Some questions:
1. Does this happen every time? or just randomly?
2. What error do you see when you try to interact with blocks or chests?
3. When you are on the island, can you do /island info and paste what it says. Also, in the console do /bsb info (name of player) and see what it says.

**Comment by krustymk** [comment]
Only noticed it when i left a team i set up to see how it worked, then left and noticed the issue, not tried it since
At the time i did /island info and it said it belonged to me.
Ive not tried it since.. maybe a one time glitch? Ill try again shortly

**Comment by tastybento** [comment]
@krustymk Still an issue?
