### ISSUE TITLE
Damaging entity on island sometimes kicks with message "io.netty.handler.EncoderException": java.lang.NullPointerException

### ISSUE THREAD

**Issue by MorkaZ** [BentoBoxWorld/BSkyBlock#117]
Damaging entity on island sometimes kicks with message "io.netty.handler.EncoderException: java.lang.NullPointerException."
Screen:
https://i.imgur.com/K2s5lB9.png

When I try to damage entity outside Bskyblock worlds (for example on server's spawn) then everything is fine. When this plugin is disabled then damaging entities do not create this exceptions and players are not being kicked. Kicks are very often (1 kick per 2 killed pigs). 

I am using latest ProtocolSupport, latest spigot and connecting via BungeeCord with viaVersion. I have also installed latest Bskyblock and BentoBox. I have installed also Levels for BSkyblock.

**Comment by BONNe** [comment]
Pls... at least add /bentobox v output, as LATEST plugin did not mean anything.

**Comment by Poslovitch** [comment]
That's a protocol error. We can't do anything about it.

**Comment by tastybento** [comment]
Yes, it's a ProtocolSupport problem. If you know how to look at the console then you should see errors that'll tell you where the problem is. If you still think it's us, paste the console error.

**Comment by MorkaZ** [comment]
Thank you guys for helping :).
I am linking it to ProtocolSupport's issue ticket.
