### ISSUE TITLE
/island settings is not work at 1.14 spigot

### ISSUE THREAD

**Issue by dauchu** [BentoBoxWorld/BSkyBlock#119]
**Description**

**Steps to reproduce the behavior:**
1. enter command /is settings
2. Click on anyitem

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50320768/57294243-f9b7f780-7101-11e9-9376-fc8355052cc9.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - OS: WINDOWS10
 - Java Version: JAVA8
 - BentoBox version: 1.5.0
 - Addons installed? [19:56:13] [Server thread/INFO]: Running SPIGOT 1.14.
[19:56:13] [Server thread/INFO]: BentoBox version: 1.5.0-SNAPSHOT
[19:56:13] [Server thread/INFO]: Loaded Game Worlds:
[19:56:13] [Server thread/INFO]: BSkyBlock_world (BSkyBlock)
[19:56:13] [Server thread/INFO]: Loaded Addons:
[19:56:13] [Server thread/INFO]: BSkyBlock 1.5.0
[19:56:13] [Server thread/INFO]: Challenges 0.7.5-SNAPSHOT-LOCAL
[19:56:13] [Server thread/INFO]: Level 1.4.0
[19:56:13] [Server thread/INFO]: Limits 0.2.0-SNAPSHOT
[19:56:13] [Server thread/INFO]: WelcomeWarps 1.4.0
 - Other plugins? WorldEdit, SuperTrails, PlaceholderAPI, PermissionsEx, Vault, PlayerParticles, WorldGuard, BentoBox, Essentials, EssentialsProtect, QuickBoard, EssentialsChat, EssentialsGeoIP, VariableTriggers, EssentialsSpawn

**Additional context**
I cant use /island settings because when I click item It was hold
I find that It was work at 1.13.2 but I want to use at 1.14
Is there any way to solve this?

**Comment by tastybento** [comment]
you need to use the 1.14 BSkyBlock version. It's not released yet. here's a pre-release
https://github.com/BentoBoxWorld/BSkyBlock/releases/tag/1.4.2-1.14

**Comment by dauchu** [comment]
> you need to use the 1.14 BSkyBlock version. It's not released yet. here's a pre-release
> https://github.com/BentoBoxWorld/BSkyBlock/releases/tag/1.4.2-1.14

I did 1.14 Bskyblock version but It wasnt work

**Comment by BONNe** [comment]
You need also BentoBox 1.14 version
