### ISSUE TITLE
No way to obtain original starter inventory

### ISSUE THREAD

**Issue by IITFA** [BentoBoxWorld/BSkyBlock#124]
**Description**
When you first get an island, you have some stuff in your inventory. You can reset your island, but no way to get a rest of inventory that I can find. Since this seems like it should be part of an island reset, I'm filing this as a bug. I created an island when I first installed. Threw away all my inventory. Unregistered my island to turn into the skyblock spawn. Then created a new island, but no inventory, just the island and a chest.

**Steps to reproduce the behavior:**
1. Covered above. Create island, lose everything in some manner, try a reset or create new island.

**Expected behavior**
Start over like new or have a command to fix it.

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Flatfile?
 - OS: [e.g. iOS] Linux?
 - Java Version: [e.g. Java 8] Java 8?
 - BentoBox version: [e.g. 1.7.2.21] BentoBox v1.4.0
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
09.05 23:20:58 [Server] INFO Running PAPER 1.13.2.
09.05 23:20:58 [Server] INFO BentoBox version: 1.4.0
09.05 23:20:58 [Server] INFO Loaded Game Worlds:
09.05 23:20:58 [Server] INFO AcidIsland_world (AcidIsland)
09.05 23:20:58 [Server] INFO BSkyBlock_world (BSkyBlock)
09.05 23:20:58 [Server] INFO Loaded Addons:
09.05 23:20:58 [Server] INFO AcidIsland 1.4.0
09.05 23:20:58 [Server] INFO BSkyBlock 1.4.1

**Comment by Poslovitch** [comment]
Just add a command to give the player a specific kit when he resets his island. Check BSkyBlock's config.
I'm unsure if this feature actually exists though.

**Comment by IITFA** [comment]
I could be mistaken about the inventory, I'll check.

**Comment by tastybento** [comment]
Right now, there's no feature to give players a starter inventory. On ASkyBlock, this was done by allowing commands to be run on starting an island (or resetting), so running kit or similar was the approach. This is something we can add.

**Comment by tastybento** [comment]
This will be handled by https://github.com/BentoBoxWorld/BentoBox/issues/704
