### ISSUE TITLE
Unable to use nether island

### ISSUE THREAD

**Issue by N0tMyFaultOG** [BentoBoxWorld/BSkyBlock#126]
**Description**
I upgraded from ASkyBlock to BSkyBlock recently and my old nether island didn't contain the end frames. However I updated, made new schematics via `bsbadmin schem` and put them in place. Since players who already had an island and won't reset cannot access the new island nether - obviously - and are stuck. Therefore I copy/pasted (via bsbadmin) the new nether schematic in and replaced the old one, which worked fine.
If they built the end portal and the gate opened, they are unable to walk thru it, the following issue occurs: ![](https://i.imgur.com/n37T3kq.png)

**Steps to reproduce the behavior:**
Already described above, merely the fact that people with an old island from ASkyBlock are unable to access the end.

**Expected behavior**
People with an old island should be able to access the end as well

**Screenshots**
Given above

**Server Information:**
 - Database being used (Flat file, MySQL, Mongo): BSkyBlock default, assume flat file
 - OS: Linux 3.10.0-693.11.6.el7.x86_64

 - Java Version: ![](https://i.imgur.com/BH5HXEq.png)
 - BentoBox version: ![](https://i.imgur.com/jiZivcU.png)
 - Addons installed? Answered above
 - Other plugins? ![](https://i.imgur.com/71XVeFG.png)

My end island: http://www.mediafire.com/file/xldbw02a5yccbrc/end-island.schem/file

**Comment by tastybento** [comment]
Did you paste in an end island for them too? It looks like they don’t have one so they can’t teleport anywhere. 
By the way, we are redoing schems and they’ll be replaced by blueprints. I’ll try and add a feature where if there is no island one will be made on the fly so you don’t have to do this.

**Comment by N0tMyFaultOG** [comment]
>Did you paste in an end island for them too? It looks like they don’t have one so they can’t teleport anywhere.

No, should I need to? And if so, where should I do that? Just randomly inside their island boundaries in the end?

**Comment by tastybento** [comment]
Place it roughly in the center of the island boundaries, yes. Each player has an island center location. You can find it out with the admin info command. You can paste it at the same x,y,z coordinates. It doesn't have to be exact though.

**Comment by N0tMyFaultOG** [comment]
Well, that's a a kind of ugly method isn't it? The cords prompted fit the center? Or do I need to search it manually ?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 13.05.19, 08:11, tastybento <notifications@github.com> schrieb:
Place it roughly in the center of the island boundaries, yes. Each player has an island center location. You can find it out with the admin info command. You can paste it at the same x,y,z coordinates. It doesn't have to be exact though.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BentoBoxWorld/BSkyBlock/issues/126#issuecomment-491688772",
"url": "https://github.com/BentoBoxWorld/BSkyBlock/issues/126#issuecomment-491688772",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tastybento** [comment]
If you'd like players to have end islands when they create or reset an island then make sure there's an end-island schem in the schems folder. I've attached a zip of the default one. If players already have an island but just a blank space in the end world (I assume you want an end world with islands) then you'll need to paste them manually. Alternatively, you can just use a default end world and not have end islands. 
[end-island.schem.zip](https://github.com/BentoBoxWorld/BSkyBlock/files/3175760/end-island.schem.zip)
