### ISSUE TITLE
Modify the island's initial creature

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/BSkyBlock#127]
I hope the author can add an option to the plugin's config that allows us to modify the auto-generated creatures on the island after the island is created. And be able to modify its name

**Comment by BONNe** [comment]
It is possible to do already.
You just need to create a new schem (or edit existing) that contains animal of your choice with a name of your choice.

**Comment by tastybento** [comment]
Yes, just to be clear, there are no autogenerated creatures on the island. They are part of the island's schem (soon to be renamed blueprint in 1.5.0). So like BONNe said, you can change them yourself.
