### ISSUE TITLE
Add custom island initial animals and inventory

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/BSkyBlock#129]
In the current version of BskyBlock I can't modify the island's default generated animals, and I can't modify the default inventory for each island. I hope to see this feature added in the next version! Thank you.

**Comment by Poslovitch** [comment]
You currently can. You just have to edit the schem (or the Blueprint, if you're using 1.5.0) you want to edit the animal and/or chests of. This allows you to create more chests or to use alternatives to said chests, such as Shulker boxes (like we do in the default provided End schem) or, in 1.14, barrels.

**Comment by BackWheel** [comment]
Where can I edit this project

**Comment by tastybento** [comment]
Hi @BackWheel - please watch this video for instructions! 
https://youtu.be/hFkP7hit3i4
