### ISSUE TITLE
I can not use /is

### ISSUE THREAD

**Issue by TopKruZ** [BentoBoxWorld/BSkyBlock#130]
**Description**
Hi I install bentobox and install addon Bskyblock but when I use command "/is"  this text show me.

**Screenshots**
<a href="https://www.picz.in.th/image/wVdLVS"><img src="https://sv1.picz.in.th/images/2019/05/22/wVdLVS.md.png" alt="wVdLVS.png" border="0" /></a>

**Server Information:**
- spigot-1.13.2

**Add on Information:**
- bskyblock-1.5.0 
- challenges-0.7.0

help me please I don't khow what should I do

**Comment by tastybento** [comment]
Hi there - sorry you're having a problem.

Do you know how to read your console log? Share what error you see in there when you run the command.

Also, can you do /bbox version and share what it says?

**Comment by TopKruZ** [comment]
![2562-05-24_12 57 45](https://user-images.githubusercontent.com/50898222/58305798-9e854500-7e23-11e9-9380-08fa6fadbf61.png)


please help me how to fix it?

**Comment by Poslovitch** [comment]
If you're using BSkyBlock 1.5.0, then you need to use BentoBox 1.5.0 as well.

**Comment by TopKruZ** [comment]
Where can i download BentoBox 1.5.0 I found only 1.4.0

**Comment by BONNe** [comment]
1.5.0 is not released yet.
It is available only in snapshots
https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/

**Comment by Poslovitch** [comment]
The same should go for BSkyBlock 1.5.0 actually...

**Comment by TopKruZ** [comment]
Thank you very much. I appreciate it.

**Comment by Poslovitch** [comment]
Well, it's actually written black on white. « BSkyBlock 1.5.0 requires BentoBox 1.5.0 »
https://github.com/BentoBoxWorld/BSkyBlock/releases/tag/1.5.0
