### ISSUE TITLE
Looks a little messy.

### ISSUE THREAD

**Issue by Tdmy** [BentoBoxWorld/BSkyBlock#138]
Can you add Chinese? It looks messy.
![QQ截图20190611200427](https://user-images.githubusercontent.com/49546360/59270512-3be5d300-8c84-11e9-93af-7de70bbf5bf3.png)

**Comment by tastybento** [comment]
This text can be set by you. Use /bsb bp to edit and change the blueprint descriptions or edit the JSON file in the blueprints folder.
