### ISSUE TITLE
Nether Blueprint Skeleton Spawners

### ISSUE THREAD

**Issue by Jerethkhan** [BentoBoxWorld/BSkyBlock#140]
**Description**
This is an assumption on my part that the Skeleton Spawner in the nether blueprint is there to spawn Wither Skeletons. Since Wither Skeletons are now separate entities Skeleton Spawners will no longer spawn them in the Nether.

**Steps to reproduce the behavior:**
Put a Skeleton Spawner in the Nether.

**Expected behavior**
Prior to "The Flattening" Wither Skeletons were spawned in the nether from Skeleton Spawners. I expect Wither Skeletons to spawn in the Nether. This will require the Blueprint to have a Wither Skeleton Spawner.

**Screenshots**

**Server Information:**
Server: Paper 1.14.2 R-0.1
BentoBox: Version 1.5.1
BentoBox Plugins: Biomes 1.5.0.0, BSkyBlock 1.5.0, Challenges 0.7.5, Level 1.5.0, MagicCobblestoneGenerator 1.5.0.1

**Additional context**
Posted here on the advice of Poslovitch

**Comment by tastybento** [comment]
Yes, the default Nether blueprint has 3 spawners - a Blaze, a Magma Cube and a Skeleton spawner. I'll add a wither one.

**Comment by Poslovitch** [comment]
I'd rather suggest you to change the skeleton spawner to wither skellies.
