### ISSUE TITLE
Nether Biome

### ISSUE THREAD

**Issue by Joeripoes** [BentoBoxWorld/BSkyBlock#143]
When a player gets his island in the nether., the biome is set to plains, thus spawning zombies and stuff in the nether. When flying out of the island radius the biome becomes nether. 

Am I missing something or is there no way to change this using bentobox.

I have no addons installed, only bskyblock. I use bentobox 1.5.0

**Comment by tastybento** [comment]
This was fixed in BentoBox 1.5.1. https://github.com/BentoBoxWorld/BentoBox/issues/745. You'll need to use WorldEdit or the Biomes add-on to put the biomes back to Nether (and End). Sorry.
