### ISSUE TITLE
Missing some World flags, island flags, and default island settings in config.yml

### ISSUE THREAD

**Issue by LordSheep** [BentoBoxWorld/BSkyBlock#151]
**Description**
In the BSkyblock config.yml file i'm missing some world flags island flags, and default island settings. 

**Screenshots**
In-Game BSkyblock Settings (Has every world flag)
![image](https://user-images.githubusercontent.com/30538383/60381583-b3d83980-9a89-11e9-96f0-3efbfac08ae5.png)

Most recent config (Missing flags)
![image](https://user-images.githubusercontent.com/30538383/60381456-c8b3cd80-9a87-11e9-80b2-6c3f89243f6d.png)

Left (28th config)     Right (3rd backup - 25th config)
![image](https://user-images.githubusercontent.com/30538383/60381447-a4f08780-9a87-11e9-9a75-cdefc494b36e.png)

Left (28th config)     Right (3rd backup - 25th config)
![image](https://user-images.githubusercontent.com/30538383/60381515-93f44600-9a88-11e9-8643-9694ad50293b.png)

**Server Information:**

[Please complete the following information:]
 - Database being used: JSON
 - OS: No clue
 - Java Version: No clue
 - BentoBox version: 1.5.3
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
   Other plugins? [Do '/plugins' and copy/paste from the console]
![image](https://user-images.githubusercontent.com/30538383/60381651-ad968d00-9a8a-11e9-8735-da012f47bb88.png)

**Additional context**
History

- On June 25th I installed BentoBox, BSkyblock and biomes, challenges, level, limits, and warps addons on spigot 1.14.2. 

- I experimented with the server over the day while making some backups. 

- On the 28th June I decided to delete the files and reinstall all my plugins. I installed BentoBox, BSkyblock and the same addons I did on the 25th on spigot 1.14.2.
 
- I looked at the bskyblock config that was just created and decided to text compare with the bskyblock config I edited on the 25th to see what changes were made. 
 
- I then saw there settings/flags missing on the config I just installed compared to the most recent one I backed up on the 25th. I tried restarting and stopping the server to see if they would appear but the config is still missing some things.
 
- Additional info: On the 25th I made 3 backups, the first two backups had the flags and settings missing in the config as well. Only the 3rd backup had the flags and settings present. So I did something that made them appear but I don't know what it is. 
 
- How do I get the flags and settings that are missing in the latest version of my config? Can I just copypaste them in?

**Comment by tastybento** [comment]
This is not a bug. The settings are only put into config.yml if they are changed from the default in the GUI. Once they are in there, they do stay, but don't get put in automatically.
I recommend you just edit the settings in the GUI how you like. If you really would like to add them manually, you can copy and paste them over.
