### ISSUE TITLE
island recreation

### ISSUE THREAD

**Issue by cptmuff** [BentoBoxWorld/BSkyBlock#153]
Im not sure what this issue is coming from. have been using bskyblock for a bit now and it has been working fine. Yesterday i went to create a island and it gave me console errors. Now everytime i restart my server I am forced to create a new island, followed by console errors.

**Comment by tastybento** [comment]
Hmm, sorry that's happening. If you'd like us to help then you should file [this bug report](https://github.com/BentoBoxWorld/BSkyBlock/issues/new?template=bug_report.md) and copy in your console errors so we can see what's happening.
