### ISSUE TITLE
Island restarting!

### ISSUE THREAD

**Issue by cptmuff** [BentoBoxWorld/BSkyBlock#154]
**Description**
I have no clue what is going on bentobox and bskyblock were working fine 2 days ago. every time I restart my server, I am forced to create a new island. When I do it feeds my console with errors.

**Steps to reproduce the behavior:**
1. In game after server restart
2. type /is to go to island
3. Instead it has me create a new island
4. when i click on the island in gui I get error in console

 - Database being used (Flat file, MySQL, Mongo): MySQL
 - Java Version: [1.13.2]
 - BentoBox version: [1.5.3]
 - Addons installed? : bskyblock 1.5.0, levels 1.5.0
 - Other plugins? :WorldEdit, ChatColor2, PlaceholderAPI, AutoBroadcast, ClearLag, NoPluginViewer, Lockette, Votifier, ProtocolLib, WorldGuard, CommandSpy, NoHopper, PermissionsEx, MOTD, Vault, GAListener, Essentials, ChatInjector, EpicSpawners, HolographicDisplays, BuycraftX, Citizens, EssentialsProtect, BentoBox, EssentialsChat, TAB, EssentialsSpawn, CratesPlus, ShopGUIPlus, TitleManager, CustomOreGen, Multiverse-Core, Multiverse-Portals

[Console.txt](https://github.com/BentoBoxWorld/BSkyBlock/files/3347586/Console.txt)

**Comment by tastybento** [comment]
It looks like your server jar is corrupted. Did you compile it yourself? I recommend recompiling or downloading paper or something. These methods should not be missing from the server:

```
01.07 22:52:56 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server._INVALID_getOnlinePlayers()[Lorg/bukkit/entity/Player;
01.07 22:52:56 [Server] WARN Plugin GAListener v1.3.2 generated an exception while executing task 24
```
and
```
01.07 22:53:34 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/BoundingBox
```

**Comment by freezweb** [comment]
i have the same issue on Paper 1.14.3

**Comment by tastybento** [comment]
@freezweb Share your console log so we can look at it.

**Comment by tastybento** [comment]
@cptmuff Is this still a problem?

**Comment by BravelyTorn** [comment]
Ditto with Paper 1.14.3 on this issue. I'll attach a console log within the next day since e'erbody else went silent on this issue.

**Comment by freezweb** [comment]
i send you a compleete backup of the skyblock server, just say me your email adress

**Comment by BravelyTorn** [comment]
@tastybento haven't been able to stop server and get a log (players still online), but I can see a couple of red lines of error text that say that there is an issue with overlapping islands, and that islands are being sent to trash. Also sum'n about duplicate islands and picking owners. (proper log coming as soon as possible)

**Comment by tastybento** [comment]
@BravelyTorn Okay. I'm not sure it's the same issue as this one that was reported because the log in the original mentioned missing classes, so please make your own ticket and fill out all the relevant info in the report. I will say that depending on the version of your BentoBox and other items, it sounds like a known issue that was fixed, but let's see what the problem is first.

**Comment by tastybento** [comment]
@freezweb Can you make your own ticket first and fill out the details there?  Also, you can email to tastybento at Bentobox dot world.
