### ISSUE TITLE
Island selector

### ISSUE THREAD

**Issue by Vogoun** [BentoBoxWorld/BSkyBlock#156]
Hi, I am using your skyblock plugin on my server for some time.
but, there is a little problem. Is there any way to prevent players from creating "Harder Island" and Double Island? Like permission or customise that menu with island types?

**Comment by tastybento** [comment]
Yes! Use /bsb bp to get into the Blueprint admin menu. Then select the harder or double blueprints and at the bottom of the guy is a painting. Click it to require permissions. The text will tell you what the permission is.

**Comment by Vogoun** [comment]
Thanks! I just couldn´t find it.
