### ISSUE TITLE
Prevent vanilla nether/end

### ISSUE THREAD

**Issue by KDanielleGeiger** [BentoBoxWorld/BSkyBlock#165]
More of a question than an issue. Is there a way to prevent the vanilla nether and end worlds from generating?

**Comment by tastybento** [comment]
Yes. Just set the generate flag for the nether and end to false in BSkyBlock's config.yml and those worlds will not be generated at all.

**Comment by KDanielleGeiger** [comment]
> Yes. Just set the generate flag for the nether and end to false in BSkyBlock's config.yml and those worlds will not be generated at all.

When I set the flag to false, no nether/end worlds are generated at all. I want the BSkyBlock nether/end worlds, but not the vanilla nether and end worlds. Is there a way to ONLY generate the BSkyBlock nether and end?

**Comment by tastybento** [comment]
Oh I see. Hmm. I don't think so if you still want to keep "world" as a world. You could make BSkyBlock the primary world (see the BentoBox wiki for instructions) - I think that's the only way.
