### ISSUE TITLE
Spawn Protection

### ISSUE THREAD

**Issue by AcesGamingUK** [BentoBoxWorld/BSkyBlock#167]
**Description**
Unable to use pressure-plate, button etc within 50blocks of spawn

**Steps to reproduce the behaviour:**
1. Make a spawn
2. Place item (pressure-plate, button etc) 
3. Try to use an item

**Expected behaviour**
To use the above items as intended

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - BentoBox version 1.5.3 
<details>
  <summary> - Addons installed?</summary>
Loaded Addons:
Biomes 1.5.0.0 (ENABLED)
BSkyBlock 1.5.0 (ENABLED)
Challenges 0.7.5 (ENABLED)
DimensionalTrees 1.0.1-SNAPSHOT (ENABLED)
Greenhouses 0.3.0-SNAPSHOT (ENABLED)
IslandFly 0.2.0 (ENABLED)
Level 1.6.0-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
MagicSummon 1.5.0.0-SNAPSHOT-LOCAL (ENABLED)
VoidPortals 1.5.0.0 (ENABLED)
WelcomeWarps 1.5.0 (ENABLED)`
</details> 
<details>
  <summary> - Other plugins?</summary>
AsyncWorldEdit, AutomaticInventory, AutoPickup, Bank, BentoBox, BlocksHub, ChatReaction, ChestSort, CMI, CMIEInjector*, Core, CoreProtect, CustomEnderChest, DeluxeMenus, DiscordSRV, FastLeafDecay, FeatherBoard*, Horizon, LiteBans, LiteBansGUI*, LuckPerms, LuckPerms-GUI, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, MVdWUpdater*, PhantomSpawnControl, PL-Hide*, PlaceholderAPI*, PlugMan, ProtectionLib*, ProtocolLib*, ProtocolSupport, ServerListPlus*, Shop, TradeMe, TreeCapitator*, TrollBoss, Vault*, ViaVersion*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, Zenchantments
</details>

**Additional context**
unloaded all plugins but bento+addons the issue persisted, added all plugins and removed bentobox and was able to use as expected

**Comment by tastybento** [comment]
What error do you see when you try to use the item? If there’s no error then it’s the server blocking it. 
You can also run the /bsb why command on a player and look in the console to see why it may be blocking. 
Sounds like a server spawn protection to me though.

**Comment by AcesGamingUK** [comment]
there is no error, no response at all in fact,
did the "/bsb why" command and console just said this 
<details>
  <summary> Console</summary>
"[BentoBox]: Why: PlayerInteractEvent in world skyblock at 6,155,12
[BentoBox]: Why: MrBee66 PRESSURE_PLATE - OP
</details>
[This is my issue](https://www.screencast.com/t/q3cpdo2D9i)

**Comment by tastybento** [comment]
Yep, so that's not being prevented by BentoBox. You'd see an error and the why command is saying that it's allowed by BentoBox because you are Op. So spawn is being protected, most likely by the server. What do you have in your server.properties file? Set it to 0 like:

```
spawn-protection=0
```

Alternatively, just stick a spawn island at 0,0.

**Comment by AcesGamingUK** [comment]
the spawn island is at 0.0

the issue goes away if i disable bentobox 

)

spawn-protection=15 
yet if i go 51+ blocks from spawn i can use things fine
but still within the spawn region 
<details>
  <summary> Spawn Island Config</summary>
{
  "deleted": false,
  "uniqueId": "BSkyBlock4059d796-faa4-474e-be58-7a2eedaa4c66",
  "center": [
    "skyblock",
    0.0,
    120.0,
    0.0,
    0.0,
    0.0
  ],
  "range": 400,
  "protectionRange": 50,
  "maxEverProtectionRange": 50,
  "world": "skyblock",
  "gameMode": "BSkyBlock",
  "createdDate": 1563574396390,
  "updatedDate": 1563574396390,
  "members": {},
  "spawn": true,
  "purgeProtected": false,
  "flags": {
    "TURTLE_EGGS": 1000,
    "CRAFTING": 0,
    "DRAGON_EGG": 1000,
    "EGGS": 1000,
    "CROP_TRAMPLE": 0,
    "MILKING": 0,
    "LEASH": 1000,
    "BREAK_BLOCKS": 1000,
    "FIRE_EXTINGUISH": 1000,
    "MONSTER_SPAWN": -1,
    "EXPERIENCE_BOTTLE_THROWING": 1000,
    "LOCK": 0,
    "FROST_WALKER": 1000,
    "BREEDING": 1000,
    "TRADING": 1000,
    "NOTE_BLOCK": 0,
    "HURT_MONSTERS": 0,
    "TNT_DAMAGE": -1,
    "COLLECT_WATER": 1000,
    "ARMOR_STAND": 1000,
    "JUKEBOX": 1000,
    "POTION_THROWING": 1000,
    "ITEM_DROP": 1000,
    "TNT_PRIMING": 1000,
    "HURT_ANIMALS": 1000,
    "END_PORTAL": 1000,
    "DISPENSER": 1000,
    "REDSTONE": 1000,
    "BUTTON": 1000,
    "FIRE_BURNING": -1,
    "RIDING": 1000,
    "ANVIL": 1000,
    "NULL_FLAG_3fd5b4eb-cc5d-49bb-add8-3610e7e0a377": 0,
    "FIRE_SPREAD": -1,
    "FURNACE": 0,
    "FISH_SCOOPING": 1000,
    "EXPERIENCE_PICKUP": 0,
    "BREWING": 0,
    "GATE": 1000,
    "COLLECT_LAVA": 1000,
    "GREENHOUSE": 1000,
    "PVP_OVERWORLD": -1,
    "DYE": 1000,
    "ENDER_PEARL": 1000,
    "TRAPDOOR": 0,
    "BOAT": 1000,
    "ITEM_FRAME": 1000,
    "BUCKET": 1000,
    "SPAWN_EGGS": 1000,
    "PVP_NETHER": -1,
    "BEACON": 0,
    "ANIMAL_SPAWN": 0,
    "ENCHANTING": 0,
    "NULL_FLAG_bd6186de-9fb9-4ba3-85b6-2c97c1f92be0": 1000,
    "DROPPER": 1000,
    "LEAF_DECAY": -1,
    "FIRE_IGNITE": -1,
    "CONTAINER": 1000,
    "LEVER": 1000,
    "HURT_VILLAGERS": 1000,
    "ITEM_PICKUP": 0,
    "DOOR": 0,
    "MOUNT_INVENTORY": 1000,
    "NETHER_PORTAL": 1000,
    "PRESSURE_PLATE": 0,
    "SHEARING": 1000,
    "NAME_TAG": 1000,
    "FLINT_AND_STEEL": 1000,
    "BED": 1000,
    "PVP_END": -1,
    "HOPPER": 1000,
    "CHORUS_FRUIT": 1000,
    "PLACE_BLOCKS": 1000,
    "MINECART": 1000,
    "BIOMES_ISLAND_PROTECTION": 1000,
    "CHALLENGES_ISLAND_PROTECTION": 0,
    "MAGIC_SUMMON_ISLAND_PROTECTION": 1000
  },
  "history": [
    {},
    {}
  ],
  "levelHandicap": 0,
  "spawnPoint": {
    "NORMAL": [
      "skyblock",
      -1.934424385956482,
      122.0,
      2.8063502307698314,
      -143.4311065673828,
      23.710506439208984
    ],
    "NETHER": [
      "skyblock_nether",
      0.5,
      125.0,
      2.5,
      0.0,
      30.0
    ],
    "THE_END": [
      "skyblock_the_end",
      -0.5,
      126.0,
      -0.5,
      315.0,
      30.0
    ]
  },
  "doNotLoad": false
}


</details>

**Comment by tastybento** [comment]
If spawn-protection is set at 15, then the server is protecting everything within a radius of 15 blocks from 0,0. So, change it to 0 and it should work.
