### ISSUE TITLE
Support request - Spawning

### ISSUE THREAD

**Issue by millermx** [BentoBoxWorld/BSkyBlock#169]
**Description**
Another User posted a picture of:

"respawn on island: True"

I cannot find this option in my config and I am using the latest version.
My reasoning for wanting this is so I can set it to false. 
Ex. On player death on the "BSKYBLOCK world". I would like for them to re-spawn in a different world we can call "world A."

Thank you so much in advance.

**Server Information:**
Spigot version 1.14.4

**Comment by tastybento** [comment]
Sorry for the late reply. World settings are set by doing /island settings and then clicking on the World Settings tab. They are all in there, including the setting to respawn on your island or not.
