### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by Guns29** [BentoBoxWorld/BSkyBlock#175]
**Description**
When placing water down there is no flow

**Steps to reproduce the behavior:**
Placing down

**Expected behavior**
when placing lava or water down there is no flow

**Screenshots**
![2019-08-07_20 54 29](https://user-images.githubusercontent.com/27779616/62667440-a69a4e80-b955-11e9-9d5a-41f0fef1e4fb.png)

**Server Information:**

[Please complete the following information:]
server: spigot 1.14.3

**Comment by tastybento** [comment]
Flow outside islands is disabled by default. You can change it by being Op and doing **/island settings** -> World Settings tab and then allowing flow.

However, normally your island should not see this. It looks like this island is not owned for some reason. As Op, do **/bsb info** on the island. I expect it will say it is not owned.
