### ISSUE TITLE
Hope to support Minecraft be 

### ISSUE THREAD

**Issue by junxiesky** [BentoBoxWorld/BSkyBlock#176]
**Description**
A clear and concise description of what your problem is.
I hope it supports MineCraft BE 
**Screenshots**
I don't know what pictures to add
**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by Poslovitch** [comment]
That's planned... But we need to figure out what kind of software is used to run BE servers.

Closing for now.
