### ISSUE TITLE
No jar file

### ISSUE THREAD

**Issue by SMAK1997** [BentoBoxWorld/BSkyBlock#177]
**Description**
Their is no jar file in the BSkyBlock add-on for BentoBox.

0. Install BentoBox and run it on the server at least once to create its data folders.
1. Place this jar in the addons folder of the BentoBox plugin.

This is what it says in the Installation section of the page. Is "this" jar the jar for the BentoBox?

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/53926479/62752815-6c7a9b00-ba82-11e9-8857-f2a56a24a436.png)

**Comment by BONNe** [comment]
There is.
For almost every addon it exists.
And in your screenshot, you can get till that.

5 Links are in the top of your screenshot -> commits / branches /releases / contributors / EPL-2.0

Click on Releases and you will find jars.

Also in ReadMe.md file (if you scroll your page a bit down, there is BUILD icon. If you click on it, it will open a development page, that also contains jars.

**Comment by SMAK1997** [comment]
I got confused a bit that the jar file was not in with the other things. But i guess its that way for a good reason and people like me need to look around a bit.
Thanks
