### ISSUE TITLE
can't use 

### ISSUE THREAD

**Issue by p82183645** [BentoBoxWorld/BSkyBlock#179]
![image](https://user-images.githubusercontent.com/5382252/62798073-f3298980-bb0f-11e9-8169-034723eda0f1.png)

i can't use in 1.14.4 , the error
help me

paper 1.14.4

the log
https://www.dropbox.com/s/1s5eczh0fildmdx/latest.log?dl=0

**Comment by tastybento** [comment]
Try the latest releases here: https://ci.codemc.org/job/BentoBoxWorld/

```
[01:54:00] [Server thread/INFO]: [BentoBox] Skipping BSkyBlock as it is incompatible with the current version of BentoBox or of server software...
```

Your BSkyBlock addon does not fit with BentoBox. We'll be releasing the latest version this weekend.
