### ISSUE TITLE
Cooped players can not do anything

### ISSUE THREAD

**Issue by cloakfox** [BentoBoxWorld/BSkyBlock#182]
Players that have coop on an island are unable to break/place blocks or access containers.

They can basicly do nothing.

PaperSpigot 1.13.2
Running bskyblock build: 424

**Comment by wellnesscookie** [comment]
Island owners can decide what coops can do via /is settings. Island managments that are intended for coops to be used/allowed must be green-lighted for Coop rank.

**Comment by tastybento** [comment]
@cloakfox Check the settings like @wellnesscookie says. If there's still an issue, let me know.
