### ISSUE TITLE
Islands are not saving when the server restarts

### ISSUE THREAD

**Issue by VooDooMedic** [BentoBoxWorld/BSkyBlock#190]
### Islands are not being saved when the server restarts

When restarting my server (hosted) any islands that were made before the server was restarted are removed.

1. Create a new island using the /island command
2. Go back out of the island using a warp command.
3. Restart the server
4. try to go back into the island by using the same command as before.
5. the option appears to "start your island"
#### Expected behavior

When restarting the server the island should remain as player saved data should be stored because if we have brought items to the island it would be bad if they are lost
#### Server

 - OS: **Win10**
 - Java version: **________**

#### Plugins

```
Bentobox. buycraft chatcolour2, Citizens, clearlag, coreprotect, crazy crates, denizen, dltradersplus, essentials, essentialschat, ezbroadcast,luckperms, multiverse-core, openinv, sdfeconomy, sentinel, simplespawn-core, timeismoney, uberenchant, vault, voxelSniper, Worldedit, Worldguard
```

##### BentoBox and Addons

```
Running PAPER 1.1.4.4
Bentbox: 1.6.0
Database: MYSQL
Bskyblock_world (BSkyBlock): Overworld Nether, End
Loaded addons:
Bskyblock 1.6.0
Challenges 0.7.5 (INCOMPATIBLE)
IslandFly 0.2.0 (ENABLED)
Level 1.6.0-SNAPSHOT-b276 (ENABLED)
WelcomeWarps 1.5.0 (ENABLED)
```

##### Configuration

 - Database: **MYSQL**

**Comment by BONNe** [comment]
Can you please provide a log file? (when islands disappear)

I know it is a much to ask, but I assume in it you will find -> cannot load null objects or something similar. 
Lately a lot of people is reporting it in discord.

**Comment by VooDooMedic** [comment]
How do i access the log file?

**Comment by tastybento** [comment]
It’s your console log. When you shut down the server it will be saved as latest.log in the logs folder of your server.

**Comment by tastybento** [comment]
Is your database setup okay? Try using JSON instead to start.
