### ISSUE TITLE
is top

### ISSUE THREAD

**Issue by leoncp9** [BentoBoxWorld/BSkyBlock#199]
why /is top
show me a empty menu?

**Comment by leoncp9** [comment]
what is command for add member to our island?

**Comment by BONNe** [comment]
I assume is the top shows empty menu, because there are no players who level are calculated?

And for a team it is ./is team

**Comment by tastybento** [comment]
Some have to type ‘/is level’ to get a level first. And it has to be > 0

For teams, use the ‘/is team’ command. To invite some use ‘/is team invite [player name]’

**Comment by leoncp9** [comment]
my level is 58, and i am not in top 10
https://prnt.sc/p6jewt

**Comment by tastybento** [comment]
In order to be in the top ten, players must have the `bskyblock.intopten` permission. Maybe that was removed for some reason. You should make sure each player has it.

If that doesn't fix your issue, then respond with the console output from `/bbox version` so I know what versions you are using.

**Comment by leoncp9** [comment]
i have add now bskyblock.intopten, but /is top show me a empty menu
i use BentoBox-1.8.0-SNAPSHOT-b1383
photo
https://prnt.sc/p6jmrl

**Comment by leoncp9** [comment]
wait now work, i do /is level and than he work
