### ISSUE TITLE
Control Panel GUI

### ISSUE THREAD

**Issue by OHutchyHutch** [BentoBoxWorld/BSkyBlock#200]
#### Is your feature request related to a problem?

No

#### Describe the solution you'd like us to implement.

A control panel GUI like what was present in ASkyBlock

#### Describe alternatives you've considered.

Using an alternative plugin like chestcommands (issue is they aren't 1.13+)

### Additional context

Nah, really I just like GUI's so more of that please.

**Comment by tastybento** [comment]
Actually, there is a ControlPanel addon now. Here it is: https://github.com/BentoBoxWorld/ControlPanel
