### ISSUE TITLE
Errors with gui ?

### ISSUE THREAD

**Issue by Killance** [BentoBoxWorld/BSkyBlock#203]
Hello,

I have a problem with the addon BSkyblock (or maybe Bentobox itself, I don't know) on my server. When I execute a command that opens a GUI, nothing happens on the server except an error in the console. Examples with the commands /is create and /is reset (nothing is reseted after the execution) : https://pastebin.com/C9qiKCa6

I already tried to reset all the configs and reconfigure them but no changes.

The server runs PaperMC 1.14.4 (build 137).

Best regards,

Killance

**Comment by BONNe** [comment]
It relates to BentoBox issue. But it looks like the issue is with BluePrints. Some of them does not have valid materials for icons.

**Comment by Killance** [comment]
Indeed, the name of material for the icons seems to be case sensitive ^^ Thank you for your help
