### ISSUE TITLE
ASkyBlock - Low TPS

### ISSUE THREAD

**Issue by Hite29** [BentoBoxWorld/BSkyBlock#206]
Hi i have very low TPS on my skyblock server, askyblock make tons of lag.

There is a timings : https://timings.aikar.co/?id=a6537a9b4ea8441dbb4810ceda76a589 

Can u help me?

**Comment by BONNe** [comment]
This is BentoBox and BSkyBlock.
It cannot be helped here. It is a different code, and different version.

**Comment by Hite29** [comment]
Okay, soo where i can report bug with askyblock?

**Comment by BONNe** [comment]
and by a fast look at your timings, it is not askyblock that is causing lag.
It is oregenerator, crazy auctions and shop gui plus.

As much as I know, ASkyBlock is not maintained anymore.

**Comment by Hite29** [comment]
Okay thanks :)
