### ISSUE TITLE
Blueprint name colors are parsed incorrectly

### ISSUE THREAD

**Issue by N0tMyFaultOG** [BentoBoxWorld/BSkyBlock#213]
#### Describe the bug

The color codes in the `default.json` blueprint are not translated to proper colors ingame https://github.com/BentoBoxWorld/BSkyBlock/blob/8917a1d4dbd927ffc1845f6bde09f84d16f3708b/src/main/resources/blueprints/default.json#L4-L9 results in
![](https://i.imgur.com/cIDvHj9.png)
It colors them correctly, yet it also contains one of those ugly chars.

#### Steps to reproduce the behavior

Install the BSkyBlock addon and run /is

#### Screenshots and videos

Already posted above

#### Expected behavior

Either strip them completely (like in the other files) or a solution to translate them properly would do it.

#### Server

 - OS: Linux 3.10.0-693.11.6.el7.x86_64
 - Java version: OpenJDK 64-Bit Server VM 25.212-b01

#### Plugins

-

##### BentoBox and Addons

![](https://i.imgur.com/V0Dc5wP.png)

##### Configuration

 - Database: **JSON**

**Comment by Poslovitch** [comment]
Might actually be à BentoBox issue as well. Shouldn't we do some prévention code international Bbox @tastybento ?

**Comment by N0tMyFaultOG** [comment]
I could not find a similar case where colors are not parsed correctly, so I quoted it on here, but since this is just an addon, bbox might be the root cause.

**Comment by tastybento** [comment]
There must be something else going on here because I don't see this issue. 
<img width="412" alt="Screen Shot 2019-11-02 at 4 21 40 PM" src="https://user-images.githubusercontent.com/4407265/68078099-e7ef9e00-fd8c-11e9-817f-10f9520088d5.png">
What happens if you change the § to &? The § character is a native Bukkit color code that we don't touch or strip. Usually we use & because it's easier to type.

**Comment by N0tMyFaultOG** [comment]
![](https://i.imgur.com/YhwSe9f.png)
That happens with `&`, I'm wondering which version you are on or how your default.json values are named. Odd that it only happens to me.

**Comment by tastybento** [comment]
I'll fix the translation of & and let's see if that helps. I am using the latest version of everything.

**Comment by N0tMyFaultOG** [comment]
> I'll fix the translation of & and let's see if that helps. I am using the latest version of everything.

Yeah, I just setup a new server and got both from the CI. I gave it a shot with Paper and Spigot, no luck tho.

**Comment by tastybento** [comment]
What client are you using? And what locale? I see this at the bottom of the description:
<img width="235" alt="Screen Shot 2019-11-02 at 5 10 40 PM" src="https://user-images.githubusercontent.com/4407265/68078489-c47c2180-fd93-11e9-9d26-d7e45ce205c5.png">

**Comment by N0tMyFaultOG** [comment]
Locale default, that's just the extended NBT info if you enabled F3+H

**Comment by tastybento** [comment]
okay, well, try the new build once it's ready on the CI - use the default.json that has &'s in it instead of §. Let's see if that matters.

**Comment by N0tMyFaultOG** [comment]
Yeah, the latest changes resolved it.
![](https://i.imgur.com/3qhDbXd.png)
Nice one, thanks ;p
