### ISSUE TITLE
Clear inventory on island reset

### ISSUE THREAD

**Issue by Reg-Ed** [BentoBoxWorld/BSkyBlock#224]
### Description
Option to clear player inventory on island reset.
#### Is your feature request related to a problem?
No.

#### Describe the solution you'd like us to implement.
I see in the config there is the option to clear a player inventory on island create/go and also leave, but not for when the player resets their island.  For servers that have separate inventories for Skyblock this could be considered undesirable behaviour because it would be easy for a player to start an island, harvest all the blocks, reset, harvest more blocks etc leading to the player having more resources than they should.

**Comment by tastybento** [comment]
This is covered by the `island.reset.on-join` or `island.reset.on-leave` sections in BSkyBlock's config. You can have inventory cleared when the player resets and joins the island or as they are leaving the island after a reset. It's a subtle difference but just affects the timing of when the resets happen.

**Comment by Reg-Ed** [comment]
Ah, I didn't notice the fact that the config options were in a tree like that.
> What the addon should reset when the player joins or creates an island/leaves or is kicked from an island

out of context sounds like inventory clearing options for any join/create/leave/kick.

I think I get it, will have to test the behaviour next time I get the opportunity to restart the server.  I'm worried there might be a race condition between my world manager loading the inventory for Skyblock and BSkyBlock clearing the inventory (if BSkyBlock wins, the player will still end up with an inventory they shouldn't have.)

Thanks for the response, I'll let you know if this turns out to be a problem.

**Comment by tastybento** [comment]
Yeah, it's not super clear and I think the comments need rewriting to make it cleared. The join/leave options are there to hopefully enable you to avoid the race conditions, but let's see.

**Comment by Reg-Ed** [comment]
Alrighty well I've done a little experimentation and clearing the inventory on join/create seems to be the most appropriate out of the two.  If you clear on leave and the player resets their Skyblock from another world, that world's inventory will be cleared (and lost) before the player is teleported to their new Skyblock with their inventory from the old one.

In my experiments using clearing on join/create the Skyblock inventory was correctly cleared however, I'm not convinced that it's not just a fluke that the race was won in my favour.

I've had a look through the BB repo but I couldn't find the listener that relates to players leaving or joining an island, however from the other Listeners that implement inventory clearing I don't imagine there's any kind of tick delay before the inventory is cleared.

My world manager loads the new inventory in on PlayerChangedWorldEvent so if BSkyBlock clears the inventory on this event also, the race condition very much does exist and I would expect the order of execution not always to be in my favour.

Other than enforcing a delay on the BSB clearPlayersInventory() function I'm not entirely sure how to get around this so I would welcome your thoughts if you have any.

**Comment by tastybento** [comment]
The sequence of events on a new island creation is as follows:

1. Island is created
2. The player is teleported to the island.
3. After teleporting is completed, the player receives the "Teleported to island" message
4. New island commands are executed, if any
5. Enderchest is cleared if set
6. Inventory is reset if set
7. Money is reset if economy exists and setting is true
8. Health same
9. Hunger reset
10. XP reset.

If you'd like to look to the code, have a look at the IslandsManager class lines 677 onwards. But given this, I think you are safe.

Now, there is a listener on `PlayerChangedWorldEvent` that's related, but it's to clear inventory if required from kicking a player from a team. That's done in the JoinLeaveListener and the priority for this is Bukkit HIGHEST, which means it actually gets run last.

**Comment by Reg-Ed** [comment]
Wonderful, very helpful thank you.  I foolishly assumed that BB was clearing the inventory based on some world-change event, which it's not.

BB calls teleport on a player, which triggers my world-change listener and I'm therefore guaranteed to execute before control returns to BB to clear the inventories.

All cleared up, thank you for taking the time.
