### ISSUE TITLE
Nether quartz on nether top

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/BSkyBlock#226]
#### Is your feature request related to a problem?

No, allow generation of nether_quartz on the top of the nether dotted around only a few percent chance of it to spawn though something like 10%

#### Describe the solution you'd like us to implement.

Allow server owners to choose what spawns there with the glowstone and netherrack

#### Describe alternatives you've considered.

None

### Additional context

None

**Comment by tastybento** [comment]
World gen is done by the respective addons, so I moved this to BSkyBlock. It sounds like a reasonable request. I always wonder if players ever realize there's a ceiling up there!

**Comment by johncsuti** [comment]
I had to show my friend that it was a there in the server he was buying glow stone from my shop and I'm like "yo look up" he was amazed and he has been playing the server off and on for over two years. Also thanks for moving this but this should be added not to just Bskyblock but to all of them. If you are worried about the nether being too over powered just think of the regular end having so much nether quartz and skyblock doesn't have that

**Comment by tastybento** [comment]
Noted.

**Comment by johncsuti** [comment]
When can i expect this to be a thing or is it too early to tell?

**Comment by tastybento** [comment]
Maybe this holiday period.

**Comment by johncsuti** [comment]
Thanks

**Comment by tastybento** [comment]
Well, I couldn't do any coding, but I'll be looking at this.

**Comment by johncsuti** [comment]
Okay sounds good! As long as you make it so it will regenerate the top of the nether and keep islands.

**Comment by tastybento** [comment]
I'm not sure what you mean exactly, but chunks are only re/generated when an island is deleted. So current islands won't magically have the ore. This would be something that would occur for new islands and resets if it was applied to an already running game, unfortunately.

**Comment by johncsuti** [comment]
I was wanting to have this but not have to regenerate the islands. So no one losses progress on there nether.

**Comment by Bricec6** [comment]
Hello, It should be possible to disable this feature, for example I wouldn't want it.
Otherwise I'd have to adapt to it. I wouldn't mind, either.

**Comment by tastybento** [comment]
This enhancement got stalled because it would only work for new chunks and not retroactively change old chunks. Is it still desired?

**Comment by johncsuti** [comment]
Yes even if a full reset is needed. However I like the idea of only updating chunks with an island reset or new island.

**Comment by opticyclic** [comment]
If you aren't using a shop or the magic generator, being able to mine quartz is crucial to create andesite, granite, diorite etc. 

Gravel also generates naturally in the nether. Having gravel generate up near the ceiling would be good too.

Gravel is useful to combine with dirt to make coarse dirt and then be hoe'd back into dirt otherwise you have to do a ton of challenges to get the dirt you need.

**Comment by johncsuti** [comment]
We couldn't do gravel since it has gravity associated with it. Thus it would spawn there and cause massive lag when the player first goes through the portal. Causing most clients/server hosters to stop the server.

**Comment by opticyclic** [comment]
How much control of world generation do you have?
Can you just specify that the gravel has to be on top of netherrack so it doesnt fall when people go through?

**Comment by johncsuti** [comment]
On it @tastybento

**Comment by johncsuti** [comment]
[nether_top_r1.zip](https://github.com/BentoBoxWorld/BSkyBlock/files/4731052/nether_top_r1.zip)
