### ISSUE TITLE
1) Убрать спавн Фантов в аду и эндер мире

### ISSUE THREAD

**Issue by Ecolog22** [BentoBoxWorld/BSkyBlock#228]
##### BentoBox Version (Mandatory)

```
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by BONNe** [comment]
It is a kinda Spigot issue. Not BentoBox.
BentoBox is not managing phantom spawning. Spigot just does not care about light level for some reason, when it summons phantoms in the world.

**Comment by Poslovitch** [comment]
And please post issues in English next time. Russian is not understood by any of us, unless through the use of a machine translation software.
