### ISSUE TITLE
Players cant create island

### ISSUE THREAD

**Issue by Fowleyy** [BentoBoxWorld/BSkyBlock#230]
When player want to create island, It give message like this: there are too many islands in this world: there isnt enough room for yours ti be created. Help because players are angry

**Comment by tastybento** [comment]
Look in your bskyblock config.yml file for these lines:

```
  # Maximum number of islands in the world. Set to -1 or 0 for unlimited.
  # If the number of islands is greater than this number, it will stop players from creating islands.
  max-islands: 0
```

Check that max-islands is zero. if it isn't then set it to 0 and restart the server.

**Comment by Fowleyy** [comment]
Thanks working
