### ISSUE TITLE
How to reduce lagg

### ISSUE THREAD

**Issue by JustBoyke** [BentoBoxWorld/BSkyBlock#233]
#### Describe the bug
I run a 1.14.4 minecraft server with BSkyblock, we have a lot of lagg with the BentoBox plugin. How can i reduce this, the server has 6gb of ram.

#### Steps to reproduce the behavior
Just run the server with the plugin

#### Screenshots and videos (Optional)
Screenshits from /timings: 
![image](https://user-images.githubusercontent.com/44916558/71424619-89abb100-2693-11ea-9235-fdc52892ab87.png)

##### BentoBox Version (Mandatory)
24.12 21:23:57 [Server] Server thread/INFO Running SPIGOT 1.14.4.
24.12 21:23:57 [Server] Server thread/INFO BentoBox version: 1.9.2
24.12 21:23:57 [Server] Server thread/INFO Database: JSON
24.12 21:23:57 [Server] Server thread/INFO Loaded Game Worlds:
24.12 21:23:57 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
24.12 21:23:57 [Server] Server thread/INFO Loaded Addons:
24.12 21:23:57 [Server] Server thread/INFO Biomes 1.6.0.1 (ENABLED)
24.12 21:23:57 [Server] Server thread/INFO BSkyBlock 1.9.0 (ENABLED)
24.12 21:23:57 [Server] Server thread/INFO Challenges 0.8.0 (ENABLED)
24.12 21:23:57 [Server] Server thread/INFO ControlPanel 1.7.0 (ENABLED)
24.12 21:23:57 [Server] Server thread/INFO DimensionalTrees 1.6.0 (ENABLED)
24.12 21:23:57 [Server] Server thread/INFO Warps 1.9.0 (ENABLED)
```
_______
```

**Comment by tastybento** [comment]
This is a recurring task that operates over a number of seconds to delete the island. The timings measurement treats it as one big task but it isn’t. If you think you are actually seeing any lag then you can change the rate of deletion in the BentoBox config.yml.
