### ISSUE TITLE
Wither skeletons/Blazes not spawning in the Nether

### ISSUE THREAD

**Issue by DarkObscurity** [BentoBoxWorld/BSkyBlock#238]
Hello!

I have no idea if this is supposed to be or not, but there are no Wither Skeletons/Blazes spawning in the Nether.

I know that these mobs have different types of spawning requirements, something with the bounding boxes around the Nether castle's, but is there some way to make them spawn naturally?

**Comment by tastybento** [comment]
In the island nether I have not found a way so that why the blueprint contains spawners. Even in the vanilla nether, blazes spawn from a spawner. You might be able to create a nether fortress type layout of a blueprint that might generate wither skeletons but you’ll need to check the spawning rules for how to do that. If you find something that works, let me know!

**Comment by BONNe** [comment]
It is not possible.
Blazes and Wither Skeleton spawning rules are relating to Nether Fortress, that are generated with worlds. Unless you have a plugin that generates mojang structures or imitates that, you will not be able to spawn them naturally.

**Comment by tastybento** [comment]
Ah, so there’s the answer. Thanks @BONNe.

**Comment by DarkObscurity** [comment]
Well they spawn within the nether fortress bounding boxes, so isn't it maybe like possible to generate a bounding box around the nether islands? That way the whole zone should be applicable as spawning area for those... or maybe customize the spawning rules for them? (I don't know exactly what can be achieved when coding a plugin, so i'm only giving suggestions..)

**Comment by DarkObscurity** [comment]
uSkyblock was also able to do it if i recall correctly?

**Comment by DarkObscurity** [comment]
@tastybento or maybe is it an idea to create a sort of custom spawn handler for those mobs? Or maybe try to spawn them through replacing some zombie pigmans? Just so that it looks natural? Or maybe that they only spawn on nether bricks so that players have to create  a floor of nether bricks to get them to spawn?

**Comment by BONNe** [comment]
No, it is not possible to create just BoundinBox of the nether fortress... already tried.
It is possible to spawn manually a nether fortress, but with all blocks and loots.
It is possible to create custom spawning handler... or enhance nether biome, but it should not be done by BentoBox core. Only via addon :)
I was working on it, but currently, I do not have time to finish it.

**Comment by tastybento** [comment]
> @tastybento or maybe is it an idea to create a sort of custom spawn handler for those mobs? Or maybe try to spawn them through replacing some zombie pigmans? Just so that it looks natural? Or maybe that they only spawn on nether bricks so that players have to create a floor of nether bricks to get them to spawn?

This could be done potentially. This is also something that could be done for Ghasts because these too will not spawn either usually due to their rules. I’ll reopen for some examination as an enhancement.

**Comment by DarkObscurity** [comment]
I really hope you guys can manage to do this, this will complete the whole nether experience 😄 
I was looking around in uSkyklock a while ago and if I recall correctly they made some custom handler for the spawning of "special" mobs as well. So I have faith that you guys can create this as well 😄

**Comment by BONNe** [comment]
Yea... uSkyblock did it in "cheaty" way. They replace spawned pigment on nether brick by certain chance to wither skeleton. 
And this is the only way how BentoBox core can do it, without editing NMS.

There is also a possibility to create a custom task, that summons wither-skeletons, but uSkyBlock approach is much nicer.

If BentoBox wants to add a custom rule, then this is the way, however, it should be toggleable.

**Comment by DarkObscurity** [comment]
Well I think the uSkyblock approach sounds good enought, that way it will work on more versions right? And this way you sort of create "custom spawning rules" because players can try to make grinders for, for example wither skeletons because they will only spawn on nether bricks so to say. If this can be done for Blazes and Ghasts aswell, and indeed it should be toggle able and maybe throw in a multiplier so that the spawn rates for each can be adjusted individually? That would be really awesome!

**Comment by Poslovitch** [comment]
I think this should be done as an addon.

**Comment by tastybento** [comment]
This is sounding a lot like Greenhouses without the greenhouse. And I agree, maybe best to be an addon. Called something like NetherMobs.

**Comment by BONNe** [comment]
There is also the ability to use the same approach to spawn shulkers, just with endermans in the end.

**Comment by DarkObscurity** [comment]
You could make it an addon yes, on the other hand, it's a core feature of the Nether world, so on that hand it could be a part of the core game mode. But I leave that up to you guys, I don't really know what takes more time/is more difficult. :) and @BONNe I forgot about those, but that is actually really cool! If it would be possible for them to have like the spawn requirement to be on top of purpur blocks, then they might even be farm able!

**Comment by Bricec6** [comment]
Hello, 
You can have Mobs generated in the nether with MythicMobs for the moment if you wish DarkObscurity

**Comment by tastybento** [comment]
This is covered by the ExtraMobs addon now. https://github.com/BentoBoxWorld/ExtraMobs
