### ISSUE TITLE
Server get big lag when player create island.

### ISSUE THREAD

**Issue by Fowleyy** [BentoBoxWorld/BSkyBlock#242]
Hello, My server has 2xCPU Intel XEON and 10GB of RAM on 1.15.1, why is server get laggy when someone create island? Thx

**Comment by tastybento** [comment]
How do you see this lag? If it's via a timing report, then what you are seeing is a repeating task that builds the island over a number of seconds. This gets reported as a long task, but it is just doing a little bit per task.

**Comment by Fowleyy** [comment]
> How do you see this lag? If it's via a timing report, then what you are seeing is a repeating task that builds the island over a number of seconds. This gets reported as a long task, but it is just doing a little bit per tick.

Server is not responding, cant write in the chat or commands. This is max for 20 seconds.

**Comment by DarkObscurity** [comment]
I just experienced this aswell, like the server is rubberbanding so to say during the creation of the island. It's not long, but everbody lags, players get teleported back, blocks aren't dropped and spawn back when mined. It's noticeable :x

**Comment by tastybento** [comment]
Give me the results of `bbox version` and then some links to your timings (not screenshots) so I can look at them.

**Comment by tastybento** [comment]
Also, you should try lower numbers for the paste speed in BentoBox config.yml:

```
  # Number of blocks to paste per tick when pasting blueprints.
  # Smaller values will help reduce noticeable lag but will make pasting take slightly longer.
  # On the contrary, greater values will make pasting take less time, but this benefit is quickly severely impacted by the
  # resulting amount of chunks that must be loaded to fulfill the process, which often causes the server to hang out.
  paste-speed: 64
```
Set it lower and see if that helps.

**Comment by DarkObscurity** [comment]
https://timings.aikar.co/?id=180e67fe726b4d8a94b0b3fb046e0ee8

Running PAPER 1.15.1.
BentoBox version: 1.11.0-SNAPSHOT-LOCAL
Database: MYSQL
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
BSkyBlock 1.10.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 1.9.0 (ENABLED)
Limits 1.9.0 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
Warps 1.9.0 (ENABLED)

Oh and we're running on a Core I7-8700 with 10 gb of ram assigned to the server. (Dunno if this is usefull info)

**Comment by DarkObscurity** [comment]
Isn't there maybe some way to make use of paper spigot's async chunk load mechanics or something? I'm just guessing here, I recently found out that a chunk generator which used that barely lagged the server when generating while there where players online, so maybe this can come in handy here aswell?

**Comment by tastybento** [comment]
Nope. This is not chunk generation, it is setting blocks one by one. A few are done per tick so it's async. If you are experiencing lag, then the only option is to do fewer blocks per tick.

**Comment by DarkObscurity** [comment]
Hmm okej.. I'll do that then, I upped it a little because players where hanging in the air quite long according to them.

**Comment by tastybento** [comment]
I just looked at your timings and lowering it should be done because too much is being pasted per tick. It's a balance.

**Comment by DarkObscurity** [comment]
I lowered it, we'll see how it goes, thanks for the help and tips! 😄

**Comment by Fowleyy** [comment]
> Give me the results of `bbox version` and then some links to your timings (not screenshots) so I can look at them. Also, let me know if you are using your own blueprints or the default ones.

I have custom bp, and where i can get bbox version

**Comment by Fowleyy** [comment]
> I just looked at your timings and lowering it should be done because too much is being pasted per tick. It's a balance.

I lower it to 8, but It is still laggy.

**Comment by Poslovitch** [comment]
Run /Bbox version,
And paste the output here.

**Comment by Fowleyy** [comment]
This is bbox version: https://pastebin.com/fkANtYTy

**Comment by Fowleyy** [comment]
> Run /Bbox version,
> And paste the output here.
> 
> And we need timings to qualify what makes your server laggy.

timings is where, in the console?

**Comment by DarkObscurity** [comment]
Alright so I lowered the value as you suggested, but it feels like the lagg became even worse when a new player generated an island just now... The whole server freezes when it happened...

**Comment by Fowleyy** [comment]
> Alright so I lowered the value as you suggested, but it feels like the lagg became even worse when a new player generated an island just now... The whole server freezes when it happened...

me too

**Comment by tastybento** [comment]
@Fowleyy To take timings (this is a Spigot/Paper thing), do `timings on` in the console. Then run the server for at least 5 minutes and do things like make a new island, etc. Then do `timings paste` and it'll give you a URL. Paste the URL here so I can look at it.

**Comment by tastybento** [comment]
I wonder if it's the custom Blueprint. It shouldn't be, but if you can email it to tastybento@bentobox.world I will try it and see if I can replicate.

**Comment by Fowleyy** [comment]
> I wonder if it's the custom Blueprint. It shouldn't be, but if you can email it to [tastybento@bentobox.world](mailto:tastybento@bentobox.world) I will try it and see if I can replicate.

I lower paste for 8 and now its OK, If something go bad, I create a new topic

**Comment by DarkObscurity** [comment]
@tastybento even though the ticket is closed, is it ok if I still mail you the blueprints? And if so, do you want all of them? The end, nether and overworld?

**Comment by tastybento** [comment]
Sure. I'll have a look over the weekend.

**Comment by DarkObscurity** [comment]
@tastybento Did you have the time to check the blueprints? :x

**Comment by tastybento** [comment]
I just looked at them. They look fine - not too big. For the Nether one, you have a portal there, but you could still put a [spawn_here] sign just to speed up teleporting if the portal is broken. Other than that, they look good.

**Comment by DarkObscurity** [comment]
@tastybento I increased the block paste speed and now the lagg seems to be less.. hmm
