### ISSUE TITLE
Nether Island Spawners

### ISSUE THREAD

**Issue by ScytheZombie** [BentoBoxWorld/BSkyBlock#243]
Hello, first I would like to say that I am a huge fan of BSkyBlock. I have a question, however. I do not want the spawners to be in the nether when a nether island is created. Is there any way that I could make it so when a nether island is created, there are no spawners there, such as the blaze and skeleton spawners? thanks.

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/BentoBox/wiki/Blueprints

You need to change nether island blueprint.

**Comment by ScytheZombie** [comment]
Ok. Thanks so much.
