### ISSUE TITLE
Lags while generating island

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/BSkyBlock#248]
Hi,
I have problem with generating of new islands. When new island is generating, the server gets lagy. Decreasing protected range helps a lot, but I thing my server is powerful enough to handle protection range 200x200 (4vCOREs on 3GHz, 12GB ram...). Is there any possibility to optimize that? Or something I can change in the settings? Thanks a lot!

Also sorry for my English, I'm not very good at it.

**Comment by tastybento** [comment]
Reduce the paste speed in BentoBox’s config.yml (not BSkyblock). Sry it to 8 or something like that.

**Comment by Kesims** [comment]
That helped a little. Still not perfect, but better than nothing... Thanks!
