### ISSUE TITLE
Super Flat Generating under Islands

### ISSUE THREAD

**Issue by BlackMalakDown** [BentoBoxWorld/BSkyBlock#249]
#### Describe the bug

I am encountering a bug that generates a superflat world under islands. The plugin was working perfectly fine and randomly started to generate this flat land. In server.properties the level name is listed as "bskyblock_world" (consistent with the world name) along with "use-own-generator" set to false. I am running the latest release of PaperMC 1.14.4 (paper-239)
#### Steps to reproduce the behavior

Steps to reproduce is unknown given that the problem occurred shortly after updating BSkyblock AND BentoBox to 1.10.0 
##### BentoBox Version (Mandatory)

```
Running PAPER 1.14.4
Bentobox version: 1.10.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
BSkyBlock 1.10.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Greenhouses 1.0.0 (ENABLED)
Level 1.9.0 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.0 (ENABLED)
```

#### Plugins (Optional)

```
BentoBox, Citizens, CitizensCMD, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, LuckPerms, Vault, WorldEdit, WorldGuard
```

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/BentoBox/wiki/Set-a-BentoBox-world-as-the-server-default-world

Please follow the setup instructions.

**Comment by tastybento** [comment]
And to recover from the super flat that was generated, you can temporarily set the super flat cleaner flag in the world settings `/bsb settings`. It'll generate console spam until the superflat is cleared. If it spams continually, then the issue is that the root cause is not fixed.

**Comment by BlackMalakDown** [comment]
Yup this worked, thank you mate!
