### ISSUE TITLE
Adding resets to a player doesn't work

### ISSUE THREAD

**Issue by Strakye** [BentoBoxWorld/BSkyBlock#250]
#### Describe the bug

When i tried to reset my island after testing blueprints i saw i ran out of resets, so i used the admin comand to add more, it "worked" fine but when i tried to reset it still said i ran out of resets. i had already verified i wrote the name well and even tried restarting the server but nothing made it work.
#### Steps to reproduce the behavior

In my server i have the addons BSkyBlock, Challenges, Chat, Controlpanel, Greenhouses, Level, Likes, Limits and Warps. i just used the 3 resets and not much more. (also before the plugin kind of broke in a moment when it started copying repeated times a bp and didnt recognize commands, that fixed with a reset but i dont know if its somehow related)
#### Expected behavior

Well after adding myself resets it should allow me to reset the island, but it says i have no resets left
#### Screenshots and videos (Optional)

https://prnt.sc/qo3tb1
##### BentoBox Version (Mandatory)
 

```
1.10.0
```

#### Plugins (Optional)

```
Plugins (35): AuthMe, BentoBox, CleanroomGenerator*, ClearLag, CraftEnhance, DailyRewards*, DiscoverWarps, Freeze, HolographicDisplays, LaggRemover, LastLoginAPI, LobbyAPI, LuckPerms, LuckPerms-GUI, MobHealthbars*, Multiverse-Core, Multiverse-Inventories, Multiverse-SignPortals, MyCorePlus*, NPCAuctions, Parties, PluginConstructorAPI, PlugMan, ProtocolLib*, Quests, RankViewer*, TouchscreenHolograms, TPA*, TreeGravity, Ultimate_Economy, Vault, WorldEdit, WorldGuard, WorldSpawns, Zenchantments
```

**Comment by tastybento** [comment]
Thanks for the report. For future reference please put the full output of `/bbox version` in the report.

**Comment by Poslovitch** [comment]
It works "in reverse". Having 1 reset means you resetted your island once. 2, twice, etc... @tastybento could you open an issue on BentoBox so that I don't forget making the messages clearer.

**Comment by Strakye** [comment]
oh so should I put it to a negative number? or 0?

**Comment by Poslovitch** [comment]
Try using the removed command instead.

**Comment by Strakye** [comment]
i see, thanks for the help
