### ISSUE TITLE
Level Place Holder

### ISSUE THREAD

**Issue by skullblaze56** [BentoBoxWorld/BSkyBlock#252]
Trying to set up a level display for QuickBoard. I'm using the %Level_bskyblock_island_level% placeholder and it is not showing up in my game, as shown below. Am I entering it incorrectly? I use Placeholder API.

![help](https://user-images.githubusercontent.com/60041876/72667363-19215700-39e9-11ea-8cbf-07eb283797f6.png)

**Comment by tastybento** [comment]
Yes, that's correct. It looks like the QuickBoard isn't passing the player name to PAPI correctly?

**Comment by skullblaze56** [comment]
Seems I had to replace the _'s with regular - marks after the gamemode

**Comment by tastybento** [comment]
What version are you using? That was the old placeholder but more recently has changed to use underscores.

**Comment by skullblaze56** [comment]
I am on 1.15.1

**Comment by tastybento** [comment]
Please do `bbox version` in the console and share the result. That’ll tell me what versions of addons and plugin you are using in a neat package.

**Comment by skullblaze56** [comment]
Bentobox version is 1.7.0
Level addon 1.6.0

**Comment by tastybento** [comment]
Aha. Those are old versions of the software so that's why you are seeing that. I recommend upgrading. Anyway, it's all answered so I'll close this.
