### ISSUE TITLE
Hopper limit (10)

### ISSUE THREAD

**Issue by xCustomWorld** [BentoBoxWorld/BSkyBlock#255]
Hello,

just a quick question, there is currently a hopper limit of 10 hoppers. I searched in the config and over the internet and as far as I know, it cannot be changed.

**My question:** Is there any way to change/increase the hopper limit?

Thank you, and have a wonderful day/night!

**Comment by BONNe** [comment]
Yes, you need to check limit addon config, as well as there exists permission that increases hopper limit to targeted player/group.
Check limit addon.

**Comment by xCustomWorld** [comment]
Thank you very much!
