### ISSUE TITLE
Creating a new island

### ISSUE THREAD

**Issue by cantercrow** [BentoBoxWorld/BSkyBlock#257]
#### Describe the bug

When I enter /island I get the message looking for a place to create island and then the message could not find a safe place to teleport you to on the island.

#### Steps to reproduce the behavior

When I enter /island I get the message looking for a place to create island and then the message could not find a safe place to teleport you to on the island.
#### Expected behavior

Teleport to island

### Environment
CraftBukit 1.15.2
##### BentoBox Version (Mandatory)

```
Spigot 1.15.2
BentoBox 1.11.0
Database JSON
Loaded Game Worlds 
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons
Biomes 1.6.0.1 (enabled)
BSkyBlock 1.11.0 (enabled)
Challenges 0.8.0 (enabled)
ControlPanel 1.7.0 (enabled)
Dimentional Threes 1.6.0 (enabled)
Level 1.9.3 (error)
Limits 1.9.0 (error)
Warps 1.9.0 (enabled)


```

#### Plugins (Optional)

```
WorldEdit
PlaceHolderAPI
Valut
WorldGuard
CoreProtect
Essentials
BentoBox
EssentialsProtect
EssentialsChat
EssentialsGeoIP
EssentialsAntiBuild
EssentialsSpawn
MultiVerse-Core
EssentialsXMPP
MultiVerse-Invertotries
MultiVerse-SignPortals
MultiVerse-Portals
MultiVerse-NetherPortals
```

**Comment by tastybento** [comment]
1. Is this a brand new world, or a conversion?
2. Did you change any of the blueprints (starter island), or is this the regular one.
3. Did this just suddenly start happening, or is this the first time you are trying this?

**Comment by cantercrow** [comment]
Hi,

 

1.	My main world is modified into a lobby
2.	I have not changed anything
3.	I have only just installed and never had working.

 

Regards

Julian

**Comment by tastybento** [comment]
If you set the BSkyBlock world as your main world, then follow these instructions:
https://github.com/BentoBoxWorld/BentoBox/wiki/Set-a-BentoBox-world-as-the-server-default-world. 
Did you set it as your main world?

**Comment by cantercrow** [comment]
Hi,

 

No I did not set to my main world, I want players to enter a lobby world first and then be able to teleport to a skyworld, is this not possible?

 

Regards

**Comment by tastybento** [comment]
Yes, this is very possible. If you haven't set the BSkyBlock world as your default world then I'm a bit surprised you are seeing that issue. Can you start the server, try to make the island, stop the server, and then copy and paste the log file from the server into this ticket? Just drag and drop. I see from your `bbox version` that two addons are in error, which shouldn't happen either, so I'd like to see the full console log to find out what's happening.

**Comment by cantercrow** [comment]
Good Day,

 

I made a few changes to the server so to get base to a base system with BSkyBlock so I can send the error log I created a new server with CraftBuckit and BSkyBlock and this time it worked without any errors.

 

I am a bit confused as to why it worked this time as I used the same procedure to install, anyway thanks for the support and I am available if you need any testing, I am a Senior IT Engineer for a company and been in IT for over 20 years, I have a high spec VMWare server for testing with 12 CPU’s and 160GB ram running AMP https://cubecoders.com/AMP

 

One question which I can find the answer to, once a player in on an island is there a command to return to the default world?

 

Below are the plugins in the plugins folder running on Craft Bukit 1.15.2

 

02/02/2020  21:41    <DIR>          BentoBox

02/02/2020  21:40         1,788,027 bentobox-1.11.0.jar

01/02/2020  21:50           360,619 CoreProtect-2.18.0.jar

01/02/2020  13:23         1,467,738 EssentialsX-2.17.1.0.jar

01/02/2020  13:23            18,104 EssentialsXAntiBuild-2.17.1.0.jar

01/02/2020  13:23            12,763 EssentialsXChat-2.17.1.0.jar

01/02/2020  13:23         1,737,804 EssentialsXGeoIP-2.17.1.0.jar

01/02/2020  13:23            20,000 EssentialsXProtect-2.17.1.0.jar

01/02/2020  13:23            15,449 EssentialsXSpawn-2.17.1.0.jar

01/02/2020  13:23           331,915 EssentialsXXMPP-2.17.1.0.jar

02/02/2020  21:07           463,673 Multiverse-Core-4.1.0.jar

01/02/2020  13:14           296,178 Multiverse-Inventories-3.0.0-SNAPSHOT.jar

01/02/2020  23:42            44,458 Multiverse-NetherPortals-4.1.0.jar

31/01/2020  16:53           107,761 Multiverse-Portals-4.0.0.jar

01/02/2020  23:44            39,912 Multiverse-SignPortals-4.1.0.jar

01/02/2020  23:24           344,057 PlaceholderAPI-2.10.4.jar

02/02/2020  21:18         1,418,996 PlugMan.jar

02/02/2020  17:34           273,727 Vault.jar

 

Regards

**Comment by tastybento** [comment]
It’s good to have you join the world of BentoBox!

> One question which I can find the answer to, once a player in on an island is there a command to return to the default world?

No, there is not. Other plugins can cover that for you, e.g. Essentials Spawn. If you do have players jumping worlds, make sure you use an inventory switching plugin or addon to keep inventory, health and food separate.
