### ISSUE TITLE
Port the  "usecontrolpanel config" of askyblock to bentobox

### ISSUE THREAD

**Issue by xion87** [BentoBoxWorld/BSkyBlock#259]
I would like to see this setting again, was pretty usefull:

    Use the control panel as the default display for /island
    /island will always create an island if one does not exist
    If the control panel is not used, then /island will teleport the player home
    Players can change this setting using /island cp on or /island cp off
    usecontrolpanel: true

Doing /is, will create the island and doing it again will open the panel, and it allow to use /is subcommands too,
Many players of my bskblock are misisng this, i tried to use some workround, but is not better.

**Comment by tastybento** [comment]
This could be done in BSkyBlock (or other game modes) because that's where the `/island` command exists. Let me investigate.

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/BentoBox/issues/498#issuecomment-465224112
This should be an implementation, as not all want to open control panel.
