### ISSUE TITLE
Nether sign should have a dash next to tastybento to show its from him.

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/BSkyBlock#270]
#### Is your feature request related to a problem?

No, the nether sign currently says "Welcome to the nether tastybento." This can confuse some users easily. There should be a change made to show "-tastybento" or just put the player name there instead.

#### Describe the solution you'd like us to implement.

-tastybento
(Player name)

#### Describe alternatives you've considered.

None

### Additional context

This would be changed from the default. I know I can change them per server.

**Comment by johncsuti** [comment]
I don't understand how this is a bug?

**Comment by tastybento** [comment]
The nether island sign should just be the same as the player's overworld sign. I think your nether island blueprint might be an old one that mistakenly was a copy of my own island and didn't have the signs set up like this:
![Screen Shot 2020-03-04 at 2 46 17 PM](https://user-images.githubusercontent.com/4407265/75930308-2ffbfb80-5e27-11ea-8214-6ce66129afdc.png)
To check, you can load your nether island blueprint and paste it somewhere and have a look whether there are signs. If not, I recommend you delete the nether island and replace it with [the latest version of the schematic](https://github.com/BentoBoxWorld/BSkyBlock/blob/develop/src/main/resources/blueprints/nether-island.blu).

**Comment by johncsuti** [comment]
Looking at the nether the sign doesn't show [start]. I have replaced it with the new versions.

**Comment by johncsuti** [comment]
Can be closed once you see this.
