### ISSUE TITLE
A machine for grief others islands! urgent bug

### ISSUE THREAD

**Issue by zannapzg** [BentoBoxWorld/BSkyBlock#272]
Hi, I'm a staffer of the server mc.zephiral.net
We use your plugin BSkyBlock and 2/3 addons :)

Today a player reported to me that there is an authomatic machine with slime block, pistons and observer block that can grief others islands

All you have to do is:
1. create the machine
2. start it on your island and it will go on forever until it reaches a block of obsidian in front of it

![2020-03-06_06 01 23](https://user-images.githubusercontent.com/61860483/76054596-7eb5ac80-5f71-11ea-9e3c-5906431ac1c5.png)

**Comment by BONNe** [comment]
You can disable piston pushing outside the island in settings.

**Comment by tastybento** [comment]
Do `/bsb settings` and choose BSkyBlock settings and activate Piston Push Protection:
![Screen Shot 2020-03-06 at 6 07 48 PM](https://user-images.githubusercontent.com/4407265/76134738-7b540c80-5fd5-11ea-88e8-4bb485664d8e.png)
