### ISSUE TITLE
Feature request /is settings mob spawning 

### ISSUE THREAD

**Issue by Beluaa** [BentoBoxWorld/BSkyBlock#273]
#### Is your feature request related to a problem?

The thing is, whenever I'm building some high structures or buildings, phantoms spawn because I haven't slept for 3 days straight. There are also other mobs spawning during night but that's easy solvable with light sources. When I'm building big buildings it's annoying to go to a bed, sleep and get all the way back up there. 
#### Describe the solution you'd like us to implement.

I think it would be a nice feature to change the "mob spawning" feature in /is settings to 2 separate settings where we can turn off natural mob spawning and mob spawning by spawners. Because I can obviously turn of mob spawning but then the spawners won't work as well. 
#### Describe alternatives you've considered.

Turning off the general mob spawning is an option, but as I said, then the mob spawners for farms wouldn't work either.

**Comment by tastybento** [comment]
Is this a request for a cheat mode for players or for you as an admin? If you want to temporarily (or permanently) prevent Phantoms or any other mobs from spawning in the world, you can do `/bsb settings` and then click on the iron boots and deselect the mob type you want to prevent.

**Comment by Beluaa** [comment]
It's not really a cheat mode I guess, it's just a request to make 2 separate /is settings for skyblock players where they can turn of mob spawning by spawners and mob spawning by natural generation?

**Comment by tastybento** [comment]
I'm going to politely say no to this one because we already have two flags for spawning - animal spawning and mob spawning. If you are giving players the ability to turn these on and off then it's actually super simple for them to do that when they need to.
