### ISSUE TITLE
Skip new island schem

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/BSkyBlock#275]
Hey, is there some way to skip new island schem selection after creating new island via /bsb register <player>? There is already physical island, but it "is not registered in BSkyBlock" so players are playing normally on island, but they cant use /is and /is sethome, because plugin wants them to select schem... Thanks for help.

**Comment by tastybento** [comment]
Try to unregister them and then register them again to the island.
If you register a totally unknown island to a player then it assumes that you are actually reserving the spot for a player to start at.

**Comment by Kesims** [comment]
Well... than I have reserved a slot for island - but there already is an island. So there is no way to skip selecting new schematic? Something that i change in some file or something like that?

**Comment by tastybento** [comment]
No, there's no config for this. If you reserve a spot, then the player will be asked to pick an island to paste it there. If as an admin you pasted some blocks there manually and you just want them to continue, then unregister the player and then register them again, that should clear it. Does it?

Is this just a one-off, or something you plan on doing a lot of?
