### ISSUE TITLE
Hostible mobs hurting island visitors

### ISSUE THREAD

**Issue by N0tMyFaultOG** [BentoBoxWorld/BSkyBlock#278]
#### Is your feature request related to a problem?

I'm not sure if this is already a thing but I was looking for a flag to allow hostile mobs to hurt island visitors.

#### Describe the solution you'd like us to implement.

See above

#### Describe alternatives you've considered.

See above

### Additional context

If this is already a thing and I overlooked it, just nevermind the issue.

**Comment by tastybento** [comment]
Yes. Change the settings of "invincible visitors" in admin settings. It's a diamond chest plate icon. Disable the protections you wish. I have  Click in there and you can choose what kind of damage that visitors should take. This is the kind of pattern I have:

<img width="463" alt="Screen Shot 2020-03-15 at 1 52 20 PM" src="https://user-images.githubusercontent.com/4407265/76710380-50984100-66c4-11ea-993b-2394f9707f6f.png">

You'll need to play with the different settings to determine what's best for your server.

**Comment by N0tMyFaultOG** [comment]
Nice, can I somehow add it to the default `/is settings` gui? I want the player to decide whether to use it or now.

**Comment by tastybento** [comment]
Sorry, no. It's a worldwide setting, not an island setting.

**Comment by N0tMyFaultOG** [comment]
Hm unfortunately, ty tho.
