### ISSUE TITLE
protection

### ISSUE THREAD

**Issue by leoncp9** [BentoBoxWorld/BSkyBlock#283]
Hi this is not a bug, orry for bad section, i have a problem
when i trust a plaeyr to my island, how can brake and place blocks on my  island? the commandsfor remove the protection is /bsbadmin settings ?
and than?

**Comment by tastybento** [comment]
The owner of the island should use `/island settings` and then change the settings for break and place blocks to allow trusted to do it.

**Comment by leoncp9** [comment]
ok thank
