### ISSUE TITLE
/is challenges

### ISSUE THREAD

**Issue by leoncp9** [BentoBoxWorld/BSkyBlock#284]
Hello this is not a features request, this is how can i find a wiki where teach me how setup the challenges addon for my bskyblock pluign :( How can i add challenges? what is the directory and file who i need to setup? becaues i cant' find how setp it! 
In /plugins/bentox/addons/challenges i find only config.yml file .... so what i need to do for add challenges?

**Comment by tastybento** [comment]
https://github.com/BentoBoxWorld/Challenges

We're developing a documentation site where it's all in one place, but for now you have to check out the individual addons. https://github.com/BentoBoxWorld/

**Comment by leoncp9** [comment]
ok thank you :D
