### ISSUE TITLE
BSkyBlock - On island creation player suffocation

### ISSUE THREAD

**Issue by matthewBeckwith** [BentoBoxWorld/BSkyBlock#287]
I am currently working on a Skyblock server, everything working great, except when I'm creating an Island now when the player teleports to the island, dies due to suffocation, and gets stuck in a loop of constantly suffocating and dying.  Player appears to be on top of the island, and at one point i was able to fly away from the tree for a moment, and appears player is suffocating in air blocks but the game thinks player is stuck in something.  tested both basic island and double island with same results.

**Comment by matthewBeckwith** [comment]
Fixed.  Was an issue with a multiverse setting.

**Comment by ZiolaBleu** [comment]
How did you fix this?

**Comment by matthewBeckwith** [comment]
I made the preset world size too small trying to save memory, this made the island areas able to spawn in I suppose "dead space" because I would die over and over.  So I just reverted the size in the config and all was well.  I hope this helps, sorry for the late reply, I haven't checked in a while.
