### ISSUE TITLE
Spectator on death

### ISSUE THREAD

**Issue by Powiss** [BentoBoxWorld/BSkyBlock#289]
Hello.
I downloaded BSkyBlock plugin to my server.
It is very great plugin but when player on skyblock die or fall the game gives him spectator mode.
How to fix that ?
Thank you :)

**Comment by Poslovitch** [comment]
`/bbox v`, please

**Comment by Powiss** [comment]
It's in Czech language. Sorry about that :/
![bboxv](https://user-images.githubusercontent.com/62929649/78000095-05249a80-7334-11ea-9c85-5ff2bb11f10a.png)

**Comment by Poslovitch** [comment]
BentoBox no longer puts the player in SPECTATOR gamemode. Could you make sure this is not another plugin that causes that?

**Comment by Powiss** [comment]
On other worlds player after death have survival so i don't think, that is causing another plugin :/
Here is my list of plugins
![plugins](https://user-images.githubusercontent.com/62929649/78012379-280b7a80-7345-11ea-942e-e4da7307a216.png)

**Comment by Poslovitch** [comment]
Yet, on the other worlds, players are most likely not falling into the void. I'll run an organisation-wide search to see if we have code that could still put players in SPECTATOR.

**Comment by Poslovitch** [comment]
As you can see, the search returns no result that changes the gamemode of a player to SPECTATOR. They're just checks.
I've got a question though : what's the `default-game-mode` option set to in your BSkyBlock config?

**Comment by Powiss** [comment]
My default game mode is survival:
 default-game-mode: SURVIVAL

But players get spectator mode when they fall into lava or get killed by mob

**Comment by Powiss** [comment]
Oh. Now player died on survival and he get spectator mode.
It is not caused by SkyBlock plugin :/
Sorry about that and thanks for your time :)
