### ISSUE TITLE
Empty Bee Nest when spawning on tree. No bees spawn naturally either.

### ISSUE THREAD

**Issue by PEZ18** [BentoBoxWorld/BSkyBlock#290]
#### Describe the bug

Bees do not spawn naturally nor do they come out of bee nest. 

#### Steps to reproduce the behavior

Use flower and sapling to generate tree with bee nest attached. Also used /give command to test bee nest but neither one has bees inside. 
#### Expected behavior

2-3 bees should appear after a few seconds of bee nest generation or placement of block.
#### Screenshots and videos (Optional)

NA
### Environment
Spigot 1.15.2
##### BentoBox Version (Mandatory)

```
Bentobox 1.11.1
```

#### Plugins (Optional)

```
Bentobox 1.11.1
EssentialsX 2.17.2.0
LuckPerms 5.0.72
Essentials Warp GUI
Vault
```
 
### Additional context (Optional)

I dont know if this should be posted on Bskyblock or on the Extra Mobs Addon side. Please let me know what I need to do.

I have tested this on fresh server  using only bentobox plugin and I have also tested this with Extra Mobs Addon but neither were successful. I also tried editing the config.yml to increase bee spawn instead of chicken but that did not work either... Maybe I am editing the config file wrong? What am I missing here?

Please test to see if you get the same results.

**Comment by BONNe** [comment]
https://minecraft.gamepedia.com/Beehive#Saplings
BentoBox and ExtraMobs do nothing with bees after it is implemented in vanilla minecraft

**Comment by PEZ18** [comment]
I spawned in some bees using a bee spawner and noticed something odd. I am guessing it could cause lag if every island on a server had bees so It might be a good thing the bees dont naturally spawn... They all fly down to the bottom of the island world and just sit there in the void. I dont know how long they sit there or if they despawn but they dont fall out of the world like other mobs. So far they have been there for about 30 min.
![2020-04-04_00 13 46](https://user-images.githubusercontent.com/45371402/78421007-37224f00-7609-11ea-9e9e-b9e468f2ab8b.png)

![2020-04-03_23 58 44](https://user-images.githubusercontent.com/45371402/78420825-a26b2180-7607-11ea-8dee-eb6c20e2c00f.png)

**Comment by BONNe** [comment]
And yet... it is not a BentoBox bug... it is default vanilla behavior.

**Comment by tastybento** [comment]
I've see the same with Guardians on AcidIsland. The mob's AI is not used to having no ground. I'll close this because there's nothing we can do, but yeah, it's sucky.

**Comment by PEZ18** [comment]
> And yet... it is not a BentoBox bug... it is default vanilla behavior.

BONNe, the bees flying down to the void is default vanilla behavior but the no bee spawning out of a bee nest is not normal. each bee nest should contain 2-3 bees from what I found which is why I opened a ticket.

**Comment by tastybento** [comment]
This issue was at one time a Spigot Bug (https://hub.spigotmc.org/jira/browse/SPIGOT-5537). It looks like the solution was to manually add bees to the hive. I'm not sure when this code is called, but maybe it doesn't get called all the time. This needs more investigation.
