### ISSUE TITLE
Island Not Found

### ISSUE THREAD

**Issue by DPanda1100** [BentoBoxWorld/BSkyBlock#291]
Hi, I recently upgraded BSkyBlock from 1.11 to 1.12 which was working fine. I edited the mob spawning config once and soon after a server restart you can no longer use the /island or /is command. Every time it is entered an error occurs stating "Finding a spot for your island...", "An internal error occurred while attempting to perform this command". On top of this I cannot get mobs to spawn throughout players islands with BSkyBlock 1.12. 
Any help would be much appreciated.
Thanks again.

**Comment by tastybento** [comment]
It sounds like a lot is broken. Can you fill out the bug report form? I need you to do `/bbox version` and paste the result and also I need to see your console log from boot up. There will be errors in it. You can zip it and drag and drop into the reply here or use pastebin.com.
