### ISSUE TITLE
Some players cannot perform /is (does nothing)

### ISSUE THREAD

**Issue by plagoutte** [BentoBoxWorld/BSkyBlock#300]
#### Describe the bug

A player on my server cannot perform /is (it does nothing). All worked perfectly up to now. No error message is printed to his chat or in the console. A day after he reported it to me, it worked again.

#### Steps to reproduce the behavior

It only happened for a single player. There is no configuration changes between when it was working and now.

#### Expected behavior

The player should be teleported to his island.

##### BentoBox Version (Mandatory)

```
> bbox version
[21:37:48 INFO]: Running PAPER 1.14.4.
[21:37:48 INFO]: BentoBox version: 1.11.1
[21:37:48 INFO]: Database: MYSQL
[21:37:48 INFO]: Loaded Game Worlds:
[21:37:48 INFO]: BSkyBlock_world (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
[21:37:48 INFO]: Loaded Addons:
[21:37:48 INFO]: Biomes 1.7.0 (ENABLED)
[21:37:48 INFO]: BSkyBlock 1.12.0 (ENABLED)
[21:37:48 INFO]: Challenges 0.8.0 (ENABLED)
[21:37:48 INFO]: Chat 1.0.4 (ENABLED)
[21:37:48 INFO]: Level 1.9.3 (ENABLED)
[21:37:48 INFO]: Warps 1.9.0 (ENABLED)
>
```

#### Plugins (Optional)

No plugin changes.
 
### Additional context (Optional)

The player is member of an island. 
I tried to kick him from his island. When he did /is again, it does nothing (he should have the GUI to create a new island).

I am available for any further information needed.

**Comment by lolsteamroller** [comment]
Can or can not be related, but from your version I see there is possible mismatch with the versions. 
You have to remember that BentoBox is the core, while Skyblock is the addon.

You are running BentoBox version: 1.11.1, with bigger Skyblock version. That in itself can not be compatible in some ways. Preferably, upgrade your BentoBox version, or downgrade your Skyblock one.

I'm seeing these releases pushed out side by side, so someone correct me if I'm wrong, but I think that itself can be source of the bug.

**Comment by tastybento** [comment]
Hey - the additional context is pretty crucial here:
>The player is member of an island.
I tried to kick him from his island. When he did /is again, it does nothing (he should have the GUI to create a new island).

Is this the the way to get the error? If so give me more info on how you did the kicking:

1. Was it successful? You write "I tried" so I'm not sure.
2. Was he offline when you did the kicking?
3. Was he just a member or the owner of the island?
4. How big was the team, if you remember?

**Comment by plagoutte** [comment]
@lolsteamroller It may be related, you are right. I cannot upgrade BentoBox now, as all of my plugins are not compatible with MC 1.15, but it is planned. 

@tastybento Thank you for your reply. I know how difficult it is to fix a bug we cannot replicate...
1. I was able to kick the player (and re-add him to the island later), but it didn't solved the problem.
2. He was online
3. He was just a member (not the owner)
4. 4 players : 1 owner and 3 members

**Comment by tastybento** [comment]
Do you have permissions for the blueprints. I wonder if he didn't have perms for any blueprints so nothing could be made...

**Comment by plagoutte** [comment]
Hello, 

Yes they have permissions. Moreover, all was working fine for other players.

**Comment by tastybento** [comment]
If it happens again, let me know because I can't do much about this right now without more info.
