### ISSUE TITLE
Control Panel open on /is 

### ISSUE THREAD

**Issue by MipperRagoo** [BentoBoxWorld/BSkyBlock#303]
### Description

When using the command /is allow an option for the control panel to open instead of teleporting to the island.

#### Is your feature request related to a problem?

     I can not find a way to make the /is command open /is cp no matter what I try. I've used other plugins like mycommand and set a alias for the /is command but it creates a command loop and spams the console and crashes the server. I've also looked though the configs to see if there is a way to set that up but there is not.

#### Describe the solution you'd like us to implement.

     Add a config option to allow /is to just open the control panel instead of teleporting to the island.

**Comment by tastybento** [comment]
This is coming in the next version of BSkyBlock.  It's #259

**Comment by MipperRagoo** [comment]
Oh cool I didn't realize that. Thank you for the info.
