### ISSUE TITLE
Players cannot use any bskyblock related commands.

### ISSUE THREAD

**Issue by skullblaze566** [BentoBoxWorld/BSkyBlock#304]
#### Describe the bug

When players log on to my server, new or old, and type /is or /is [subcommand] they are met with a chat error 50% of the time which goes as follows:

The chat claims to take us to the island, then confirms that we are that island, but we are never teleported. After that, the player becomes invisible to everyone in the game and cannot type any chat message or command unless they re-log on to the server.

#### Steps to reproduce the behavior

A player logs on to the server and types the command /is, and 50% of the time experiences the issue. (not a single error in our console). After that, they try to type a command or chat and it tells the person they cannot send a chat.

#### Expected behavior

It should teleport players to their islands without a problem at all.
#### Screenshots and videos (Optional)

https://prnt.sc/s2sfj3
https://image.prntscr.com/image/YTC9iWe7RpyWztvjvVFB8g.png
##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.12.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, [nether_color]NEther, [end_color]End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
Challenges 0.9.0-SNAPSHOT-b399 (ENABLED)
Chat 1.0.4 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
Limits 1.9.2 (ENABLED)
Warps 1.9.0 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (27): BentoBox, Citizens, DeluxeChat, Essentials, F*, FastAsyncWorldEdit, GUIShop, HolographicDisplays, HyperDrive, InfiniteScoreboard, LiteBans, LuckPerms, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, ProtocolSupport, RedLib*, Shopkeepers, TAB, UltimateTimber, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard, XPBoost
```
 
### Additional context (Optional)

Out of the 27 plugins I posted above I have already ruled out  PlaceholderAPI, ProtocolLib and ProtcolSupport, as well as RedLib.

**Comment by skullblaze566** [comment]
Will do so, I will let you know should the problem continue with only Bbox remaining

**Comment by Poslovitch** [comment]
I was told on Discord the following:

> FAWE for 1.15 ended up being the cause of my issue with your bskyblock commands
> you can close my thread, i forgot my github password

Closing this issue.
