### ISSUE TITLE
#609 and after have bug

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/BSkyBlock#312]
#### Describe the bug
The server is also not execute `is` after a while. And it gives these errors.

![image](https://user-images.githubusercontent.com/47111280/80712108-1fe85b80-8afa-11ea-975d-0693ccbad4c4.png)

##### BentoBox Version (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/80712157-35f61c00-8afa-11ea-8fb0-4e447b5789d9.png)

**Comment by tastybento** [comment]
#609 added the ability to use the Control Panel by default when doing /is. Are you using this feature?

**Comment by OverBrave** [comment]
No 
But after these errors, I started using it. There is no problem yet.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/80842119-76908b00-8c09-11ea-8984-b1ee0ed5581a.png)
![image](https://user-images.githubusercontent.com/47111280/80842130-827c4d00-8c09-11ea-8b64-3fab146ad87a.png)

**Comment by tastybento** [comment]
What is happening on-screen when you get this error?

Also, could you copy and paste the console instead of using screenshots? It's a lot easier for me to scan it.

**Comment by OverBrave** [comment]
Of course, I will do so from now on.

When I type the / is command, I get the error "An internal error".

**Comment by tastybento** [comment]
Does it happen all the time, or just sometimes? Please try the latest Level addon snapshot release. I made some changes that might help.

**Comment by OverBrave** [comment]
I made the update. This problem was appearing at random times. And when this happened, I was having the same trouble for all new players.

**Comment by OverBrave** [comment]
The problem has now happened again, but this time there was no error on the console.

**Comment by tastybento** [comment]
Just to clarify, the problem is that you type `/is` and nothing happens?
If you restart the server, then it works again?

**Comment by OverBrave** [comment]
Yes

**Comment by tastybento** [comment]
Please try latest BentoBox 1.14.0-SNAPSHOT when it finishes building.

**Comment by OverBrave** [comment]
The same thing happened again.

**Comment by tastybento** [comment]
No errors? If you do `/is help` do you see anything?
What version of Paper are you using?
Does it work for a while and then stop?

**Comment by OverBrave** [comment]
All yes. Paper 237

**Comment by tastybento** [comment]
Sorry, if you do `/is help` you **do** see help?

**Comment by OverBrave** [comment]
eh no

**Comment by tastybento** [comment]
I'm stuck. Do other plugins run okay? Can you do a timings report when it fails? Maybe there's some kind of infinite loop going on.

**Comment by OverBrave** [comment]
This happens only in some players. Not all:
https://timings.aikar.co/?id=7a221970be6c4a5992b664fcc995b356

**Comment by tastybento** [comment]
I see you are using PlugMan. Another user reported a similar bug to you and I think that PlugMan is likely not compatible with BentoBox. PlugMan uses class loaders and so does BentoBox. If you do any operations with PlugMan, I expect it will cause problems. Can you try your server without PlugMan?

**Comment by OverBrave** [comment]
I can try but I didn't use Bentobox with Plugman. Why would this be a problem?

**Comment by tastybento** [comment]
PlugMan is listed in your timings report, so it appears to be running on the server. PlugMan will load and unload plugins and it does so by taking control of the classloader to do that. 
![Screen Shot 2020-05-05 at 3 59 33 PM](https://user-images.githubusercontent.com/4407265/81124115-7afac380-8ee9-11ea-84bb-87965641e075.png)
BentoBox loads and unloads addons in a similar way. So it looks like there is an incompatibility between the two. It'd be good to try and rule it out.

**Comment by OverBrave** [comment]
Okay, I just uninstalled it and restarted the server. If the problem occurs again, I will be informed.

**Comment by tastybento** [comment]
There is another bug that had an effect on /is not working. It was caused by players logging out when mounted, e.g., on a horse. When they logged in again /is and other BentoBox commands would not work. That may also be related to this. If so, try the latest SNAPSHOT build because it has a fix.

**Comment by OverBrave** [comment]
I think problem has been fixed. It also works with the plugman plugin installed.
I think player clearing cache feature its working.
Thanks, 
If this problem again happened, i will reopened this issue
