### ISSUE TITLE
on-join and on-leave commands

### ISSUE THREAD

**Issue by Ratibus11** [BentoBoxWorld/BSkyBlock#315]
Sorry if I make mistakes, I'm French 😅
#### Describe the bug

I use a LuckPerms track du symbolize the player's Skyblock level. So I create two commands in the BSkyBlock config :
on-join:
- lp user [player] parent settrack skyblock novice

on-leave:
- lp user [player] parent cleartrack skyblock

I test 3 cases :
- When I use the /is reset, the on-leave, then on-join command is executed, no problem,
- When I use the /bsbadmin delete [my name], the on-leave command is executed, perfect,
- After that, I use the /is to create a new island, but the on-join isn't executed. That's problematic. That is normal ? (Even I reset the database, my island is created but no command is executed)

#### Steps to reproduce the behavior

- Type a on-join and on-leave command. Type the /bsbadmin delete [name] to quit our own island then the /is command.

#### Expected behavior

I think the on-join commands should be executed.

#### Screenshots and videos (Optional)

<img width="354" alt="Capture d’écran 2020-05-02 à 14 06 00" src="https://user-images.githubusercontent.com/49524093/80863646-0f60ee00-8c7e-11ea-8588-6fd5ff9dd197.png">
<img width="627" alt="Capture d’écran 2020-05-02 à 14 05 17" src="https://user-images.githubusercontent.com/49524093/80863625-f5271000-8c7d-11ea-9568-74ceda959b5a.png">

##### BentoBox Version (Mandatory)

```
En cours d'exécution PAPER 1.15.2.
BentoBox version: 1.12.0
Database: JSON
Mondes de jeu chargés :
skyblock (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
Addons chargés :
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.12.0 (ENABLED)
Challenges 0.8.1 (ENABLED)
Chat 1.0.5 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (18): ArmorStandTools, AsyncWorldEdit, BentoBox, BungeeTabListPlus, CoreProtect, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, HolographicDisplays, LuckPerms, Multiverse-Core, PremiumVanish, ProtocolLib, TheNewEconomy, Vault, WorldEdit
```

**Comment by tastybento** [comment]
I could not find a bug, but maybe the command you are running doesn't do anything or has an error.

I tested with reset and new islands and the join commands are run.

```
[16:53:27 INFO]: tastybento issued server command: /ai reset
[16:53:28 INFO]: Unknown command. Type "/help" for help.
[16:53:28 ERROR]: [BentoBox] Could not execute leave command as console: lp user tastybento parent cleartrack skyblock
[16:53:30 INFO]: Unknown command. Type "/help" for help.
[16:53:30 ERROR]: [BentoBox] Could not execute join command as console: lp user tastybento parent settrack skyblock novice
[16:53:53 INFO]: tastybento issued server command: /acid delete tastybento
[16:53:54 INFO]: tastybento issued server command: /acid delete tastybento
[16:53:55 INFO]: Unknown command. Type "/help" for help.
[16:53:56 INFO]: tastybento issued server command: /ai
[16:53:59 INFO]: Unknown command. Type "/help" for help.
[16:53:59 ERROR]: [BentoBox] Could not execute join command as console: lp user tastybento parent settrack skyblock novice
```

I did add more error checking for failed commands (you can see I don't have LuckPerms). Try the latest build and see if you can find out why your command isn't running.

**Comment by Ratibus11** [comment]
I found the solution ! May be it's an unexpected behaviors.

I change only the ```teleport-player-to-island-when-created:``` setting.

When I turn it to ```true```, I'm teleported when I create my island and the on-join commands are executed.
But when I turn it to ```false```, the on-join commands are not executed.

So I solve my self problem, but may be it's a bug.

**Comment by tastybento** [comment]
No, it's not a bug, but we should document that better. If you are not teleported to your island then commands are **not** run because you may be in another world. As a result, these two options are incompatible.

**Comment by Poslovitch** [comment]
Weren't we storing the "pending kicks" in BentoBox? Then we could store the "pending joins", and once the player teleports to its island for the first time, we do the usual on-join stuff.
