### ISSUE TITLE
I can't create an island

### ISSUE THREAD

**Issue by Azipos** [BentoBoxWorld/BSkyBlock#316]
#### Describe the bug

I can't create an island. I can open creation GUI with /is command, where I should choose island type, but when I click on one of the three choices, I grab it instead of execute creation.

#### Steps to reproduce the behavior

Really don't know. It happened right after clean installation. And then again after another installation.

#### Expected behavior

Just to create an island :).

##### BentoBox Version (Mandatory)

```
latest build - 1.11.3
```

#### Plugins (Optional)

```
LuckPerms, WorldEdit, SkinsRestorer, PerWorldPlugins, RandomTeleport, MultiVIP, SetLobby, Vault, WorldGuard, BentoBox, Essentials, EssentialsChat, PlotSquared, EssentialsSpawn, Multiverse-Core, Multiverse-Inventories, AuthMe, Multiverse-NetherPortals
```

**Comment by tastybento** [comment]
If you can grab items out of the GUI then it is usually due to another plugin blocking the inventory cancellation (cancelling the event prevents items being taken). Your plugins look okay, but there are some I don't recognize. Try removing them one by one until you can't take from the inventory. Alternatively, install BentoBox/BSkyBlock on a test machine and add plugins until you find you can take items. Let me know which plugin it is if it happens.

**Comment by Azipos** [comment]
Ok, I will try. Have you tried some of them, so I don't have to try them all :D.

**Comment by tastybento** [comment]
These should be safe:

LuckPerms, WorldEdit, Vault, WorldGuard, BentoBox, Essentials, EssentialsChat, EssentialsSpawn, Multiverse-Core, Multiverse-NetherPortals

These might be safe:
PlotSquared, Multiverse-Inventories

I don't know about these:
AuthMe, SkinsRestorer, PerWorldPlugins, RandomTeleport, MultiVIP, SetLobby,

**Comment by Azipos** [comment]
I found something. There is collision between /cp command of BentoBox and /cp command for change password of AuthMe.

**Comment by Azipos** [comment]
But if I'm right, main problem is caused by plugin PerWorldPlugin.

**Comment by tastybento** [comment]
So, if you don't use PerWorldPlugin then it works? I would get PerWorldPlugin is not compatible with BentoBox anyway because BentoBox runs across many different worlds.

**Comment by Azipos** [comment]
Yeah, when I unistalled PerWorldPlugin, BentoBox BSkyBlock is operational. But I can't acces controlpanel though...

**Comment by tastybento** [comment]
Control panel is `/is cp` or `/is controlpanel`
