### ISSUE TITLE
When I reset the island, I still have all items

### ISSUE THREAD

**Issue by Azipos** [BentoBoxWorld/BSkyBlock#317]
#### Describe the bug

When I reset my island, I still have items. I tried it multiple times, as op and also as normal player. So I can farm with just resetting my island again and again.

#### Steps to reproduce the behavior

Really don't know.

#### Expected behavior

Items from previous island should disapear.

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/64070959/80949448-57a21c80-8df4-11ea-8b0c-9acf53d6f199.png)

##### BentoBox Version (Mandatory)

```
BentoBox version: 1.13.1
```

#### Plugins (Optional)

```
BentoBox, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Inventories
```

**Comment by Poslovitch** [comment]
Have a look at those options in BSkyBlock's config:

https://github.com/BentoBoxWorld/BSkyBlock/blob/b6b6483360db82ec4645300a6d80ee413c79c2f0/src/main/resources/config.yml#L255-L296

**Comment by Azipos** [comment]
Thanks!
