### ISSUE TITLE
Editing the schematic isnt possible?

### ISSUE THREAD

**Issue by Peda1996** [BentoBoxWorld/BSkyBlock#32]
Hello,

i just wanted to edit the schematics of the island, but mcedit and worldedit doesn't seem to load them. 
How can I edit therefore the schematic files?

**Comment by Poslovitch** [comment]
Schem files =/= schematics.
These are a dedicated format handled by BentoBox, which can be edited using `/bsbadmin schem` commands and by following this video guide: https://youtu.be/hFkP7hit3i4

We're looking forward adding a better way to manage all of this, and to add support for WE's schematics, but we'll definitely keep our handmade format, as it's very useful to us.

**Comment by Peda1996** [comment]
Danke für die schnelle Antwort :)

**Comment by Poslovitch** [comment]
Bitte sehr!
