### ISSUE TITLE
/is level and island creation lag

### ISSUE THREAD

**Issue by JKess731** [BentoBoxWorld/BSkyBlock#321]
#### Description
 Our server is on 1.15.2 tuinity and we have a bug with tps dropping /is level and island creation
#### Describe the bug 

whenever someone types /is level or creates an island, the tps lags 

#### Steps to reproduce the behavior

 We run the Minecraft 1.15.2 Tuinity git-Tuinity-"8f8b451" version

#### Expected behavior
 I think that there is possibly a way to make it so the tps doesn't drop as much?

##### BentoBox Version (Mandatory)
 1.12.0

```
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
They are both very intensive operations. There are config options in the Level addon to take more time to do the calculations. For pasting, have a look in the BentoBox config.yml for paste speed and try a lower value.

**Comment by JKess731** [comment]
Alright, i made the island level time longer and it fixed the tps issue so ill try making the paste speed longer as well
