### ISSUE TITLE
Creeper Grief

### ISSUE THREAD

**Issue by Ahmadh26** [BentoBoxWorld/BSkyBlock#326]
#### Describe the bug

I have disabled creeper griefing using `/bsb settings` in the overworld but creepers are still exploding blocks. i have tried both options.

#### Steps to reproduce the behavior

I set creeper griefing to disabled, got a creeper spawn egg and spawned it, it exploded the blocks.

#### Expected behavior

Blocks should not explode.

#### Screenshots and videos (Optional)

![bsb-settings](https://user-images.githubusercontent.com/57562297/81877058-cfa6da00-958c-11ea-8ba3-cbb5a6c807d1.png)
![creeper-exploded](https://user-images.githubusercontent.com/57562297/81877064-d1709d80-958c-11ea-89be-43be4267059a.png)

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.13.1
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
caveblock-world (CaveBlock): Overworld, Nether, The End
Loaded Addons:
BentoBox-InvSwitcher 1.6.1 (ENABLED)
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.13.1 (ENABLED)
CaveBlock 1.13.0 (ENABLED)
Challenges 0.8.2 (ENABLED)
Chat 1.0.5 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.0.0 (ENABLED)
Likes 1.7.1 (ENABLED)
Limits 1.12.2 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
TwerkingForTrees 1.3.1 (ENABLED)
Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
 Plugins (15): BentoBox, BungeeTabListPlus, CMI, CMIPaperLib, CommandHook, DiscordSRV, DiscordSRV-Staff-Chat*, LibsDisguises, LuckPerms, PlaceholderAPI, ProtocolLib, Spleef*, Vault, WorldEdit, WorldGuard
```

**Comment by tastybento** [comment]
Use CREEPER_DAMAGE. That when enabled, that prevents creeper damage.
CREEPER_GRIEFING protection is to enable/disable protection from visitors igniting creepers with flint & steel.
I've made a change to the locale file, so on your next update, removed en-US.yml and have it regenerate with better text.
