### ISSUE TITLE
Issue with villagers

### ISSUE THREAD

**Issue by Ahmadh26** [BentoBoxWorld/BSkyBlock#327]
#### Describe the bug

When we try to cure a zombie villager, the villager disappears. i've tried it a few times. 
Also when you spawn one with a villager spawn egg it does not spawn (you can hear the villager sound but nothing is shown ingame)
#### Steps to reproduce the behavior

- have a zombie villager, hit it with splash potion of weakness and give it a golden apple. after waiting the zombie villager will just disappear.

OR 

- get a villager spawn egg and use it

#### Expected behavior

Zombie villager becomes a villager instead of disappearing
OR
Villager will appear when using the villager spawn egg

#### Screenshots and videos (Optional)

https://youtu.be/0lX9BhVEDY8
A youtube video showing the problem.

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.13.1
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
caveblock-world (CaveBlock): Overworld, Nether, The End
Loaded Addons:
BentoBox-InvSwitcher 1.6.1 (ENABLED)
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.13.1 (ENABLED)
CaveBlock 1.13.0 (ENABLED)
Challenges 0.8.2 (ENABLED)
Chat 1.0.5 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.0.0 (ENABLED)
Likes 1.7.1 (ENABLED)
Limits 1.12.2 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
TwerkingForTrees 1.3.1 (ENABLED)
Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
 Plugins (15): BentoBox, BungeeTabListPlus, CMI, CMIPaperLib, CommandHook, DiscordSRV, DiscordSRV-Staff-Chat*, LibsDisguises, LuckPerms, PlaceholderAPI, ProtocolLib, Spleef*, Vault, WorldEdit, WorldGuard
```
 
### Additional context (Optional)

I've tried spawning villagers with `/spawnmob villager` and they spawned normally, i've attached a video of me curing the zombie villager and trying to spawn one with the spawn egg and both didn't work whereas spawning normal mobs with spawneggs works normally.

**Comment by tastybento** [comment]
I couldn't replicate this on a new server. If you try and use a spawn egg and it was prevented by BentoBox then it would show an error. I expect this is being prevented by one of your other plugins.

You can try `/bsb admin why` with the name of the player to see if BentoBox is blocking anything and why, but I expect it'll say ALLOWED in the console. That will definitely indicate it's another plugin blocking this. If not, then tell me what you see.

**Comment by Ahmadh26** [comment]
```
>.... [00:18:34 INFO]: _Jayy26 issued server command: /bsb why _Jayy26
>.... [00:18:40 INFO]: [BentoBox] Why: PlayerInteractEvent in world bskyblock_world at 152,121,202
>.... [00:18:40 INFO]: [BentoBox] Why: _Jayy26 SPAWN_EGGS - OP
>.... [00:18:40 INFO]: [BentoBox] Why: PlayerInteractEvent in world bskyblock_world at 152,121,202
>.... [00:18:40 INFO]: [BentoBox] Why: _Jayy26 SPAWN_EGGS - OP
>.... [00:18:40 INFO]: [BentoBox] Why: PlayerInteractEvent in world bskyblock_world at 152,121,202
>.... [00:18:40 INFO]: [BentoBox] Why: _Jayy26 SPAWN_EGGS - OP
>.... [00:19:22 INFO]: _Jayy26 issued server command: /r sure
>.... [00:19:25 INFO]: [BentoBox] Why: PlayerInteractEvent in world bskyblock_world at 155,121,202
>.... [00:19:25 INFO]: [BentoBox] Why: _Jayy26 SPAWN_EGGS - OP
>.... [00:19:27 INFO]: <MG> [MOD] Cyclonus07: You can use it to make lingering potions
>.... [00:19:33 INFO]: _Jayy26 issued server command: /tp Cyclonus07
>.... [00:19:37 INFO]: <MG> [Dev] _Jayy26: come
>.... [00:19:38 INFO]: <MG> [MOD] Cyclonus07: HOLY
>.... [00:19:47 INFO]: _Jayy26 issued server command: /bsb why _Jayy26
>.... [00:19:52 INFO]: _Jayy26 issued server command: /bsb why Cyclonus07
>.... [00:19:54 INFO]: <MG> [Dev] _Jayy26: try to spawn
>.... [00:19:56 INFO]: [BentoBox] Why: PlayerInteractEvent in world bskyblock_world at 383,31,418
>.... [00:19:56 INFO]: [BentoBox] Why: Cyclonus07 SPAWN_EGGS - BYPASS_EVERYWHERE
>.... [00:20:11 INFO]: <MG> [Dev] _Jayy26: okay. thanks
>.... [00:20:13 INFO]: _Jayy26 issued server command: /bsb why Cyclonus07
```
that's what i got in the console. The plugins that i have are listed. i have the following flags disabled with WorldGaurd: fire-spread & lava-fire.

**Comment by Ahmadh26** [comment]
@tastybento 
i have tried removing the plugins 1 by 1 and see if it fixes the problem but nothing happened.

**Comment by tastybento** [comment]
The _why_ result BYPASS_EVERYWHERE indicates that BentoBox is not blocking anything because the user has the mod permission `bskyblock.mod.bypassprotect` or similar. So, it's not a BentoBox issue.

If you removed all the plugins and this still happens, then maybe it's your server setup. Have a look at your server.properties file. Is `spawn-npcs=true` set?

If you skipped a few plugins, then make sure things like WorldGuard are not preventing villager spawning. There's a region flag to prevent it, e.g., `/rg flag __global__ deny-spawn villager`.

**Comment by Ahmadh26** [comment]
turns out npcs was off for some reason. Thank you so much tastybento!
