### ISSUE TITLE
Great plugin. Can I transport it to Chinese Minecraft website www.mcbbs.net?

### ISSUE THREAD

**Issue by 2173204318** [BentoBoxWorld/BSkyBlock#328]
Great plugin. Can I transport it to Chinese Minecraft website www.mcbbs.net?
https://www.mcbbs.net/thread-1044356-1-1.html

**Comment by Poslovitch** [comment]
Hi. It is already available there.

**Comment by 2173204318** [comment]
But it didn't update

**Comment by 2173204318** [comment]
> 你好 它已经在那里可用。
But it didn't update


> Hi. It is already available there.

But it didn't update
