### ISSUE TITLE
Hi. It is already available there.

### ISSUE THREAD

**Issue by 2173204318** [BentoBoxWorld/BSkyBlock#329]
Hi. It is already available there.

_Originally posted by @Poslovitch in https://github.com/BentoBoxWorld/BSkyBlock/issues/328#issuecomment-629363599_
But it didn't update

**Comment by Poslovitch** [comment]
Then just publish it...

**Comment by 2173204318** [comment]
> Then just publish it... If it's already available on MCBBS, it means we approved it already ^^
thanks! And Aoneblock is not published in Chinese minecraft forum.
