### ISSUE TITLE
What file do I find to edit island sizes from the 100*100?

### ISSUE THREAD

**Issue by Cabblestone** [BentoBoxWorld/BSkyBlock#332]
Just a plugin newbie trying to have bigger islands

**Comment by Poslovitch** [comment]
In the gamemode's config. I.e, in BSkyBlock's config, in that case.

**Comment by Cabblestone** [comment]
Thank you! But i go through Minehut and i'm having a hard time finding what i have to.

**Comment by Poslovitch** [comment]
It's both distance-between-islands and range

**Comment by Cabblestone** [comment]
Thank you mate!

**Comment by Cabblestone** [comment]
When I change this midgame what exactly do I have to reset?

**Comment by Poslovitch** [comment]
> exactly do I have to reset?

The worlds and databases.
