### ISSUE TITLE
Add The Classic L-Shaped Island

### ISSUE THREAD

**Issue by opticyclic** [BentoBoxWorld/BSkyBlock#338]
### Description
The original Skyblock by Noobcrew was an L-Shaped island.
It would be nice to see this as an option.

#### Describe the solution you'd like us to implement.
Add a 4th map option in the defaults.

#### Describe alternatives you've considered.
I have made a custom bundle but would like to see the l-shaped map in the defaults.

**Comment by FesterHead** [comment]
@opticyclic - do you have the same items in the chest as the default island 'island.blu'?
Care to upload your blueprint as a zip here?

**Comment by opticyclic** [comment]
I just realised that the original https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/maps/1473433-surv-skyblock and the latest version 4 https://www.planetminecraft.com/project/skyblock-4/ have different chests and I'm not sure if we want to include the obsidian in the chest.

This pull request only has lava and ice in the chest.

**Comment by tastybento** [comment]
Thanks!
