### ISSUE TITLE
Getting Started / Server

### ISSUE THREAD

**Issue by Zaris24** [BentoBoxWorld/BSkyBlock#34]
I would like to request 
A small Guide on how to start a server With
Bentobox and Bskyblock 

I have been Running a server before
but seems the jar files wont be loaded on my server
and some one else told i had to recompile them and thats where im clueless
So please how about makeing a small Guide ? Please
Love to help out and test the Bskyblock 
Been a fan of Skyblock for a long time 

Keep up the good Work

**Comment by Poslovitch** [comment]
Here you go: https://github.com/BentoBoxWorld/bentobox/wiki/Install-Bentobox 🙂

**Comment by Poslovitch** [comment]
Oh, and if you want some faster support, you can join our [Discord server](https://discord.bentobox.world).
