### ISSUE TITLE
Multiple Islands

### ISSUE THREAD

**Issue by KlayaR** [BentoBoxWorld/BSkyBlock#342]
Hello, 
I know that in october 2019 you had a request about adding the possiblity for players to have multiple islands. I would like to know if it's still something that you want to add?

Thank you 
Klayar

**Comment by tastybento** [comment]
It's in the works, but stalled a bit. There is other work that has to be done first. You can track this here: https://github.com/BentoBoxWorld/BentoBox/issues/108
