### ISSUE TITLE
Ender Man has no hatred against players and does not attack players

### ISSUE THREAD

**Issue by Xueyo02** [BentoBoxWorld/BSkyBlock#346]
Ender Man has no hatred against players and does not attack players
version:1.16.1
bentobox version:1.13.1
BskyBlock version:1.13.1
Core Version: Spigot 1.16.1

**Comment by Poslovitch** [comment]
Could you please make sure it still occurs if BentoBox is not on the server? I highly doubt that it is caused by BentoBox.

**Comment by tastybento** [comment]
I can replicate this issue on spigot with no BentoBox installed. Seems like a vanilla bug right now.

**Comment by tastybento** [comment]
He just gets angry but never moves to attack. This is on the nether island with BentoBox removed.
<img width="863" alt="Screen Shot 2020-06-27 at 8 22 54 AM" src="https://user-images.githubusercontent.com/4407265/85925803-cb3e3400-b84f-11ea-92ce-d2206a9b74c6.png">

**Comment by tastybento** [comment]
This is fixed in the latest version of spigot. Download it and it should work.
