### ISSUE TITLE
Error when creating new world

### ISSUE THREAD

**Issue by AnonAlpha** [BentoBoxWorld/BSkyBlock#353]
#### Describe the bug

When generating a new world got following errors (also happen on main world and end)
[https://pastebin.com/ZSCAcyNV](https://pastebin.com/ZSCAcyNV)
#### Steps to reproduce the behavior

Install latest bentobox and bskyblock
start server
wait for it to generator new world
#### Expected behavior

No error occured
#### Screenshots and videos (Optional)

None
### Environment
Paper 1.16.1
##### Output of `/bbox version` (Mandatory)

```

正在运行 PAPER 1.16.1.
Bentobox 版本：1.14.0-SNAPSHOT-b1828
数据库：JSON
已加载游戏世界：
bskyblock_world (BSkyBlock): &主世界, 地狱, 末界
已加载扩展：
Biomes 1.13.0-SNAPSHOT-b178 (ENABLED)
BSkyBlock 1.14.0-SNAPSHOT-b665 (ENABLED)
Challenges 0.9.0-SNAPSHOT-b418 (ENABLED)
ControlPanel 1.13.0-SNAPSHOT-b34 (ENABLED)
DimensionalTrees 1.6.1-SNAPSHOT-b81 (ENABLED)
MagicCobblestoneGenerator 2.0.0-SNAPSHOT-b129 (ENABLED)
Warps 1.10.0-SNAPSHOT-b261 (ENABLED)
_______
```

#### Plugins (Optional)

Only bentobox

**Comment by tastybento** [comment]
This is a server error. I was able to replicate it without BentoBox and I've filed an issue with Spigot, but it might be a Mojang vanilla error. https://hub.spigotmc.org/jira/browse/SPIGOT-5971

It should not affect game play.

**Comment by tastybento** [comment]
md5 wrote:

> Entirely vanilla. You can reproduce it just by making a flat world in server.properties
As far as I'm aware the 'error' doesn't affect anything.

So, we just have to wait for Mojang to fix it.
