### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by SenkuUzumaki** [BentoBoxWorld/BSkyBlock#358]
#### Describe the bug
Addons do not load, BSkyblock is loaded but commands are **NOT** working

Steps to reproduce the behavior
Have downloaded the following addons(all latest): biomes, border, bskyblock, challenges, chat, controlpanel, dimensonialtree, greenhouses, islandfly, level, likes, warps, bskyblock(ofc), bentobox(ofc)

Expected behavior
For the plugins & addons to load and work DUH

#### Screenshots and videos (Optional)

https://imgur.com/gallery/r3WXRv7

##### Output of `/bbox version` (Mandatory)
Running PAPER 1.15.2
BentoBox verrsion: 1.14.2
Database: JSON
Loaded Game Worlds: (empty)
Loaded Addons: (empty)

#### Plugins (Optional)
AdvancedBan*, BentoBox, Biscuit*, BSkyBlock*, BuycraftX, Citizens, CitizensCMD, CommandPanels, CrackShot, CraftEnhance, CreateYourOwnMenus, CustomEnderChest, DamageIndicator, DeathPenalties*, DeluxeMentions, DeluxeTags*, DiscordSRV, EliteLootbox, EpicBosses, EpicEnchants, EpicHeads, EpicVouchers, Ersatz*, Essentials, EssentialsChat, EZColors, FastAsyncWorldEdit, GrapplingHook*, GreatKits*, HeadDatabase*, HolographicDisplays, HolographicDisplaysAddon*, IllegalStack, Itemizer, Languagy, LibsDisguises, LuckPerms, Matrix, MMOCore, MMOItems, MMOLib, Multiverse-Core, MysqlEconomyBank, NoHunger, PL-Hide, PlaceholderAPI, PlayerParticles, ProtocolLib, PsudoCommand, PunishmentGUI*, Sentinel, ServerListPlus*, SkBee, Skellett, SkQuery, skRayFall*, Skript, skUtilities*, SpawnPermission, StaffChat, StaffModeGUI2*, SuperVanish, TAB, TradeSystem, TuSKe*, UltimateDrugs, UltraMinions, uShop, Vault, VehiclesPlusLite*, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, VoidTeleport, VoxelSniper, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, XProtect*, YoutubeBridge
_______
```
 
### Additional context (Optional)
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->

I switched from fabledskyblock to bskyblock

**Comment by Poslovitch** [comment]
May I ask you if you followed [this tutorial](https://bentobox-world.readthedocs.io/en/latest/BentoBox/Install-Bentobox/) ?

**Comment by tastybento** [comment]
You need to put addons into the BentoBox addon folder. They are not plugins.

**Comment by SenkuUzumaki** [comment]
IM so stupid im sorry
