### ISSUE TITLE
/[admin-command] range is work wrong

### ISSUE THREAD

**Issue by chickiyeah** [BentoBoxWorld/BSkyBlock#362]
#### Describe the bug

/[admin-command] range remove is work increase protection range

##### Output of `/bbox version` (Mandatory)

```
Running Spigot: 1.16.1
BentoBox version: 1.14.2
Database: JSON
Loaded Addons:
Biomes: 1.7.0
Border: 1.0.9
BSkyblock: 1.14.0
Challenges: 0.8.3
Control panel: 1.7.0
DimensionalPanel: 1.6.0
Level: 2.3.3
Limits: 1.14.0
Warps: 1.10.0

```

#### Plugins (Optional)

```

```

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/BentoBox/issues/1466
Duplicate and issue is fixed in the latest dev version
