### ISSUE TITLE
Nether Portal unapproachable in 1.16.2

### ISSUE THREAD

**Issue by gundall98** [BentoBoxWorld/BSkyBlock#371]
Currently using BentoBox V. 1.14.2 & BSkyBlock Addon V 1.14.0, and Paper v.179
Everything was okay while holding 1.16.1 version of paper.
I did not change anything on bskyblock's config file, but, entering both nether portal and end portal make no response. Is this only happens to me?

**Comment by fredthedoggy** [comment]
This may be related to [BentoBox/issues/1505](https://github.com/BentoBoxWorld/BentoBox/issues/1505)
Could you check to see if the nether/end are enabled?
