### ISSUE TITLE
Tuinity Paper crash after /is or /island

### ISSUE THREAD

**Issue by BrightPrimates** [BentoBoxWorld/BSkyBlock#372]
#### Describe the bug
This only happens with all players. When running the /is or /island command the server crashes. This is the output:
https://pastebin.com/Zbzu23jk

Edit:
After resetting the world... the plugin now gives the error:
Could not find a safe spot to teleport you to on the island. I have done nothing to the schematic files the plugin uses or even edited anything within the plugin or worldedit, worldguard... aka anything that should impact it.

Additionally I just loaded the blueprint with the plugin and it pastes in fine, seems fine etc.

#### Steps to reproduce the behavior
Client connects
Runs /is or /island

#### Expected behavior
Teleport the player to there island

### Environment
Tuinity version git-Tuinity-"0b86de3" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

##### Output of `/bbox version` (Mandatory)
Running Invalid (TUINITY) Invalid.
BentoBox version: 1.14.2
Database: JSON
Loaded Game Worlds:
islands (islands): Overworld, Nether, The End
Loaded Addons:
Biomes 1.13.0 (ENABLED)
BSkyBlock 1.14.0 (ENABLED)
Challenges 0.8.3 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.4.1 (ENABLED)
Limits 1.14.0 (ENABLED)
Warps 1.10.0 (ENABLED)
_______
```

#### Plugins (Optional)
Plugins (68): AdvancedAbilities, AdvancedEnchantments, AdvancedPortals, Animatronics*, ArmorStandTools, AsyncWorldEdit, AuctionMaster, AuctionMasterItemDisplay, BentoBox, BigDoors, BlockRegen, Citizens, CitizensCMD, CitizensText, CMI, CMIPaperLib, Collections, CommandPanels, CoreProtect, DeluxeChat, Denizen, DiceFurniture, Dimensions, DimensionsAddons, EntityTrackerFixer, eZProtector, FeatherBoard*, floodgate-bukkit, FurnitureLib, GCore, GPS, GrapplingHook*, GSigns, HandyOrbs, HeadDatabase*, HolographicDisplays, ItemJoin, LevelPoints, LibsDisguises, LuckPerms, MMOItems, MMOLib, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, MythicMobs, MythicMobsSpawnerGUI, PlaceholderAPI*, Plan, PlayerPoints*, PlayerProfiles, ProtectionLib*, ProtocolLib, QuestCreator, Rewards*, RoyaleEconomy, RPGRegions, ServerTutorialPlus*, SimpleGeyserVL, Skellett, Skript, TradeSystem*, Vault, VoidGenerator, Votifier, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by BrightPrimates** [comment]
Sorry, turns out this issue is for every player, new and ones who have islands already.

**Comment by tastybento** [comment]
The error is occurring due to lag from this plugin:

```

me.xxastaspastaxx.dimensions.portal.CustomPortal.isReturnWorld(CustomPortal.java:981)
[10:17:46] [Paper Watchdog Thread/ERROR]: 		me.xxastaspastaxx.dimensions.portal.PortalClass.findBestPathAndUse(PortalClass.java:383)
[10:17:46] [Paper Watchdog Thread/ERROR]: 		me.xxastaspastaxx.dimensions.portal.listeners.PortalListeners.onWorldChange(PortalListeners.java:291)
[10:17:46] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor614.execute(Unknown Source)
[10:17:46] [Paper Watchdog Thread/ERROR]: 		
```

That plugin listens for a world change event and then is taking a long time to process it. Paper detects the lag and raises the issue in the console. 

I recommend you try running without that plugin and see if that helps. 

There is no indication this is anything to do with BentoBox except that the player is teleporting to a new world.
