### ISSUE TITLE
After I upgraded from bentobox-1.11.1 to bentobox-1.15.0, player data cannot be used normally

### ISSUE THREAD

**Issue by 930708393** [BentoBoxWorld/BSkyBlock#377]
After I upgraded from bentobox-1.11.1 to bentobox-1.15.0, player data cannot be used normally

all addons ver is 1.11.1 i see have new "1.15.0" so i download used to server but the date not load

Is it necessary to use any data converter？I find it hard to find a solution in I place。

**Comment by tastybento** [comment]
No, no data convertor is required.

What errors do you see in the console log?

Do `bbox version` in the console and share the output so we know what database and the state of the addons.
