### ISSUE TITLE
permissions list

### ISSUE THREAD

**Issue by Joeripoes** [BentoBoxWorld/BSkyBlock#38]
make a list with all permissions, if there is not already

**Comment by tastybento** [comment]
Okay, I made a quick one here:

https://github.com/BentoBoxWorld/BSkyBlock/wiki/Home-Page

**Comment by Joeripoes** [comment]
Thanks a ton this is really helpfull, is there also a permission like - bskyblock.island.range.[number] and - bskyblock.team.maxsize.[number], because this was a thing in askyblock

**Comment by Poslovitch** [comment]
Yes, you can use them
