### ISSUE TITLE
Portal not working in nether

### ISSUE THREAD

**Issue by GIGABAIT93** [BentoBoxWorld/BSkyBlock#380]
After upgrading the server from 1.16.1 to 1.16.3, portals in nether do not work, how can I fix it?

**Comment by BONNe** [comment]
Mojang changed some server settings, and if nether and end are disabled in server.properties, portals will stop working.

In BentoBox 1.15.1 we implemented a "fix" for that, which will emulate portals with a custom teleportation.

**Comment by tastybento** [comment]
The latest snapshot for 1.15.1 is on the CI server, https://ci.bentobox.world.

**Comment by GIGABAIT93** [comment]
Thanks it helped me

**Comment by MViper** [comment]
Just use the plugin here 
https://dev.bukkit.org/projects/multiverse-netherportals
