### ISSUE TITLE
/island (and related) don't work.

### ISSUE THREAD

**Issue by AMOLINAE06** [BentoBoxWorld/BSkyBlock#381]
#### Describe the bug
At server startup the /is or /island (also related) commands do not work and I have to restart the server, this happens on minehut.
#### Steps to reproduce the behavior
I don't really know how to reproduce it, but it happens at server startup and I have to restart.

#### Expected behavior
The command should work fine every time the server starts up without the necessity of rebooting it.

##### Output of `/bbox version` (Mandatory)
Bentobox version: 1.15.0 (this one says paper invalid)
Bskyblock version: 1.14.0
Paper 249
_______
```

#### Plugins (Optional)
Plugins (13): Bentobox, Bskyblock*, Essentials, EssentialsChat, EssentialsSpawn, Kiteboard*, Luckperms, Mineresetlite, PlayerServer, Ultimate_Economy, Vault, WorldEdit, Worldguard
_______
```

**Comment by tastybento** [comment]
I don't understand. If it happens on startup, how does restarting the server help? Does it work at all?

It does look like BSkyBlock was not properly installed. For example, it is in your plugins folder. It should be in your addons folder (/plugins/BentoBox/addons).

In the console do `bbox version` and copy and paste the output.

**Comment by AMOLINAE06** [comment]
Thanks @tastybento the problem was that the plugin wasn't properly installed!
