### ISSUE TITLE
Nether-End teleport

### ISSUE THREAD

**Issue by bckd00r** [BentoBoxWorld/BSkyBlock#384]
Why can't we teleport to nether and end islands it's a mistake! needs to be added and edited.

/is reset (nether|end|normal)

/is tp (nether|end|normal)

portal should be able to be changed from custom config. (Nether and End)

Please take note of me. I have devoted a lot of time to this idea. </3

**Comment by tastybento** [comment]
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/1585
