### ISSUE TITLE
 Island reset limit and Island customization

### ISSUE THREAD

**Issue by Lopeww** [BentoBoxWorld/BSkyBlock#389]
I use the BentoBox Skyblock plugin.And my players can create unlimited islands once for 300 seconds.
Is there a limit to this?, For example, they can either take an island once or reset it 3 times in total.

As a second problem, I want to be able to customize the items and the mob names in the crate when I reset Island.

**Comment by tastybento** [comment]
Yes, look in the BSkyBlock config.yml for reset limiting. 

For custom blueprints, look on YouTube for BentoBox custom islands or read the docs on docs.BentoBox.world

**Comment by Lopeww** [comment]
Thank you for everything, and finally, how can I do the island borders ?, I saw somewhere they were doing it with the upgrade system.

**Comment by tastybento** [comment]
Do you mean show an island border, or change the protection sizes? You can use the Border addon for the first one, and for the protection sizes you can use permissions, commands or the Upgrade addon.
