### ISSUE TITLE
/bsbadmin setspawn

### ISSUE THREAD

**Issue by KinaQueen61** [BentoBoxWorld/BSkyBlock#391]
I want to set the world spawn for my skyblock world. 

I use the command /bsbadmin setspawn

However It's telling me 'There is no island here'
The world I used this command in is created with Multiverse-Core.
How do i fix this?

##### Output of `/bbox version` (Mandatory)

```
Biomes 1.13.0 (ENABLED)
BSkyBlock 1.14.3 (ENABLED)
Challenges 0.8.3 (ENABLED)
Chat 1.1.1 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.5.0 (ENABLED)
Likes 2.0.0 (ENABLED)
Limits 1.15.0 (ENABLED)
MagicCobblestoneGenerator 2.1.0 (ENABLED)
Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (22): BentoBox, BetterRTP, DeluxeHub, Essentials, EssentialsChat, GriefPrevention, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NoJoinMessage*, PlaceholderAPI, PlotSquared, PluginConstructorAPI, SetSpawn*, TabList, Vault, VoidGenerator, VoidSpawn, WorldEdit, WorldGuard
```

**Comment by fredthedoggy** [comment]
`/bsba setspawn` is meant for servers that only want 1 world, and not a separate spawn world from their island world. It only changes the command `/is spawn`, but it allows for an unregistered island to be useable.
I would suggest using EssentialsSpawn for what you are looking to do.

**Comment by KinaQueen61** [comment]
Okay thank you
