### ISSUE TITLE
Could not pass event IslandDeletedEvent to BentoBox v1.16.0-SNAPSHOT-b1947

### ISSUE THREAD

**Issue by n54b** [BentoBoxWorld/BSkyBlock#399]
https://pastebin.com/NKzsqqNV

I have this error when someone reset / create or leave island ... 

![image](https://user-images.githubusercontent.com/12047619/106735404-78fa9800-6614-11eb-9e35-b8b530af482e.png)

**Comment by BONNe** [comment]
Likes addon 2.1.0-b39 contains a bug.
https://github.com/BentoBoxWorld/Likes/issues/22

It is fixed in b40 version
