### ISSUE TITLE
Cannot unlock challenges with "type: level"

### ISSUE THREAD

**Issue by MXR156** [BentoBoxWorld/BSkyBlock#40]
**Description**
All of the chalenges in the Chalenges addon will not allow you to unlock them if it has been set to "type: level" in the config, Meaning you cant unlock Builder/Craftsman/Mason and any other custom ones.

**Steps to reproduce the behavior:**
1. Try to unlock Builder when using BSkyBlock with Challenges addon

**Expected behavior**
Chalenge to unlock and give rewards.

**Server Information:**
[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): YAML
 - OS: Linux (Unknown Version)
 - Java Version: Java 8
 - BentoBox Version Addon Versions.
Bentobox version: 0.17.0
Loaded Game Worlds: Skylands (BSkyBlock) 
Loaded Add-Ons - 
BSkyBlock 0.6.0 
Challenges 0.3.0-SNAPSHOT 
BentoBox-Level 0.0.2-SNAPSHOT 
Biomes 0.3.0-SNAPSHOT 
BentoBox-InvSwitcher 0.0.1-SNAPSHOT
 - Other plugins?
Plugins (21): LuckPerms, FastAsyncWorldEdit, LiteBansGUI, PlaceholderAPI, HolographicDisplays, Vault, SilkSpawners, Essentials, BentoBox, CustomOreGen, DeluxeMenus, Shop, SuperVanish, LiteBans, EssentialsSpawn, BungeeTabListPlus, DeluxeChat, TitleManager, WorldEdit, WorldGuard, ItemJoin

**Additional context**
I do have the development copy of BentoBox Levels addon that I haven't installed just yet, however will do this if it resolves the issue.

**Comment by Poslovitch** [comment]
I think you'll need to install the Level addon

**Comment by MXR156** [comment]
I've tried to update to both Version 0.4.0 and 0.2.0 from however they throw the below exceptions. I have stuck version 0.1.0 which seems to be working for me. Hope the below helps in the progression :)

0.4.0 error - 
`05.01 12:05:19 [Server] INFO Enabling BentoBox v0.17.0 05.01 12:05:19 [Server] INFO Loading addons... 05.01 12:05:19 [Server] ERROR Error occurred while enabling BentoBox v0.17.0 (Is it up to date?) 05.01 12:05:19 [Server] INFO java.lang.NoClassDefFoundError: world/bentobox/bentobox/api/addons/request/AddonRequestHandler 05.01 12:05:19 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at world.bentobox.bentobox.api.addons.AddonClassLoader.<init>(AddonClassLoader.java:47) ~[?:?] 05.01 12:05:19 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122) ~[?:?] 05.01 12:05:19 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_161] 05.01 12:05:19 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:58) ~[?:?] 05.01 12:05:19 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:122) ~[?:?] 05.01 12:05:19 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:05:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
`

0.2.0 error - 
`05.01 12:06:50 [Server] INFO Enabling BentoBox v0.17.0 05.01 12:06:50 [Server] INFO Loading addons... 05.01 12:06:50 [Server] ERROR Error occurred while enabling BentoBox v0.17.0 (Is it up to date?) 05.01 12:06:50 [Server] INFO java.lang.NoClassDefFoundError: world/bentobox/bentobox/api/addons/request/AddonRequestHandler 05.01 12:06:50 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at world.bentobox.bentobox.api.addons.AddonClassLoader.<init>(AddonClassLoader.java:47) ~[?:?] 05.01 12:06:50 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122) ~[?:?] 05.01 12:06:50 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_161] 05.01 12:06:50 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:58) ~[?:?] 05.01 12:06:50 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:122) ~[?:?] 05.01 12:06:50 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-82e117e-2b2d084] 05.01 12:06:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
`

**Comment by Poslovitch** [comment]
You need to update BentoBox to 1.0

**Comment by MXR156** [comment]
I actually missed that, Updated to BentoBox 1.0 and now everything seems to be working with the below specs and addons :).

Bentobox version: 1.0 
Loaded Game Worlds: Skylands (Skylands) 
Loaded Add-Ons 
- BSkyBlock 1.0 
- Challenges 0.3.0 
- Level 0.4.0-SNAPSHOT 
- Biomes 0.3.0-SNAPSHOT 
- BentoBox-InvSwitcher 0.0.1-SNAPSHOT
