### ISSUE TITLE
Villager reproduction problem

### ISSUE THREAD

**Issue by Wings-Fantasy** [BentoBoxWorld/BSkyBlock#400]
### Description

Can it be achieved to prevent creatures from destroying the terrain while allowing villagers to pick up items to breed？

It may be a configuration I don’t know, or a plug-in needs to be added

**Comment by tastybento** [comment]
We do not have any protection from creatures or villages picking up items except for protection against Enderman block taking. So, villages should be able to gather what they need. Do you see a problem? Can you share more information?

**Comment by Wings-Fantasy** [comment]
I asked the op of the server, she changed the mobGriefing rule of the game, saying that it was because creeper would break the block

**Comment by tastybento** [comment]
Yes, that protects against creeper explosions, but that should not affect villagers. I hope it works for you.

**Comment by hank9999** [comment]
> I asked the op of the server, she changed the mobGriefing rule of the game, saying that it was because creeper would break the block

I have the same problem, you have just saved me!
