### ISSUE TITLE
BREAK_HOPPER default flag missing from config.yml

### ISSUE THREAD

**Issue by Zorua162** [BentoBoxWorld/BSkyBlock#401]
#### Describe the bug

By default the BREAK_HOPPER flag is missing from the config.yml and therefore it defaults to member.
Therefore cooped and trusted players on an island cannot break hoppers.
#### Steps to reproduce the behavior

 - Start a new island,
 - Coop/ trust a friend
 - They cannot break hoppers
 - Admins trying to fix this from config have a hard time finding it/ setting it
 when setting the server up.
 NB: This can be fixed from the gui, however I believe this required OP which isn't
very desirable. 
#### Expected behavior

By default this flag should be in `addons/BSkyblock/config.yml`
Therefore it can be changed to coop by default and this issue doesn't stop players
who cannot change this setting.

As far as I can see all that needs to be done is that
    BREAK_HOPPERS: 500
needs to be added to default-island-flags: in the config.yml. (Note it is already 
in acid islands one so this just makes the sb behaviour the same).
This will retain the current behaviour, but allow for the flag to easily be found 
in the config and therefore when making changes from config it can be changed 
without having to add it in (which I don't believe is documented anywhere).

##### Output of `/bbox version` (Mandatory)

```
Running PAPER 1.16.4.
BentoBox version: 1.15.5
Database: JSON
Loaded Game Worlds:
skyblock (skyblock): Overworld, Nether
Loaded Addons:
Biomes 1.14.0 (ENABLED)
Border 2.0.2 (ENABLED)
BSkyBlock 1.14.3 (ENABLED)
Challenges 0.8.3 (ENABLED)
Chat 1.1.2 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Greenhouses 1.4.2 (ENABLED)
IslandFly 1.8.0 (ENABLED)
Level 2.5.1 (ENABLED)
Likes 2.0.0 (ENABLED)
Limits 1.15.2 (ENABLED)
TwerkingForTrees 1.4.1 (ENABLED)
Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (10): AutoPluginLoader, BentoBox, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, MobArena*, Multiverse-Core, Vault, WorldEdit
```
 
### Additional context (Optional)

For any servers trying to fix this issue themselves before this is patched:
add 
    BREAK_HOPPERS: 500
to default-island-flags:
in your BSkyBlock\config.yml
then do /bsbadmin resetflags BREAK_HOPPERS 
to add this change to all islands,  note that this is not required if you do not hide the 
BREAK_HOPPERS flag from your /is settings gui, so you can move along and have a nice day.

**Comment by Zorua162** [comment]
This also seems to be missing from AOneBlock's config and SkyGrid, but not CaveBlock and AOneBlock.

**Comment by tastybento** [comment]
Thanks for the report. BentoBox was updating the game mode configs with flags missing from the config.yml files but the addons were then reloading the config and losing that information before saving the config.yml again. This is now fixed and all flags should be auto-added to the configs if they don't already exist.
