### ISSUE TITLE
Villager can't breed within island protection

### ISSUE THREAD

**Issue by dazedtracers** [BentoBoxWorld/BSkyBlock#403]
#### Describe the bug
villagers make lotsa hearts, but only angry particles within island protection.

#### Steps to reproduce the behavior
after a day or so of thinkin I was just unlucky.. quick test outside protected range they breed just fine

#### Expected behavior
villager should breed normally, unless maybe limits installed.

#### Screenshots and videos (Optional)
sry, i have none

### Environment
1.16.5-R0.1 (git-Paper-526)

##### Output of `/bbox version` (Mandatory)

```
11:31:53.384[CHAT] Biomes 1.14.0 (ENABLED)
11:31:53.384[CHAT] BSkyBlock 1.14.3 (ENABLED)
11:31:53.384[CHAT] Challenges 0.8.3 (ENABLED)
11:31:53.384[CHAT] Chat 1.1.3 (ENABLED)
11:31:53.384[CHAT] CheckMeOut 1.0.2 (ENABLED)
11:31:53.384[CHAT] ControlPanel 1.7.0 (ENABLED)
11:31:53.384[CHAT] DimensionalTrees 1.6.0 (ENABLED)
11:31:53.384[CHAT] ExtraMobs 1.11.0.3 (ENABLED)
11:31:53.384[CHAT] Greenhouses 1.5.1 (ENABLED)
11:31:53.384[CHAT] IslandFly 1.7.3 (ENABLED)
11:31:53.422[CHAT] Level 2.5.2 (ENABLED)
11:31:53.422[CHAT] Likes 2.2.0-SNAPSHOT-b55 (ENABLED)
11:31:53.422[CHAT] Limits 1.15.5 (ENABLED)
11:31:53.423[CHAT] MagicCobblestoneGenerator 2.2.1 (ENABLED)
11:31:53.423[CHAT] TwerkingForTrees 1.4.1 (ENABLED)
11:31:53.423[CHAT] Upgrades 0.2.0-SNAPSHOT-b80 (ENABLED)
11:31:53.423[CHAT] Visit 1.1.0 (ENABLED)
11:31:53.423[CHAT] Warps 1.10.2 (ENABLED)```

#### Plugins (Optional)
<!-- Paste the `/plugins` output inside the code block below (remove the underscores). Do not provide an image. -->
```
11:33:52.860[CHAT] Plugins (63): AuctionHouse, AutoAFK*, BentoBox, BossBroadcast*, BossShopPro, ChatControl, ChestShop, Citizens, ClearLag, ColoredAnvils*, CoreProtect, CrateReloaded, CS-CoreLib, DeluxeChat, ElectricSpawners, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, ExoticGarden, EZRanksPro, FeatherBoard*, HolographicDisplays, IPWhitelist*, Jobs, LimitedUses*, LiteBans, MarriageMaster, mcMMO, MobCapturer, Multiverse-Core, MVdWPlaceholderAPI*, MysqlPlayerDataBridge, Nicky*, PermissionsEx*, PerWorldInventory, PlaceholderAPI, PlayerPoints*, PlayerVaults, PluginConstructorAPI, PlugMan, PremiumVanish, ProtocolLib, RandomTeleport, ServerListPlus*, ShowItem, SilkSpawners, Skript, Slimefun, Smileychat*, SQLibrary*, SuperbVote, TAB, Towny, TownyNameUpdater*, Vault, ViaBackwards, ViaVersion, VKBackPack, VoidWorld*, Votifier, WorldEdit, WorldGuard```
 
### Additional context (Optional)

was running BentoBox 1.15.5 bundle i'd downloaded the other day..everything else seems to function as expected. downloaded dev builds this morning an still no luck..perhaps I've simply missed a setting. Pretty sure I allowed everything, and even rebooted after amnual check of config.yml(s) to make sure on the fly setting changes not taking effect weren't the issue. We did have limits set, "VILLAGER: 16" removed limits.jar altogether and still have problem.

**Comment by dazedtracers** [comment]
oops, looks like i missed a little on the bentobox version output:

11:31:53.331[CHAT] Running PAPER 1.16.5.
11:31:53.383[CHAT] BentoBox version: 1.16.0-SNAPSHOT-b2001
11:31:53.384[CHAT] Database: JSON
11:31:53.384[CHAT] Loaded Game Worlds:
11:31:53.384[CHAT] bskyblock (BSkyBlock): Overworld, Nether, The End
11:31:53.384[CHAT] Loaded Addons:
11:31:53.384[CHAT] Bank 1.3.0 (ENABLED)
11:31:53.384[CHAT] BentoBox-InvSwitcher 1.6.1 (ENABLED)
11:31:53.384[CHAT] Biomes 1.14.0 (ENABLED)
11:31:53.384[CHAT] BSkyBlock 1.14.3 (ENABLED)
11:31:53.384[CHAT] Challenges 0.8.3 (ENABLED)
11:31:53.384[CHAT] Chat 1.1.3 (ENABLED)
11:31:53.384[CHAT] CheckMeOut 1.0.2 (ENABLED)
11:31:53.384[CHAT] ControlPanel 1.7.0 (ENABLED)
11:31:53.384[CHAT] DimensionalTrees 1.6.0 (ENABLED)
11:31:53.384[CHAT] ExtraMobs 1.11.0.3 (ENABLED)
11:31:53.384[CHAT] Greenhouses 1.5.1 (ENABLED)
11:31:53.384[CHAT] IslandFly 1.7.3 (ENABLED)
11:31:53.422[CHAT] Level 2.5.2 (ENABLED)
11:31:53.422[CHAT] Likes 2.2.0-SNAPSHOT-b55 (ENABLED)
11:31:53.422[CHAT] Limits 1.15.5 (ENABLED)
11:31:53.423[CHAT] MagicCobblestoneGenerator 2.2.1 (ENABLED)
11:31:53.423[CHAT] TwerkingForTrees 1.4.1 (ENABLED)
11:31:53.423[CHAT] Upgrades 0.2.0-SNAPSHOT-b80 (ENABLED)
11:31:53.423[CHAT] Visit 1.1.0 (ENABLED)
11:31:53.423[CHAT] Warps 1.10.2 (ENABLED)

sry for that

**Comment by tastybento** [comment]
We don't do anything to prevent villages from mating and if the angry heats are appearing then I suspect it's just that the mating rules aren't being met. I'm looking at this link:
https://minecraft.gamepedia.com/Village_mechanics#Breeding_and_population_cap

> Villagers go into love mode (indicated by red heart particles above both their heads) if they have enough food to make themselves and their partner willing. They enter love mode based on their amount of food, not the population cap (based on the number of beds), but can produce a baby only if they have their own beds plus an available bed for the baby, and the beds have two empty blocks above them (there needs to be room for the baby to jump on the bed). **If the population cap is met, or the beds are obstructed, angry particles appear above their heads (along with the heart particles), preventing them from mating.**

Are there enough beds and are they not obstructed?

In regards to the population cap, it's bed related and the villagers are counted like this:

> The breeding depends on the number of valid beds. If a villager is "willing", villagers breed as long as there are unclaimed beds available within the limits of the village. ... A census is periodically taken to determine the current population of the village. All villagers within the horizontal boundary of the village and 5 vertical blocks‌[Java Edition only] of the center are counted as part of the population to determine if continued villager mating is allowed.

**Comment by dazedtracers** [comment]
island spacing 400
protected range 96

//cyl 4 cobblestone
atop cobble //hcyl glass 5 3
set 3 beds, /summon villager (2x), give a few bread..so long as they are outside protection they breed fine

identical setup inside island protected range will w many many stacks of bread and about as many hours of tweaking settings n removing add-ons only make angry particles after hearts. in my experience, if beds are invalid they simply don't become "willing" at all

i will see if i can come up w fresh server n do some some further testing. I'd imagine the problem is me, just hoping for a little help

thx tho :)

**Comment by dazedtracers** [comment]
and i am absolutely just dumb..thx for indulging my ignorance :)
