### ISSUE TITLE
/bskyblock switch command broken

### ISSUE THREAD

**Issue by AmazedMender16** [BentoBoxWorld/BSkyBlock#409]
#### Describe the bug

When staff uses the command to switch on/off protection bypass, the command runs fine, but it does not do a single thing. They are still being prevented from making changes to other people their islands "Block breaking disabled" as example.

#### Steps to reproduce the behavior

Login with non-owner account, give yourself /bskyblock switch permissions and run the command, then try to change things on other people their islands.

#### Expected behavior

It should switch on bypass and allow user to make edits like it did before.

#### Screenshots and videos (Optional)

https://prnt.sc/10xvzlr

##### Output of `/bbox version` (Mandatory)

```
Running PAPER 1.16.5.
BentoBox version: 1.16.1
Database: MYSQL
Loaded Game Worlds:
sb4-world (Skyblock): Overworld, Nether, The End
Loaded Addons:
Bank 1.3.0 (ENABLED)
Biomes 1.14.0 (ENABLED)
Border 3.0.1 (ENABLED)
BSkyBlock 1.14.4 (ENABLED)
Challenges 0.8.4 (ENABLED)
Level 2.6.2 (ENABLED)
Limits 1.15.5 (ENABLED)
MagicCobblestoneGenerator 2.3.0 (ENABLED)
Warps 1.10.2 (ENABLED)
```

**Comment by tastybento** [comment]
You missed a step - the mod needs the `bskyblock.mod.bypassprotect` permission as well. The permission for switch command just gives you the permission to use that command to turn on and off protections. In other words, switch enables you to flip between being a normal player and whatever role you have (Op, Mod, etc). but you still need the right perms for that role. This enables you to have mods who have different perms and want to switch them on and off.

**Comment by AmazedMender16** [comment]
@tastybento when did this behavior change then? I made no changes to permissions since 1.15.x bento. After upgrading it stopped working.

**Comment by tastybento** [comment]
1.16.x changed this behavior.

**Comment by AmazedMender16** [comment]
@tastybento figured.. must have not been in the changelog then so I missed it.
I compared the 2 tags ( 1.15.5 and 1.16.1 ) and spotted the following 2 that probably explains it.
https://github.com/BentoBoxWorld/BentoBox/commit/ce79588805c4796a3e8aa7bed63b8cc0445357cb
https://github.com/BentoBoxWorld/BentoBox/commit/1da3539f0232a7aa60d11b01730fb61dbc83b38b
