### ISSUE TITLE
commands issue

### ISSUE THREAD

**Issue by mcx6** [BentoBoxWorld/BSkyBlock#41]
i cant use /bsbadmin setspawn
and there is no /is spawn
thank you foe your time you guys are always the best

**Comment by Poslovitch** [comment]
BSkyBlock has not been updated to BentoBox 1.1 yet.

**Comment by tastybento** [comment]
I’m, there is no setspawn command yet too....

**Comment by Poslovitch** [comment]
@tastybento It has been added on the develop branch.
