### ISSUE TITLE
Polish translation problem 

### ISSUE THREAD

**Issue by stachuXp** [BentoBoxWorld/BSkyBlock#414]
hey, I use the translation built into the bento box, instead of something like [liczba] [pozycja] [numer] and so on

![probelm](https://user-images.githubusercontent.com/79519257/116206385-05fa4c80-a73f-11eb-997f-e24e1271d806.png)

**Comment by tastybento** [comment]
The placeholders have been translated. Placeholders in the text need to stay as English. We'll need to look through the file and fix those.
