### ISSUE TITLE
Topbreeders

### ISSUE THREAD

**Issue by ghost** [BentoBoxWorld/BSkyBlock#415]
### Description
Hello. Would it be possible to add as it was in ASkyBlock topbreeders? When someone has alot of mobs, it is really good to have it fast. It would be awesome. Thanks

**Comment by tastybento** [comment]
Just to clarify, what problem would this solve for you? Is it an admin command, or a like a top ten for users?

**Comment by Aricius2** [comment]
Admin. When someone has alot of mobs on island, TPS goes down and without it it is for us pretty hard to go around and find out where it is happening

**Comment by tastybento** [comment]
Okay got it. Yes, it'd only work if the chunks were loaded, so the player would need to be online for it to work.

**Comment by BONNe** [comment]
(or create addon, as in https://github.com/BentoBoxWorld/BentoBox/issues/1572 request)
