### ISSUE TITLE
Buttons, pressure plates doesn´t work on islands for visitors

### ISSUE THREAD

**Issue by Aricius2** [BentoBoxWorld/BSkyBlock#416]
### Description
Hello. Simply, if i allow use of for example buttons or pressure plates, visitors still can´t use them. This problem is only with visitors. Only island that works fine is spawn.  (tried everything about redstone)

**Comment by tastybento** [comment]
Huh. Try this: run the `/bsb why (player_name)` command on the visitor and then have they try to use a button or pressure plate. The console will produce some debug to tell you why they cannot (or can) do the action. Share that output.

Also, when reporting bugs, please use the template and share the `/bbox version` at least so I know what versions you are using.

**Comment by Aricius2** [comment]
Yes. Sorry. Will do. But, it is now working? I did the exact same thing as before and now it is working. So idk. But, if i will be able to reproduce it again, i will do what you said. Thanks

**Comment by Aricius2** [comment]
Hello. Fixed it. Turns out, offline-redstone was false
