### ISSUE TITLE
Nether Generator bug

### ISSUE THREAD

**Issue by bipedd** [BentoBoxWorld/BSkyBlock#424]
#### Describe the bug
The block infront of where the lava source is on a nether generator does not generate.

## ## Steps to reproduce the behavior
Make a simple 5 block long lava generator and place a lava source and mine.
Pickaxe I used had Efficiency 5, Fortune 3, Mending, and Unbreaking 3.

#### Expected behavior
The block should generate like a nether gen should.

#### Screenshots and videos (Optional)

Screenshot: ![2021-06-07_15 11 44](https://user-images.githubusercontent.com/77213949/121094215-220ff580-c7a3-11eb-9405-32079fe19b06.png)
Video: https://youtu.be/UT_YjHqLcII

### Environment
The nether

##### Output of `/bbox version` (Mandatory)
```
Running TUINITY 1.16.5
BentoBox Version: 1.16.2
DATABASE: JSON
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Biomes 1.14.0
Border 2.02
BSkyBlock 1.14.4
Challenges 0.8.3
Chat 1.1.1
ControlPanel 1.7.0
ExtraMobs 1.11.0.3
IslandFly 1.8.0
Level 2.5.1
MagicCobblestoneGenerator 2.2.1
TwerkingForTrees 1.4.1
Warps 1.10.2
All enabled
```

**Comment by BONNe** [comment]
Can you confirm that it is not a ghost block?

The current MCG does not create blocks by itself, it just changes which block generates after lava meet blue ice.

One more thing could be that in your nether generator is air block in block list?

**Comment by Bipedfriend173** [comment]
I can confirm it is not a ghost block as when I click there nothing happens and I can stand in it and it doesn't bug out. Acts as no block is there. For the air block in the block list, I'm pretty sure its not in there but here's a couple screenshots of its GUI.
![2021-06-07_19 57 46](https://user-images.githubusercontent.com/77213949/121116238-0f111b80-c7cb-11eb-97d3-aaaf555f8498.png)
![2021-06-07_20 00 23](https://user-images.githubusercontent.com/77213949/121116247-10dadf00-c7cb-11eb-9cec-4254ff11aae4.png)
