### ISSUE TITLE
Island reset dont erase my previous inventory.

### ISSUE THREAD

**Issue by jarruego** [BentoBoxWorld/BSkyBlock#425]
#### Describe the bug

island reset dont erase my previous inventory. Any solution? I put keep-previous-island-on-reset: false in config.yml
#### Steps to reproduce the behavior

Put keep-previous-island-on-reset: false in config.yml and restart server
#### Expected behavior

Remove inventory when i restart the island
##### Output of `/bbox version` (Mandatory)

```
_______
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I use SepareWorldItems plugin. I don't know if it affects

**Comment by Fredthedoggy** [comment]
https://github.com/BentoBoxWorld/BSkyBlock/blob/develop/src/main/resources/config.yml#L332-L373
Same as posted in discord, `keep-previous-island-on-reset: false` does something very different

**Comment by jarruego** [comment]
Sorry I was watching in principal bentobox config file

sorry sorry sorry Auchh!!!!
