### ISSUE TITLE
Essentials /sethome support

### ISSUE THREAD

**Issue by bipedd** [BentoBoxWorld/BSkyBlock#431]
#### Is your feature request related to a problem?
Add support for essentials sethome.

#### Describe the solution you'd like us to implement.
I use /sethome (command from essentials) and I'd like to put it on my skyblock server in addition to /is sethome as that command is not per player. The issue is you can /sethome on other peoples islands.

#### Describe alternatives you've considered.
Don't really have any.

### Additional context
None

**Comment by BONNe** [comment]
Sorry, but we cannot code anything into the essentials plugin. You should ask them :)

We have option in config that allows to block commands:
`visitor-banned-commands`

Where you can block `/sethome` command.

**Comment by bipedd** [comment]
Ah thank you!
