### ISSUE TITLE
Inventory Clearing at changing worlds

### ISSUE THREAD

**Issue by Jmaniacs** [BentoBoxWorld/BSkyBlock#432]
### Description
Hi, at the moment of changing worlds between my skyblock hub and bskyblock_worlds it clear my inv, and gives me so many achievements unlocked.(this happens for everyone, not only me), im using Multiverse-inventories, and it is working properly to my other gamemode(survival).

#### Steps to reproduce the behavior
Im just changing between worlds(skyblockhub -> bskyblock_world)

#### Expected behavior
Nothing, it should'nt clear my inv and give so many achievements

#### Screenshots and videos (Optional)
![image](https://user-images.githubusercontent.com/45721052/125145110-29058d00-e0ee-11eb-9a08-222d6422a83d.png)
![image](https://user-images.githubusercontent.com/45721052/125145233-826dbc00-e0ee-11eb-85ab-ba09507e540e.png)

##### Output of `/bbox version` (Mandatory)
(Everything is enables)
```
Spigot:1.16.5
Bbox:1.16.2
bskyblock_world(Bskyblock): Mundo, Nether, End
Biomes 1.14.0
Bskyblock 1.14.0
Challenges 0.8.4
ControlPanel 1.13.0
DimensionalTrees 1.16.0
InvSwitcher 1.11.0
Level 2.6.3
Likes 2.1.1
Limits 1.15.5
MagicCobblestoneGenerator 2.3.0
Warps 1.10.2
```

#### Plugins (Optional)
```
Plugins (61): TubeTils, PlaceholderAPI, PluginManager, SimpleFlyPlugin, InvSee, NametagEdit, Broadcaster, VariableTime, UserLogin, SkinsRestorer, MCVotes-Integration, LuckPerms, WonderChat, PerWorldChat, UltimateStatistics, BannerBoard, ProtocolLib, LibsDisguises, AdvancedPortals, AdvanceParticle, VoidGenerator, EasyPlayerFreeze, SpawnerManager, Vault, PixelVip, AntiCooldown, SimpleRename, HolographicDisplays, AConomy, AdvancedKits, LPC, WorldEdit, Spectator, PlayerKits, LiteBans, UltimateChat, BentoBox, TAB, HolographicExtension, WorldGuard, Spartan, JetsMinions, Shop, GadgetsMenu, EpicFarming, Multiverse-Core, Citizens, SuperVanish, DeluxeHub, SpecializedCrates, Multiverse-Inventories, McDuels, TitleManager, BuildBattlePro, zAuctionHouseV3, DiscordSRV, ItemJoin, HideAndSeek, BuildBattlePro-StartMessage, PartyGames, DiscordSRV-Staff-Chat
```
 
### Additional context (Optional)

This is not happening between bskyblock_world, bskyblock_world_the_end, bskyblock_world_nether. Only between 'skyblock' and 'bskyblock_world'

**Comment by BONNe** [comment]
Well, you have InvSwitcher addon.

Remove it and it will stop doing it.

**Comment by tastybento** [comment]
Yes, InvSwitcher is for switching out inventories and achievements, etc.
