### ISSUE TITLE
vanilla nether is being generated

### ISSUE THREAD

**Issue by yueyinqiu** [BentoBoxWorld/BSkyBlock#433]
i enabled `world.nether.islands` and it works well before. but today a player told me that his nether island is generated upper the bedrocks so i teleported there and found it like this, under the bedrocks in spectator mode:

![img](https://user-images.githubusercontent.com/18749772/126667093-110a34bf-75c9-4eac-8954-687889e41d78.png)

a vanilla nether is generated here.

i don't think it's a bug because my server is in 1.16.5, which is incompatible. i just want to know how to solve the problem temporarily since all the new players' islands is going to be like this.

i can even accept completely deleting the nether world, but i think it won't work and may cause more problems so i'm here to ask.

##### Output of `/bbox version` (Mandatory)
```
服务器： 无效 (YATOPIA) 1.16.5
BentoBox 版本： 1.16.2
数据库： JSON
已载入的游戏世界：
bskyblock_world (BSkyBlock) : 主世界, 下界, 末地
已载入的附加组件：
Bank 1.3.0 (ENABLED)
Biomes 1.14.0 (ENABLED)
Border 3.1.1 (DISABLED)
BSkyBlock 1.14.4 (ENABLED)
Challenges 0.8.4 (ENABLED)
Chat 1.1.3 (ENABLED)
CheckMeOut 1.0.2 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
ExtraMobs 1.11.0.3 (ENABLED)
Greenhouses 1.5.3 (ENABLED)
IslandFly 1.8.1 (ENABLED)
Level 2.6.3 (ENABLED)
Likes 2.1.1 (ENABLED)
Limits 1.15.5 (ENABLED)
MagicCobblestoneGenerator 2.3.0 (ENABLED)
TwerkingForTrees 1.4.1 (ENABLED)
Visit 1.3.0 (ENABLED)
VoidPortals 1.5.0.0 (ENABLED)
Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (78): AuthMe, AutoRestart*, Barrels, BBSToper*, BentoBox, BetterEnchantBook*, BkyBlockEX, ChatItemDisplay, ChestCommands, ChopTree2, Citizens, CitizensGUI, ClearEntity*, ColoredEnderChests, ConfigItem*, CoreProtect, CratesLottery, CreateX, CS-CoreLib, CustomCrafting, EliteMobs, Essentials, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraHeads, EzTools, FastLogin*, FlowerPower, Geyser-Spigot, GlobalMarketChest, GroupManager, HolographicDisplays, HopperFilter, Images, ipsave, IronElevators*, LangUtils, LightAPI, LuckyCubes, mcMMO, mcMMOView, MineTinker, MiniMOTD, Multiverse-Core, MySkin, NoSpawnChunks, NotBoom*, Notbuild, OhTheWorld, patronSaint, PlaceholderAPI, PlayerIntensify, PlayerKits, PlayerTitle, PlugMan, PrivateStorage, ProtocolLib, QuickShop, RandomMoneyChat*, ShadowJoin*, Shift_Menu*, Shopkeepers, Signin*, Slimefun, spark, Stp*, SZYMLNoBoom, TitleManager, TResources*, TrMenu, Vault, ViaVersion, VoidGenerator, WGAcheck, WolfyUtilities, WorldEdit, WorldGeneratorApi
```

these are two screenshots of the edge of the two kinds of nether (y=128 and y=256):

![2021-07-22_23 32 39](https://user-images.githubusercontent.com/18749772/126667140-8e9dbab1-2d81-4b1d-8a6d-a7af7021431b.png)

![2021-07-22_23 33 17](https://user-images.githubusercontent.com/18749772/126667155-9ceb405c-d961-4c2a-adc4-42b5f7c0cae4.png)

**Comment by tastybento** [comment]
Do you have the BSkyBlock world set as the only world on your server?

**Comment by yueyinqiu** [comment]
> Do you have the BSkyBlock world set as the only world on your server?

```
====[ Multiverse World List ]====
world - NORMAL
world_the_end - THE_END
world_nether - NETHER
bskyblock_world_nether - NETHER
bskyblock_world_the_end - THE_END
bskyblock_world - NORMAL
```

**Comment by tastybento** [comment]
Sorry for the very late reply. I suspect that these chunks were made prior to you switching on the nether islands, so the world was already generated as normal nether here.

**Comment by yueyinqiu** [comment]
> Sorry for the very late reply. I suspect that these chunks were made prior to you switching on the nether islands, so the world was already generated as normal nether here.

This is a possibility. Since I'm also not that sure about this and it's hard to reproduce, maybe I shall close the issue.
I will open a new one if my new server runs into the problem again. Thank you for your help.
