### ISSUE TITLE
island chest is empty

### ISSUE THREAD

**Issue by moraisandreua** [BentoBoxWorld/BSkyBlock#434]
It's not possible this problem is only mine, but I couldn't find on closed issues.

On generating the island, the chest is empty. Then I found your video explaining how to load/save an island scheme (to put some items in the chest), but the command you gave us (/bsbadmin scheme load ...) does not exist.

**Comment by BONNe** [comment]
The scheme command was renamed to the blueprint.

**Comment by kccricket** [comment]
Any idea which in which Spigot commit that was fixed?

**Comment by Fredthedoggy** [comment]
8d244b0b SPIGOT-3725, SPIGOT-6638, MC-136917: Properly clear tile entities before replacing

**Comment by moraisandreua** [comment]
I suppose the problem was the papermc, because after swapping to spigot, it worked, thanks!

**Comment by Fredthedoggy** [comment]
> I suppose the problem was the papermc, because after swapping to spigot, it worked, thanks!

It is not a problem with PaperMC, it is a problem with Spigot, that was brought to Paper. Spigot has Since fixed it, and Paper has updated to match.
