### ISSUE TITLE
island settings

### ISSUE THREAD

**Issue by VincoNafta** [BentoBoxWorld/BSkyBlock#442]
### Is your feature request related to a problem?

Hi,

I want to add new option to island settings. This setting is in command bskyblock settings, but i want to this option in island settings, because I using certian island for server minigame. This option is for visitors and damage in this optinon on czech locale named "Nesmrtelní Navštevníci". 

Thanks and have a nice day

**Comment by tastybento** [comment]
Yes, Invincible Visitors (Nesmrtelní Navštevníci) is worldwide setting and not per-island. I do not think I can make it per-island easily. Can you use the PVP on/off setting?

**Comment by VincoNafta** [comment]
Yes, but PVP settings is not work for monsters. This option works only PVP => Player vs. Player, Not Monster vs player. Thanks for anwser

**Comment by tastybento** [comment]
Okay. What settings do you want to have for visitors your mini-game?

**Comment by VincoNafta** [comment]
Please add MobAttack and entity explosion :)
