### ISSUE TITLE
Hi! Please help me. I really need to have only two ranks on the islands: visitor and member. Or at least I need players without "op" to see only these two ranks. I have seen several requests on this topic, but I have not found anything. How can I make only two ranks?

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/BSkyBlock#444]

**Comment by BONNe** [comment]
Simple answer: you cannot.

Banned, coop, trusted has main functionallity within plugin. 
The only underutilized rank is sub-owner.

There are feature requests that wants a customization in this part, but due to complexity and time constraints, it is not done.

**Comment by tastybento** [comment]
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/528

**Comment by Pikachu2p** [comment]
Ok. Thanks for answer
