### ISSUE TITLE
Hello! Is it possible to choose the settings for the island not in the panel, but specifically by commands?

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/BSkyBlock#445]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

For example, I want to enable and disable the pvp flag on the island using the /is settings DOOR off visitor command (which means that the ability to open doors will be closed for the visitor.

> 

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

/is settings DOOR off visitor 

or

/is flag DOOR off visitor

**Comment by tastybento** [comment]
Yes, this command line settings are supported. Do `/bsb settings ` and then hit tab to see the completion options for world settings. Do `/bsb settings tastybento `  then tab to see all the settings for tastybento's island. E.g.:

```
> bsb settings tastybento 
BED                          BEACON                       CRAFTING                     LEAF_DECAY                   COLLECT_LAVA                 HURT_VILLAGERS
DYE                          BUCKET                       MINECART                     NOTE_BLOCK                   CROP_TRAMPLE                 PRESSURE_PLATE
BOAT                         BUTTON                       NAME_TAG                     PVP_NETHER                   FIRE_BURNING                 FIRE_EXTINGUISH
CAKE                         ELYTRA                       REDSTONE                     SPAWN_EGGS                   FROST_WALKER                 FLINT_AND_STEEL
DOOR                         HOPPER                       SHEARING                     TNT_DAMAGE                   HURT_ANIMALS                 MOUNT_INVENTORY
EGGS                         RIDING                       TRAPDOOR                     ARMOR_STAND                  PLACE_BLOCKS                 POTION_THROWING
GATE                         BREWING                      COMPOSTER                    ENDER_PEARL                  BREAK_HOPPERS                EXPERIENCE_PICKUP
HIVE                         DROPPER                      CONTAINER                    FIRE_IGNITE                  COLLECT_WATER                ANIMAL_NATURAL_SPAWN
LOCK                         FURNACE                      DISPENSER                    FIRE_SPREAD                  COMMAND_RANKS                ANIMAL_SPAWNERS_SPAWN
help                         JUKEBOX                      ITEM_DROP                    ITEM_PICKUP                  FISH_SCOOPING                MONSTER_NATURAL_SPAWN
ANVIL                        LECTERN                      DRAGON_EGG                   SHULKER_BOX                  HURT_MONSTERS                MONSTER_SPAWNERS_SPAWN
CHEST                        MILKING                      ENCHANTING                   TNT_PRIMING                  NETHER_PORTAL                EXPERIENCE_BOTTLE_THROWING
LEASH                        PVP_END                      END_PORTAL                   TURTLE_EGGS                  PVP_OVERWORLD
LEVER                        TRADING                      FLOWER_POT                   BREAK_BLOCKS                 TRAPPED_CHEST
BARREL                       BREEDING                     ITEM_FRAME                   CHORUS_FRUIT                 BREAK_SPAWNERS
```

To turn on PVP:
```
> bsb settings tastybento PVP_OVERWORLD Active
```

To set the DOOR setting:

```
> bsb settings tastybento DOOR 
Coop        help        Owner       Member      Trusted     Visitor     Sub-Owner
```

**Comment by Pikachu2p** [comment]
Wow! Thanks so much! ;)

**Comment by Pikachu2p** [comment]
I have a problem. When I enter a command, I just get an example of the command (/bsbadmin settings [player]): open system settings etc..., but the pvp does not change. I just need to change the flag without the panel, only with the command

/bsb settings Steve PVP_OVERWORLD Active

**Comment by tastybento** [comment]
It works... here's what I just did on my server:
```
> bsb settings BoxManager PVP_OVERWORLD Disabled
[19:07:40 INFO]: Success!
```
Note that the user, in this case BoxManager, must be the owner of the island. 

What version of BentoBox are you using? Share the output of `bbox version`

**Comment by Pikachu2p** [comment]
Strange, it doesn't work for me. I did everything right, but I just get help BSkyBlock (/bsbadmin settings [player]: open system settings or island settings for player

bbox version
[18:49:29 INFO]: Currently running Invalid (PURPUR) 1.15.2 .
[18:49:29 INFO]: BentoBox version: 1.14.2
[18:49:29 INFO]: Database: JSON
[18:49:29 INFO]: Loaded game worlds:
[18:49:29 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether
[18:49:29 INFO]: Uploaded add-ons:
[18:49:29 INFO]: BSkyBlock 1.14.3
[18:49:29 INFO]: Challenges 0.8.4
[18:49:29 INFO]: ControlPanel 1.13.0
[18:49:29 INFO]: IslandFly 1.7.0
[18:49:29 INFO]: Level 2.3.3
[18:49:29 INFO]: Limits 1.12.1
[18:49:29 INFO]: MagicCobblestoneGenerator 2.1.0
[18:49:29 INFO]: Warps 1.9.7

**Comment by tastybento** [comment]
Well, your BentoBox version is very old. You are on 1.14 so that's why - it wasn't a feature back then. I recommend you take backups and then consider upgrading to BentoBox 1.17.2.

**Comment by Pikachu2p** [comment]
So I need to change the kernel version to 1.17? It's just that BentoBox 1.17.3 doesn't work for me on my version of purpur 1.15.2

**Comment by BONNe** [comment]
Well, it is not as easy as "chanigng version".

BentoBox 1.17+ uses Java 16, and it uses things that are in Minecraft 1.17.

So if you want to use it on 1.15.2, you need to downgrade Java 8 version for BentoBox, remove all 1.16 and 1.17 things from code and then you could use it on your 1.15.

**Comment by Pikachu2p** [comment]
Oh well, I think it's actually easier to upgrade to a newer version. I've tried everything and everything really works for me! I think it's worth it, thank you so much for your support ;)

But I have one more question. Are there placeholders for showing the island settings? For example, so that I can add a placeholder %bskyblock__island_flags_door% so that at the moment I can understand whether it is enabled or not.

**Comment by BONNe** [comment]
No, there is no such placeholders.
It is blocked by: https://github.com/BentoBoxWorld/BentoBox/issues/1070

**Comment by Pikachu2p** [comment]
OK thanks a lot for the support ;)
