### ISSUE TITLE
Hey! Is it possible for one player to create multiple islands? I want to make permissions for the ranks of the players, so that a regular one has 1 island, and with a higher rank it can have 3 islands at once. Can you do this?

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/BSkyBlock#446]
Hey! Is it possible for one player to create multiple islands? I want to make permissions for the ranks of the players, so that a regular one has 1 island, and with a higher rank it can have 3 islands at once. Can you do this?

**Comment by BONNe** [comment]
No, each player can have 1 island per gamemode.

Either as an owner or team member.
There already are feature request that asks this thing: https://github.com/BentoBoxWorld/BentoBox/issues/108
