### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by zuhir** [BentoBoxWorld/BSkyBlock#45]
Can make a poeditor (or similar) page for plugin translation?

**Comment by tastybento** [comment]
I would like to, but we have a lot of strings so we would need to pay.

I recommend you take the locale file and then submit the changes as a Pull Request. 

Thank you for your support!

**Comment by Poslovitch** [comment]
Check the locales folder

**Comment by TheIntelloBox** [comment]
I have only the sign of the island to translate, is it normal ? :D

**Comment by Poslovitch** [comment]
Then you don't understand how BentoBox works.

BentoBox provides 99.9% of the features of a gamemode. Therefore, most of the translation is done in BentoBox.

**Comment by tastybento** [comment]
@TheIntelloBox Please translate the locales in BentoBox first. The GameModes only do extra text.
