### ISSUE TITLE
ASkyBlock to BSlyBlock.

### ISSUE THREAD

**Issue by TheIntelloBox** [BentoBoxWorld/BSkyBlock#46]
Hello ! :D

I have many questions. :D 
1) Is the plugin fully released ? :D (I mean all features of ASkyBlock are included ?)
2) Is there a converter between ASkyBlock and BSkyBlock ? :D 

Thanks for your answer ! :D 
TheIntelloBox. :D

**Comment by Poslovitch** [comment]
1. BentoBox is definitely released. We're just not publishing it on SpigotMC as long as we don't have enough documentations ready. And there are definitely more features than ASB - but some from ASB have not been ported yet to BentoBox.
2. FAQ. Planned, no ETA.

**Comment by TheIntelloBox** [comment]
And last question, if I want to create a new world with islands, etc, could you tell me what must I do ? :D

**Comment by Poslovitch** [comment]
Be more specific please

**Comment by BONNe** [comment]
1. You download BentoBox.
2. Run server with BentoBox and stop after it started.
3. You download BSkyblock and put it in BentoBox/addons folder.
4. Run server. :)

**Comment by TheIntelloBox** [comment]
I mean, how to create the island world ?
