### ISSUE TITLE
Why World Generator will generate ocean and villages?

### ISSUE THREAD

**Issue by HurryBy** [BentoBoxWorld/BSkyBlock#467]
### Expected behavior

Players in Bskyblock **play well** (Acuatlly When there were more than 100 players on the server, I found this problem)

### Observed/Actual behavior

Img : 
![4R6Q(ZSGTM)DAWVKLIT4P`L](https://user-images.githubusercontent.com/47547391/152282626-6fd1f3b7-cfca-4872-97c8-9b849f7c2231.png)
![T29 UMA79PEC2Y9}UXTBCVQ](https://user-images.githubusercontent.com/47547391/152282632-349e060c-df45-40e0-b8ff-4a1c06ad5692.png)

There is naturally generated terrain below the player generated island.
People can break blocks .....
This caused me a lot of trouble

### Steps/models to reproduce

No any error.I think it must have had problems when the world was created, but when we recreated a bskyblock world, it worked normally.
I removed bskyblock_world and plugin auto create a new world(problem world)
I changed config.yml about World_name part(normal world)

### BentoBox version

![BAD](https://user-images.githubusercontent.com/47547391/152282685-4a23e946-f895-412a-822b-53d90a34f3b5.png)

### Plugin list

![BAD](https://user-images.githubusercontent.com/47547391/152282608-69dffe53-92ef-4446-90da-f58335da78ea.png)

### Other

Please, help us. This is really a huge loss to our server. Players can build new islands that have 6000+ levels. Or, do you have any way to solve this problem. thank you!!!!!

**Comment by BONNe** [comment]
Hmm, that could happen only if Void World generator is disabled.
https://github.com/BentoBoxWorld/BSkyBlock/blob/21eacb025d7b18ae1fad3dd8cb32ef9232bed7af/src/main/resources/config.yml#L73-L77

Otherwise world would generate flat terrain.

Another thing could be that some other plugin hijack world generation. Not sure how that could be achieved exactly, but maybe via incorrect bukkit.yml world section.

**Comment by HurryBy** [comment]
Have any way to fix this problem yet? :(
 use-own-generator was never set to true; (maybe Multiverse-Core ?)

**Comment by BONNe** [comment]
Is that happening continuously when you generate new chunks? Or it happened only for some areas?

**Comment by HurryBy** [comment]
Some of the first islands were normal When X: 6000 comes, there will be villages and oceans under the island.

My idea is to create a new world, then move the player Island intact, change the world in the configuration file, or use the map modifier to delete the redundant terrain in the original world.But the software was not found:(

**Comment by BONNe** [comment]
Have you set any generator related options in:
bukkit.yml?

**Comment by HurryBy** [comment]
Here is my bukkit.yml file

settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 6000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  monsters: 40
  animals: 5
  water-animals: 5
  water-ambient: 10
  ambient: 5
chunk-gc:
  period-in-ticks: 300
  load-threshold: 1145
ticks-per:
  animal-spawns: 750
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  ambient-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml

**Comment by BONNe** [comment]
I am clueless how that could happen. 
Do you have any custom blueprint that is very large?

**Comment by HurryBy** [comment]
Are 1500 blocks too many?

**Comment by BONNe** [comment]
No, i was just guessing, that may be a normal terrain was saved inside blueprint.

How did you create BSkyBlock world:
- you let bento box to create it.
- you used other plugin to create it

**Comment by HurryBy** [comment]
I let bento box to create it.

**Comment by BONNe** [comment]
@tastybento do you have any ideas how normal terrain could be generated in BSkyBlock worlds?

**Comment by tastybento** [comment]
I am surprised this is happening and you have asked all the right questions Bonne. 

Vanilla terrain should *never* be generated unless you enter the world and BentoBox is not running. If it is running but the generator is being overridden then you get flat land. 

I can only think that there is some kind of server incompatibility or bug. If you are using snapshots then update and see if it still happens. Or try a different server.

**Comment by HurryBy** [comment]
hmmm.It's happened and the problem hasn't been found. Forget it.:D

if I  let bento box to create a new world and changed 
![QQ截图20220203155054](https://user-images.githubusercontent.com/47547391/152302168-e004fd4e-2d68-458c-a073-42bcd25bbd3f.png)

this Settings , is the island will be generate? Or I need to move this island into this world with right location?

**Comment by tastybento** [comment]
You would need to copy and paste the island blocks into a new world using WorldEdit or similar. But I would check first that the same problem doesn't occur otherwise it won't help.

To debug, one approach is to copy your server to your home computer and start with just BentoBox active and no other plugins. See if new terrain is generating still. If so, then it may be a server setting or the server code itself. 

You could also try a clean server install and just BentoBox and then build up the plugins until the problem occurs.

**Comment by HurryBy** [comment]
WorldEdit can not load bskyblock_world :(

**Comment by HurryBy** [comment]
Can old players use old map and new players generate their new islands in the new world?

**Comment by BONNe** [comment]
No, each BentoBox GameMode supports just one world.

Could you explain what you mean with `WorldEdit can not load bskyblock_world`?

**Comment by tastybento** [comment]
When I said WorldEdit I meant you'd need to copy and paste each individual island from one world to another.

**Comment by BONNe** [comment]
Maybe you could upload multi-verse world config file.

It could be that multi-verse has picked up the issue with the world.

**Comment by HurryBy** [comment]
[Files.zip](https://github.com/BentoBoxWorld/BSkyBlock/files/7999537/Files.zip)

> Could you explain what you mean with ?`WorldEdit can not load bskyblock_world`

There's a program named "MCEdit".It's a program to load level.dat and change the world in a quick way.
But it was code by python 2.7 and it doesn't work :(

> When I said WorldEdit I meant you'd need to copy and paste each individual island from one world to another.

Yeah . That's what I'm doing.

**Comment by HurryBy** [comment]
> In config replace main material with AIR in all dimensions

Do you mean replace main-block with air?
Replace blocks: [] with air?
Shoud I change use-own-generator: true to false?
Shoud I change default-biome: THE_VOID to PLAINS?
Shoud I change create-and-link-portals to false?

**Comment by HurryBy** [comment]
> Replace CaveBlock locales with BSkyBlock locales.
Could you please explain what you mean with :(

**Comment by HurryBy** [comment]
It does work!:D
but Rank system will not work :(

**Comment by BONNe** [comment]
> [Files.zip](https://github.com/BentoBoxWorld/BSkyBlock/files/7999537/Files.zip)
> 
> > Could you explain what you mean with ?`WorldEdit can not load bskyblock_world`
> 
> There's a program named "MCEdit".It's a program to load level.dat and change the world in a quick way. But it was code by python 2.7 and it doesn't work :(
> 
> > When I said WorldEdit I meant you'd need to copy and paste each individual island from one world to another.
> 
> Yeah . That's what I'm doing.

Based on level.dat file that you provided, I can say that provided world was not generated by BentoBox. That is the reason why it has normal terrain generation.

**Comment by BONNe** [comment]
> > In config replace main material with AIR in all dimensions
> 
> Do you mean replace main-block with air? Replace blocks: [] with air? Shoud I change use-own-generator: true to false? Shoud I change default-biome: THE_VOID to PLAINS? Shoud I change create-and-link-portals to false?

- AIR
- I think use-own-generator option is disabled in CaveBlock so it does not matter.
- Yes, you can change biome
- Depends. I prefer with linked portals, but that is my preference.

**Comment by BONNe** [comment]
> > Replace CaveBlock locales with BSkyBlock locales.
> 
> Could you please explain what you mean with :(

In /plugins/bentobox/locales/caveblock/<locale>.yml
Keep only:
```caveblock:
  sign:
    line0: "&cCaveBlock"
    line1: "Welcome!"
    line2: "[name]"
    line3: "Start digging! &c<3"
```
