### ISSUE TITLE
Are there any plugin conflicts with Bskyblock and BentoBox? Bskyblock 以及 BentoBox 有與甚麼插件衝突嗎

### ISSUE THREAD

**Issue by wadtwff** [BentoBoxWorld/BSkyBlock#471]
### Expected behavior

想請問一下Bskyblock 以及 BentoBox 有與甚麼插件衝突嗎
或是 他會再 CraftBukkit , spigot , paper 伺服器中有什麼缺點嗎

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### BentoBox version

.

### Plugin list

.

### Other

.

**Comment by tastybento** [comment]
No known conflicts. We recommend using Paper because it has optimizations that Spigot does not have.
