### ISSUE TITLE
Add a flag to prevent other players from rotating glowing item frames

### ISSUE THREAD

**Issue by PapiCapi** [BentoBoxWorld/BSkyBlock#475]
### Is your feature request related to a problem?

Players can rotate item frames on other islands.

### Describe the solution you'd like.

Add a flag that could prevent that.

### Describe alternatives you've considered.

For me the flag is the best option.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
There already is: `ITEM_FRAME`

**Comment by PapiCapi** [comment]
Oh didn't saw it was working because i was testing with the glowings ones.
Actually, it would make sense if they had the same behaviour with the same flag.

Is there any way to prevent the same interactions with the glowing item frames ?

**Comment by BONNe** [comment]
Implemented in dev version of BentoBox.
