### ISSUE TITLE
endportal above y256 doesn't work

### ISSUE THREAD

**Issue by SlamBam140** [BentoBoxWorld/BSkyBlock#478]
### Expected behavior

the expectation is that players spawn on their end island like happends below y256

### Observed/Actual behavior

if players create an endportal above y256 they get teleported to the default obsidian platform at the 0 coords in the end where the vanilla end island is supposed to be

### Steps/models to reproduce

build an endportal above y256
now enter the portal and you will spawn on the obsidian platform instead of your own island

### BentoBox version

Running PAPER 1.18.2.
BentoBox version: 1.21.0-SNAPSHOT-b2283
Database: JSON
Loaded Game Worlds:
skyblock_world (SkyBlock): Overworld, Nether, The End
Loaded Addons:
Bank 1.4.0-SNAPSHOT-b59 (ENABLED)
Biomes 2.1.0-SNAPSHOT-b225 (ENABLED)
Border 3.3.0-SNAPSHOT-b136 (ENABLED)
BSkyBlock 1.15.2-SNAPSHOT-b719 (ENABLED)
Challenges 1.1.0-SNAPSHOT-b486 (ENABLED)
Chat 1.1.4 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
ExtraMobs 1.12 (ENABLED)
IslandFly 1.10.0-SNAPSHOT-b143 (ENABLED)
Level 2.9.1-SNAPSHOT-b509 (ENABLED)
Limits 1.19.1-SNAPSHOT-b300 (ENABLED)
MagicCobblestoneGenerator 2.5.0-SNAPSHOT-b251 (ENABLED)

**Comment by BONNe** [comment]
Fixed in BentoBox 1.21
