### ISSUE TITLE
The sand brush machine can't be used. I really hope I can get help. Thank you.

### ISSUE THREAD

**Issue by 1642579950** [BentoBoxWorld/BSkyBlock#489]
### Expected behavior

Hello! I can't use the sand brush in an empty island anymore. After testing, it can be used smoothly as long as BentoBox is deleted. Can you help me solve this problem? Thank you very much.

And creatures can't be transported to the terminal through the terminal portal, but creatures placed with eggs can be transported!

### Observed/Actual behavior

I hope I can use the sand brushing machine, which is very useful for me.

### Steps/models to reproduce

Sand brushing machine cannot be used.

### BentoBox version

1.21.1

### Plugin list

BentoBox-1.21.1

**Comment by BONNe** [comment]
What is sand brushing machine?
And what is terminal?

**Comment by BONNe** [comment]
Please check that ENTITY_PORTAL_TELEPORT flag in world settings is enabled.

If flag is disabled then entities will not be able to report via portāls

**Comment by 1642579950** [comment]
I enable ENTITY_ PORTAL_ After TELEPORT, the next portal cannot transmit entities. The terminal gate can transfer entities

**Comment by 1642579950** [comment]
Ha ha ha, thank you for your help, I have successfully solved it!!!
