### ISSUE TITLE
plugin.xml is missing in jar

### ISSUE THREAD

**Issue by kalleswe** [BentoBoxWorld/BSkyBlock#49]
It seems that the plugin.xml that must go into bskyblock-1.0.jar after compiling the project is missing.
Minecraft won't load the plugin since it can't find it. And also I can't find that xml file in the git project files either.

**Comment by tastybento** [comment]
Apologies that this is not apparent in the README (I've updated it [here](https://github.com/BentoBoxWorld/BSkyBlock)) but this is not a Bukkit plugin. You need to installed BentoBox first (which is a plugin) and then put this into the Addons folder.
