### ISSUE TITLE
add /is delhome

### ISSUE THREAD

**Issue by RK96** [BentoBoxWorld/BSkyBlock#490]
### Is your feature request related to a problem?

In my server players can create island homes with /is sethome name, but they can't change the name or remove the home once created.

### Describe the solution you'd like.

adding the command /is delhome 

### Describe alternatives you've considered.

command /is resethomes

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
In Bentobox we have home deletion and renaming:

- `[player_cmd] deletehome <home>`
- `[player_cmd] renamehome <home>`

These commands should be available by default. If your server does not have, check if you have assign correct permissions to the players.

- `[gamemodes].island.deletehome`
- `[gamemodes].island.renamehome`

**Comment by tastybento** [comment]
I'm sorry, our docs are out of date ([I just updated them](https://docs.bentobox.world/en/latest/gamemodes/BSkyBlock/Commands/)), but they should be viewable in the in-game help. There are 4 commands to manage homes:

/is homes - lists the homes the player has
/is sethome - sets the current location as their home and enables them to name it
/is deletehome - for deleting a named home
/is renamehome - enables you to rename a home

**Comment by tastybento** [comment]
Haha, BONNe answered while I was updating the docs.
