### ISSUE TITLE
players spawn in void when entering the end

### ISSUE THREAD

**Issue by SlamBam140** [BentoBoxWorld/BSkyBlock#491]
### Expected behavior

I expect that players will be spawned on their end island or at least at the closest safe location from where they enter the end (since there were no [spawn_here] signs in the end blueprint)

### Observed/Actual behavior

if players enter their end dimension they get teleported on the same location as they entered which is most likeley in the void

### Steps/models to reproduce

1. build an end portal
2. enter the end portal
3. you will fall in the void if you didn't build your endportal at the same location as your end island
https://youtu.be/bh68vI00QrQ

### BentoBox version

Running PAPER 1.19.2.
BentoBox version: 1.22.0-SNAPSHOT-b2308
Database: JSON
Loaded Game Worlds:
skyblock_world (SkyBlock): Overworld, Nether, The End
Loaded Addons:
Bank 1.4.0-SNAPSHOT-b62 (ENABLED)
Biomes 2.1.0-SNAPSHOT-b238 (ENABLED)
Border 3.3.0-SNAPSHOT-b136 (ENABLED)
BSkyBlock 1.17.0-SNAPSHOT-b722 (ENABLED)
Challenges 1.1.0-SNAPSHOT-b492 (ENABLED)
Chat 1.1.4 (ENABLED)
ControlPanel 1.13.1-SNAPSHOT-b56 (ENABLED)
DimensionalTrees 1.6.1-SNAPSHOT-b84 (ENABLED)
ExtraMobs 1.12 (ENABLED)
IslandFly 1.10.0-SNAPSHOT-b143 (ENABLED)
Level 2.9.1-SNAPSHOT-b510 (ENABLED)
Limits 1.19.1-SNAPSHOT-b301 (ENABLED)
MagicCobblestoneGenerator 2.5.0-SNAPSHOT-b252 (ENABLED)

### Plugin list

Plugins (73): AdvancedGift, AntiAFKPlus, AreaShop, AuctionHouse, AutoPickup2, BedrockMiner, BentoBox, BetonQuest, BlockLocker, BossShopPro, BottledExp, BuycraftX, ChestShop, ChestShopNotifier, Citizens, CitizensIntergration*, CleanroomGenerator, CMI, CMILib, DeathMessages, DeluxeCoinflip, DeluxeCombat, DeluxeCombat_Addon_WG*, Duels, DungeonSystem, eco, EcoEnchants, EffectLib, FastAsyncWorldEdit (WorldEdit), FeatherBoard, HeadDatabase, HolographicDisplays, HyperDrive, Hyperverse, InteractiveBoard, ItemShops*, LagAssist, LeaderHeadsRevamped, LibsDisguises, LimitCrafting, LimitedUses*, LogBlock, mcMMO, Minepacks, MobFarmManager, MythicMobs, NametagEdit, NBTAPI, NetworkManager, ParticlesMenu, PL-Hide, PlaceholderAPI, PlayerParticles, PremiumVanish, ProtocolLib, RoseStacker, SendToConsole*, Shopkeepers, SimplePets, Spartan, SpecializedCrates, TCRestart*, TNTRun_reloaded, TradeSystem, UltimateShoutPro, UltimateVotes, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, VoidGen, WGEF-Reborn, WorldGuard

**Comment by tastybento** [comment]
Hmm. I can't seem to replicate this. There is a [spawn_here] sign on the default End Island blueprint and you do seem to be teleported to it (or close to it) when you go into the End via a gateway. Also, when an admin teleports using `/bsb tpend` it goes there too. I added some debug code and the location is definitely being picked up. If you don't see the [spawn_here] sign in your blueprint then may be it was removed somehow - you can download it again.

I was wondering if some config setting might cause this, but I set `create-obsidian-platform: true` to see if that would affect things, but that correctly created an obsidian platform where I teleported too. That could also be an option for you.

I'm not sure why you are seeing that except that it does seem your end island doesn't have the [spawn_here] sign and the safe teleport spot search can't find a spot (it only searches around so far). So, I recommend you add the sign and see if that helps.

**Comment by tastybento** [comment]
<img width="850" alt="Screenshot 2022-12-28 at 11 23 20 AM" src="https://user-images.githubusercontent.com/4407265/209862916-771ecaa3-2fe3-468c-b1f2-8de0c76cff42.png">
<img width="738" alt="Screenshot 2022-12-28 at 10 53 09 AM" src="https://user-images.githubusercontent.com/4407265/209862927-75ac022e-b7f0-4898-8f94-a4d9279f6395.png">

**Comment by tastybento** [comment]
Yes, you can adjust the value in this setting in _BentoBox's_ config.yml_ to be more than 16 (Line 225):

```
island.safe-spot-search-range:
```

You can also enable the obsidian platform option as mentioned above.
