### ISSUE TITLE
ITEMS OF BENTOBOX IN CONFIG.YML DOESN'T WORKS

### ISSUE THREAD

**Issue by Phoenix-99** [BentoBoxWorld/BSkyBlock#495]
### Expected behavior

I thought that panel item from bentobox configs support custom model data but no

### Observed/Actual behavior

I'm in bentobox/config.yml, exactly in this tring 
![image](https://user-images.githubusercontent.com/63762282/215958067-8be9faad-6cf6-4b5f-96b0-1c9e6cbb4294.png)
but item doesn't support custom model data
![image](https://user-images.githubusercontent.com/63762282/215958165-63c2c848-7cbd-43b6-a144-d13897467aab.png)
the same happens in addons/visit/config.yml
![image](https://user-images.githubusercontent.com/63762282/215960443-74b71e1a-7503-46c6-bacd-6476e1402179.png)
![image](https://user-images.githubusercontent.com/63762282/215960519-1a28edf8-17ad-4c90-8fcf-91e976faa845.png)
those head with that custom model data should be displayed like this head
![image](https://user-images.githubusercontent.com/63762282/215960698-1a56af49-8715-491c-adad-b8451eee6818.png)

### Steps/models to reproduce

this is the normal gui, with glass panels 
![image](https://user-images.githubusercontent.com/63762282/215958562-661861fc-9662-46c4-a81d-d62e807e0a5d.png)
i can change the item too
![image](https://user-images.githubusercontent.com/63762282/215958669-baba8954-2d6a-499b-a962-c9ef0df618f8.png)
but when i set custom model data it doesn't work and it returns the last material
![image](https://user-images.githubusercontent.com/63762282/215958899-84ba28ab-9d1a-4509-afd0-f3cb46941514.png)

### BentoBox version

![image](https://user-images.githubusercontent.com/63762282/215958437-943eb834-fc17-4e15-8d76-57875748f027.png)

**Comment by BONNe** [comment]
Visit addon config does not allow such things as icons must be changed via customizable panels. 

About the issue with the settings menu... well, until customizable panels it will not be fixed.
