### ISSUE TITLE
Grammar issue in island messages

### ISSUE THREAD

**Issue by Jeremys556** [BentoBoxWorld/BSkyBlock#500]
### Expected behavior

When a player leaves your island, you get a message displaying that they did so. However, the grammar on this message is incorrect. It should say "[player] left your island".

### Observed/Actual behavior

When a player leaves your island, it says "[player] leaved your island", which is incorrect gramatically.

### Steps/models to reproduce

1. Have a player /is visit your island
2. Have the player get off your island

### BentoBox version

29.05 13:40:18 [Server] [INFO] Running PAPER 1.19.4.
29.05 13:40:18 [Server] [INFO] BentoBox version: 1.23.1
29.05 13:40:18 [Server] [INFO] Database: JSON
29.05 13:40:18 [Server] [INFO] Loaded Game Worlds:
29.05 13:40:18 [Server] [INFO] bskyblock_world (BSkyBlock): Overworld
29.05 13:40:18 [Server] [INFO] Loaded Addons:
29.05 13:40:18 [Server] [INFO] BSkyBlock 1.16.1 (ENABLED)
29.05 13:40:18 [Server] [INFO] Chat 1.1.4 (ENABLED)
29.05 13:40:18 [Server] [INFO] Likes 2.3.1 (ENABLED)
29.05 13:40:18 [Server] [INFO] Visit 1.6.0 (ENABLED)

### Plugin list

29.05 13:40:40 [Server] [INFO] Server Plugins (34):
29.05 13:40:40 [Server] [INFO] Bukkit Plugins:
29.05 13:40:40 [Server] [INFO] - ABCore, ABSkyLantern, AntiCurse, BentoBox, BentoBox-BSkyBlock, BentoBox-Likes, BentoBox-Visit, BuycraftX, ChestShop, ClearLag
29.05 13:40:40 [Server] [INFO] DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GrimAC, GUIShop, IllegalStack
29.05 13:40:40 [Server] [INFO] LuckPerms, MessageAnnouncer, PL-Hide, Plan, ProtocolLib, SilkSpawners_v2, SimpleChatGames, StackMob, TabList, Vault
29.05 13:40:40 [Server] [INFO] VoidTeleport, Votifier, VotingPlugin, WorldGuard

**Comment by tastybento** [comment]
Hmm. This text is in BentoBox (the main library plugin) and is correct:

`left-your-island: "&c [name] &c left your island"`

Line 656 of en-us.yml (I'm on my phone so this is rough). 

What does yours say?

**Comment by Jeremys556** [comment]
Weird. Even on my config, it shows the same messages, but in-game it has the grammar issue.
![image](https://github.com/BentoBoxWorld/BSkyBlock/assets/20655063/b83f1615-98c6-44f1-b962-0ac6c0b6790c)

**Comment by tastybento** [comment]
I found it. It's in the Visit addon. https://github.com/BentoBoxWorld/Visit/blob/d7780f20919d4dd6b7ebc8009be55ee45a231ac0/src/main/resources/locales/en-US.yml#L309

The author is not a native English speaker. I'll submit a PR.

**Comment by tastybento** [comment]
Fixed by https://github.com/BentoBoxWorld/Visit/commit/254f5c7135707fa6bfdc0f7138a6cb827c83e6c7
