### ISSUE TITLE
Island Bug

### ISSUE THREAD

**Issue by AccioAce** [BentoBoxWorld/BSkyBlock#515]
### Expected behavior

Hello there, I'm using the latest version of bentobox and bskyblock. It seems like there is a island bug. Whenever I start an islands i designed using blueprint the island block is all mess up or went missing for some reason when I tried to start an island and when i tried to restart an island it didn't seem to fix it. 

This is happening to all islands included end and nether island ->  https://gyazo.com/a8c96b1b281ca897e9f6ea69f31560c1

### Observed/Actual behavior

It should be fully generating the islands properly but it doesn't seem to.

### Steps/models to reproduce

1. /island -> To start an island
2. Than pick an island

### BentoBox version

https://gyazo.com/e37ebc5eec3d68331932f8d269681914

**Comment by tastybento** [comment]
Can you share the blueprints? Also what exactly is messed up? I cannot tell from the description. Is it that some blocks are not pasted?
It'd be good to share a video of the problem. 
Also, if you logon and log back in, do blocks appear?

**Comment by AccioAce** [comment]
> Can you share the blueprints? Also what exactly is messed up? I cannot tell from the description. Is it that some blocks are not pasted? It'd be good to share a video of the problem. Also, if you logon and log back in, do blocks appear?

Hello,
I can share he blueprints if that helps, is there any place I can share privately? I would like to keep my builds private.

I could send you a short video of the bug but I cannot seem to upload video mkv file.

**Comment by tastybento** [comment]
You can send them to tastybento@bentobox.world. Also, if you zip the video you should be able to drag and drop it here if it isn't too big.

**Comment by AccioAce** [comment]
> You can send them to [tastybento@bentobox.world](mailto:tastybento@bentobox.world). Also, if you zip the video you should be able to drag and drop it here if it isn't too big.

Hello, oh that good to know and I've send you the video and blueprint under one zip file through my email. Let me know when you got it and keep me updated!

- Thanks

**Comment by AccioAce** [comment]
Hello tastybento, just wanted to check in if there is any luck on the fix?

**Comment by tastybento** [comment]
I tried the files and they all seem to be missing lines of blocks. I need to investigate more to see why these blocks are missing. I filled them in with pther blocks and copy and pasted them and that worked fine, so I don't understand why these ones are missing, yet.

**Comment by AccioAce** [comment]
> I tried the files and they all seem to be missing lines of blocks. I need to investigate more to see why these blocks are missing. I filled them in with pther blocks and copy and pasted them and that worked fine, so I don't understand why these ones are missing, yet.

Oh I see, I wonder if it could be a BSkyblock bug? That very odd then because if copy and paste it work. But starting any islands that doesn't works filled in with missing blocks sounds like a very strange bug to me. Hope you can get this resolved soon and good luck! Feel free to keep me updated. Thanks!

**Comment by tastybento** [comment]
<img width="512" alt="Screenshot 2024-03-24 at 2 27 11 PM" src="https://github.com/BentoBoxWorld/BSkyBlock/assets/4407265/bbbabf81-5845-44fa-ae19-d6fdbac0301e">

I changed the pasting to paste blocks as stone no matter what and this is what the starter-island looks like. This shows that it isn't the pasting causing the missing blocks - they are not actually there in the file. So, it was the copying that didn't happen correctly. 

If you have the proper islands still in a world I recommend you select and copy them again with the latest BentoBox. For some reason, slices were not copied. I don't know why and I'd be interested to find out, but right now you should try and remake these because the blueprints themselves are missing the blocks.

**Comment by AccioAce** [comment]
> <img alt="Screenshot 2024-03-24 at 2 27 11 PM" width="512" src="https://private-user-images.githubusercontent.com/4407265/316343974-bbbabf81-5845-44fa-ae19-d6fdbac0301e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTYzNDQsIm5iZiI6MTcxMTMxNjA0NCwicGF0aCI6Ii80NDA3MjY1LzMxNjM0Mzk3NC1iYmJhYmY4MS01ODQ1LTQ0ZmEtYWUxOS1kNmZkYmFjMDMwMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMjEzNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk1MzM0OTMyMTVkYTJkOWRlNzc5OWU3MTc5NWNkYjllYjdlMjdhMTM2NmVjZGFlNzFlMjViMzA0M2EzZWFiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sg_JaeeMlNmZCnHaPVgrwjePk7g9lXXwPmclssej1bc">
> 
> I changed the pasting to paste blocks as stone no matter what and this is what the starter-island looks like. This shows that it isn't the pasting causing the missing blocks - they are not actually there in the file. So, it was the copying that didn't happen correctly.
> 
> If you have the proper islands still in a world I recommend you select and copy them again with the latest BentoBox. For some reason, slices were not copied. I don't know why and I'd be interested to find out, but right now you should try and remake these because the blueprints themselves are missing the blocks.

I will try out with latest 2.1.1 version and then get back to you about it. I really hope it works!

**Comment by tastybento** [comment]
Do you recall how you made all of these blueprints? Did they used to paste correctly or have they always been wrong?

**Comment by AccioAce** [comment]
> Do you recall how you made all of these blueprints? Did they used to paste correctly or have they always been wrong?

Steps I did was from the video I saw which is 
1. /bsbadmin blu pos1
2. /bsbadmin blu pos2
3. /bsbadmin blu copy
4. /bsbadmin blu save (name)

Unless that the wrong steps?

**Comment by tastybento** [comment]
No, that's right. What version of BentoBox did you use for that?

**Comment by AccioAce** [comment]
> No, that's right. What version of BentoBox did you use for that?

I used latest one from here ->https://download.bentobox.world/custom#%5B%22BSkyBlock%22,%22Challenges%22,%22Level%22,%22Warps%22,%22ControlPanel%22,%22DimensionalTrees%22,%22Biomes%22,%22Bank%22%5D which was (2.2.0)

**Comment by tastybento** [comment]
I can only think that the copying of the islands didn't happen completely (for some reason). Tell me if it happens again.

**Comment by AccioAce** [comment]
> I can only think that the copying of the islands didn't happen completely (for some reason). Tell me if it happens again.

Hello @tastybento so it seems like the islands works perfectly fine. Same goes for end and nether islands with the bentobox version of **2.2.0**

I do highly recommend you to update to that version on your "custom build website" for bentobox as well as the current version is broken.

But overall 2.2.0 seems to be working fine.

**Comment by tastybento** [comment]
Okay. Good. Weird. 2.2.0 is the latest on the download website.
