### ISSUE TITLE
Please add the ASkyBlock GUI

### ISSUE THREAD

**Issue by robgob** [BentoBoxWorld/BSkyBlock#52]
Not sure if this has already been added. But is it possible to add the GUI from ASkyBlock that once you enter the command "/island" it brings up the GUI with all the different menus. As it is right now, when i execute the command it teleports me to my island.

Thank you!

**Comment by Poslovitch** [comment]
Duplicate of https://github.com/BentoBoxWorld/BentoBox/issues/459
