### ISSUE TITLE
Infinite spawn loop with Multiverse

### ISSUE THREAD

**Issue by Gypsum13** [BentoBoxWorld/BSkyBlock#53]
**Description**

**Steps to reproduce the behavior:**
1. Delete island whilst on Island
2. try to do /spawn
3. Get a Multiverse spawn error
You will get locked into "tping to island" Unable to move, type, or exit game

**Expected behavior**
Expected to just get an error and stay on deleted island, but instead the island remains in the world, and you get trapped. Even after server restart. 

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): None at the moment
 - OS: windows 10
 - Java Version: Latest version
 - BentoBox version: 1.1
 - Addons installed? Bskyblock
 - Other plugins? 93 other plugins, although unnecessary as the issue correlates with Multiverse-Core and Bskyblock.

**Additional context**
The problem is caused by a Multiverse Error, but possibly a better deletion system, like you get teleported to main spawn, not the worlds spawn. With it trying to tp me to the world spawn, It defaults to original island spawn, which doesnt exist, and I get into an infinite loop.

**Comment by tastybento** [comment]
How do you do step 1? How do you delete the island?
