### ISSUE TITLE
Starting chest contains beetroot instead of beetroot_seeds

### ISSUE THREAD

**Issue by JadenDevon** [BentoBoxWorld/BSkyBlock#54]
**Description**
Starting chest contains beetroot instead of beetroot_seeds.

**Steps to reproduce the behavior:**
1. Start a new island

**Additional context**
You can't plant beetroots. You can only plant beetroot_seeds and you cannot create the seeds with the beetroots. It is therefore impossible to complete the "seedy place" challenge

**Comment by tastybento** [comment]
Understood. You can edit the schem yourself, but I'll do an update and put more stuff in the chest.

**Comment by JadenDevon** [comment]
I have already fixed on my end. I just wanted to make sure it was fixed for everyone else. Thanks for making this awesome plugin!

**Comment by tastybento** [comment]
Fixed
