### ISSUE TITLE
Creeper Block Grief and Creeper Damage always active, also if disabled in /is settings

### ISSUE THREAD

**Issue by KleinDevDE** [BentoBoxWorld/BSkyBlock#56]
**Description**
Creeper Block Grief and Creeper Damage always active, also if disabled in /is settings

**Steps to reproduce the behavior:**
1. /is settings
2. SkyBlock Settings
3. Disable Creeper Block Grief and Creeper Damage
4. Go in survival and spawn creeper

**Expected behavior**
I want to disable Creeper Block Griefing, but it takes no changes 

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): [File]
 - OS: [Debian 8.4]
 - Java Version: [Java 8]
 - BentoBox version: [1.1]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
[20:52:08 INFO]: Bentobox version: 1.1
[20:52:08 INFO]: Loaded Game Worlds:
[20:52:08 INFO]: BSkyBlock_world (BSkyBlock)
[20:52:08 INFO]: Loaded Add-Ons
[20:52:08 INFO]: BSkyBlock 1.0
[20:52:08 INFO]: WelcomeWarps 0.1.0-SNAPSHOT
[20:52:08 INFO]: Challenges 0.3.0
[20:52:08 INFO]: Biomes 0.4.1
[20:52:08 INFO]: Level 0.2.0
[20:52:08 INFO]: BentoBox-Level 0.0.2-SNAPSHOT
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Plugins (14): AsyncWorldEdit, AsyncWorldEditInjector, BentoBox, BungeeTabListPlus*, CoreProtect, Essentials*, EssentialsChat*, FreeBungeeChat*, LuckPerms*, Multiverse-Core*, Vault*, WorldBorder*, WorldEdit, WorldGuard

**Comment by tastybento** [comment]
Hmm, I tested and I can't replicate. Let's check that we have a common understanding of what the settings are:

**Creeper damage** - if enabled, then blocks will be destroyed when a creeper blows up on your island. If disabled, then blocks will not be blown up. In both cases though, you will still suffer player damage from the explosion and may die.

**Creeper griefing** - this has no affect on your own island. It is only for visitors. When disabled, if a visitor causes a creeper to explode, nothing will happen. No blocks will be destroyed. If active nothing will happen as well **unless** Creeper Damager is active.
