### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TheWackersKian** [BentoBoxWorld/BSkyBlock#59]
This isn't really a bug just a "How to install guide" problem. I have looked and looked and looked and can't find the jar for BSkyblock to put into the BentoBox addons file. Hence meaning I can't use the extension... Please help lol.

**Comment by Poslovitch** [comment]
It's in the releases tab, not the big green download button

**Comment by TheWackersKian** [comment]
Thanks so much lol, I'm so dumb xD.

**Comment by Poslovitch** [comment]
Glad to help, but that's a FAQ ^^'.
