### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by TheWackersKian** [BentoBoxWorld/BSkyBlock#60]
Hi, I have just went and created a new schematic saved it and tried /island reset minershaven which is the name of the new schematic and it says "That schem has not been loaded yet." so I do /bsbadmin schem load minershaven it says success so I try the command again and it is still saying the schem is not loaded.

**Comment by tastybento** [comment]
You should restart the server. Schems for island creation are loaded when the plugin loads.
