### ISSUE TITLE
support

### ISSUE THREAD

**Issue by TheWackersKian** [BentoBoxWorld/BSkyBlock#61]
Once again I am having issues increasing the distance between islands. I also closed the server first then edited the config brought it back up did /island reset minershaven twice to regenerate the island and the amount of blocks are still the same.

**Comment by tastybento** [comment]
What are you doing exactly? Give me step by step.

Also, please complete the following information for background on your server:
 - Database being used (Flat file, MySQL, Mongo): []
 - OS: [e.g. iOS]
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Comment by TheWackersKian** [comment]
I stopped the server went into the bSkyblock folder and then into config, I changed the distance between islands to 128 so doubling it and then I started the server back up. I did /island reset minershaven because I already owned an island and my friends island was still close to me and the value of blocks away didn't change.

I am not using any database atm.
Windows 10 but I bought this server from shockbyte
Dk
1.2.0 the one from a day ago
Bentobox version: 1.2.0
Loaded Game Worlds:
BSkyBlock_world (BSkyBlock)
Loaded Add-Ons
BSkyblock 1.1

World Edit, SonezSpawnJoin, InventorySort, VoidGenerator, Group Manager, HolographicDisplays, HelpGUI, Vault, WorldGuard, ColoredTags, BentoBox, Essentials, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, Multiverse-Core and EssentialsProtect.

**Comment by TheWackersKian** [comment]
Also what are the permissions for allowing users to create islands?

**Comment by tastybento** [comment]
If you change island distance, you really should restart the world, i.e., delete it completely. It could be that your friend's island is now within your island space. Generally, you cannot change the island distance without resetting everything.

Permissions are here:
https://github.com/BentoBoxWorld/BSkyBlock/blob/master/src/main/resources/addon.yml#L12
