### ISSUE TITLE
Question or problem ? With respawn on island

### ISSUE THREAD

**Issue by wohahobg** [BentoBoxWorld/BSkyBlock#62]
**Description**
Hey there! I am using your SkyBlock plugin, really is nice one, I like it, but from few days I have a problem with this

```
# Have player's respawn on their island if they die
respawn-on-island: true
```

even when it is true they have respawn somewhere else but not on thairs island. I do not have any erros in console or something like that.?:( ?  and where I could find the placeholderapi staff for the plugin, I was looking but...

**Server Information:**

[Please complete the following information:]
 - Database: YAML
 - Java Version: last one.
 - BentoBox info:

BentoBox Info: [http://prntscr.com/mkxyro](http://prntscr.com/mkxyro)

**Comment by wohahobg** [comment]
So they have respawn on one of my staff island. I do not have any respawn plugin, even Essentials as u can see above, just when they die thay are respawing on another island not on thairs one..

I am sorry for my english is not well.

**Comment by tastybento** [comment]
I understand what you wrote.

Does it happen to all players? Or just some players?

If a safe spot cannot be found for the player then they will be teleported to the world spawn location. In the most recently (1.2) version of BentoBox, the /spawn command will be run. That may be happening.

**Comment by wohahobg** [comment]
It happen to everybody... Even I have try it as a User made an island then just jump into void and it does not teleport me to my island plus I have used /is sethome, even then I have not teleport to island when I die.

**Comment by tastybento** [comment]
When you stop the server and then open the config.yml file is the setting really set to true? Just want to check. 

By the way are you able to run your own test server on a PC? Can you check if if it works there?

**Comment by wohahobg** [comment]
When I stop it Yes it is still on true.. if you want u came in and see IP mc.cwolly.eu
Discors Wohaho#5542

Right now I am not on my pc will try later.

**Comment by wohahobg** [comment]
Hey there! So I have try it on my localhost and even there it happen like that + I found out another bug with the Ender portal even on my localhost we cannot create ender portal, here is the list of plugin on my localhost..

[http://prntscr.com/mf133h](http://prntscr.com/mf133h)

**Comment by wohahobg** [comment]
Hey there, the problem come again few days ago.. Some people has different respawn on death

**Comment by Poslovitch** [comment]
Please provide your `/bbox v` output as well as the `Players` files of the users that respawn weirdly.

**Comment by wohahobg** [comment]
Hey there here is the information:

My BentoBox v: [http://prntscr.com/mky30x](http://prntscr.com/mky30x)

So here Is both files:
My Head Admin File [https://gist.github.com/wohahobg/fdda8f0c04da5500b879365165d0e7bb](https://gist.github.com/wohahobg/fdda8f0c04da5500b879365165d0e7bb)
My Server Helper File

My Server Helper File [https://gist.github.com/wohahobg/e2e934a2663a172fa6d4b90ec05b3063](https://gist.github.com/wohahobg/e2e934a2663a172fa6d4b90ec05b3063)

So when **Ghost34** [HeadAdmin] die his respawn point is on **DenisVK** [Server Helper] island's but whenn **Ghost34** exe command /is home or /is , his respawn point is normal.

**Comment by LukeZurg22** [comment]
I am not going to upload player files and doing the command shows something odd. Now it does:
![Uploading 2019-02-17_20.25.31.png…]()

**Comment by tastybento** [comment]
@wohahobg It's been a while are you still having issues?
