### ISSUE TITLE
PlaceholderAPI Support?

### ISSUE THREAD

**Issue by PizzaMC** [BentoBoxWorld/BSkyBlock#63]
Hey,
When are we getting support for PlaceholderAPI?
Like %bskyblock_level%

**Comment by BONNe** [comment]
BSkyblock does not support any level related things.
It cannot give you this information.

**Comment by iSkeptical** [comment]
Could you guys add PlaceHolderAPIS? 
I loved the support from ASkyblock, but Bskyblock is just missing so much...

**Comment by BONNe** [comment]
So BentoBox supports PlaceHolderAPI.
But there are no addons who uses it.

**Comment by iSkeptical** [comment]
Is there a list of PlaceHolderAPIS for bskyblock anywhere?

**Comment by Poslovitch** [comment]
@iSkeptical And ASkyBlock's actually never supported placeholders :p 
See https://github.com/BentoBoxWorld/BentoBox/issues/322

**Comment by PizzaMC** [comment]
What do you mean "would need" to be added? Is there completely no implemented placeholders already?
