### ISSUE TITLE
zombie pigmans do not attack the turtle eggs.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/BSkyBlock#67]
**Description**

The zombie pigmans in the Nether do not attack the turtle eggs.

**Expected behavior**
The zombie pigmans in the Nether must attack the turtle eggs.

**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/52206719-2f8fda80-288c-11e9-8ea0-0560f419e2af.png)

**Server Information:**
 - OS: Linux
 - Java Version: Java 8
 - BentoBox version: 1.2.1

**Comment by OverBrave** [comment]
This 1.13 features look at the video: https://www.youtube.com/watch?v=euVbrFmQpyc

**Comment by Poslovitch** [comment]
Have you tried to replicate this on a singleplayer world?

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/52211333-9e743000-289a-11e9-8474-36e82dc51e27.png)
Yes its working on singel player.

**Comment by Poslovitch** [comment]
I wanted you to try to build the exact same farm design: on the first screen you've shared, the pigman looks at the eggs, but it seems he won't move to there because of the hole.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/52217669-fb2b1700-28a9-11e9-9a39-b2cd17f05c9e.png) ?

**Comment by Poslovitch** [comment]
This one... https://github.com/BentoBoxWorld/BSkyBlock/issues/67#issue-406293910

**Comment by safemaster00** [comment]
i had this problem too

**Comment by Mahi** [comment]
Same issue. Mob griefing set to `true`

![image](https://user-images.githubusercontent.com/11020883/179565215-8e0e77be-d738-4cbd-ae2a-82e329931de9.png)

**Comment by BONNe** [comment]
BentoBox does not have any features that would prevent entities from breaking turtle eggs, picking up blocks, or trampling crops. 

If you use WorldGuard, EssentialsProtect, or any other plugin that has world protection features, then most likely they are the reason for your issue.

Also, Paper and Purpur server engines have options to prevent zombies from targeting Turtle Eggs.

Overall  -> not a bentobox issue.
