### ISSUE TITLE
Users can't go to each other's islands.

### ISSUE THREAD

**Issue by TheAgentRAINBOW** [BentoBoxWorld/BSkyBlock#73]
**Description**
Users cannot go to other people's islands, even when co-opped as there doesn't appear to be a command to do so. We have tried `/is go` and everything similar.

**Screenshots**
None appliciable.

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): [Flat File]
 - OS: [Windows 10]
 - Java Version: [Java 8]
 - BentoBox version: [1.2.1]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 Loaded Addons:
`BSkyBlock 1.1`
`Challenges 0.5.0-SNAPSHOT`
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Plugins (7): `BasicColors*, BentoBox, Hub*, MySkin, VoidGenerator, WorldEdit, WorldGuard`

**Additional context**
None.

**Comment by tastybento** [comment]
This is correct. You can install the warp sign add-on or enable commands like /tpa from other plugins.

**Comment by TheAgentRAINBOW** [comment]
Ah, okay, thank you. Sorry for the bother.

**Comment by AeSix** [comment]
@TheAgentRAINBOW Don't be sorry for bothering.  It's stupid this isn't built into bskyblock.

**Comment by Poslovitch** [comment]
It's currently a pending feature request. See https://github.com/BentoBoxWorld/BentoBox/issues/1163. I'm already designing that.

**Comment by AeSix** [comment]
@Poslovitch - Thank you very much!  We've already had players kill their visitors on teleport by holdinging shift on the edge of blocks, then walking forward as the visitor spawns in, which can push them off the edge :S 

I hope your solution has some better logic than that :)
