### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by CaptainElsa** [BentoBoxWorld/BSkyBlock#76]
**Description**
A clear and concise description of what your problem is.

**Answer: So my problem is that when I downloaded the plugin and added it to my server, I cant do /c or /challenges. Can I download it somewhere?**
**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): [None]
 - OS: [e.g. iOS] None
 - Java Version: [e.g. Java 8] Dont know
 - BentoBox version: [e.g. 1.7.2.21] Latest
 - Addons installed? [Do '/bentobox version' and copy/paste from the console] BSkyBlock
 - Other plugins? [Do '/plugins' and copy/paste from the console] **_WorldEdit, TAB, IPWhitelist, Pex, Vault, WorldGuard, EssentialsX, EssentialsChat, BSkyBlock, EssentialsSpawn, ChatFormat, EssentialsProtect._**

**Additional context**
Help me with adding challenges to the islands.

**Comment by tastybento** [comment]
The challenges add-on is here: https://github.com/BentoBoxWorld/Challenges/releases/tag/0.5.0

Once you install it in your BentoBox add-ons folder the admin command to start is /bsadmin challenges.

**Comment by CaptainElsa** [comment]
Will it only work for admins or for players as well?
