### ISSUE TITLE
latest jar won't work

### ISSUE THREAD

**Issue by PizzaMC** [BentoBoxWorld/BSkyBlock#80]
http://prntscr.com/mm19hd

**Comment by Poslovitch** [comment]
https://github.com/BentoBoxWorld/BentoBox/wiki/Install-Bentobox#install-addons

**Comment by PizzaMC** [comment]
lmao close this. downloaded wrong jar

**Comment by Poslovitch** [comment]
![image](https://user-images.githubusercontent.com/20014332/52905070-e4cf7480-3234-11e9-80eb-77cca09d6484.png)

**Comment by PizzaMC** [comment]
that's not the problem. I downloaded the javadoc jar instead
