### ISSUE TITLE
Challenge/Quest System

### ISSUE THREAD

**Issue by LukeZurg22** [BentoBoxWorld/BSkyBlock#84]
One of my players reccommends a challenge system, something that is easy and customizable would be nice, expecially if there is an ingame GUI. Not expecting it to happen and other plugins could fill out this roll but having one do it would be less memory intensive than a requirement for 2 plugins to load.

The feature would also dramatically increase plugin's appeal to others joining the server aswell.

**Comment by BONNe** [comment]
BSkyBlock is GameMode addon. It is not suited for these kind of things.
There exists Challenges Addon and there is planned to create Achievement Addon that is your requested things.

**Comment by LukeZurg22** [comment]
Where do I find the challenges addon?

**Comment by BONNe** [comment]
Link that shows all official repos for BentoBox
https://github.com/BentoBoxWorld

**Comment by LukeZurg22** [comment]
How do I compile as a .jar?

**Comment by BONNe** [comment]
![wheretofind](https://user-images.githubusercontent.com/1344358/52921612-a8c60d80-3321-11e9-854c-4732fd4049bd.png)

**Comment by LukeZurg22** [comment]
My bad for my stupidity in that moment, all good now!
