### ISSUE TITLE
BSkyBlock invswitcher

### ISSUE THREAD

**Issue by kreskofter** [BentoBoxWorld/BSkyBlock#85]
**Description**
I'm sorry to bother you here, but the discord link is expired and I could not sign up on http://dhwxsxsc.com to message you there.

There are a few issues going on with BSkyBlock. On the latest Build (build 166) does not allow players or admins to access Challenges.

Also InvSwitcher-0.0.1-SNAPSHOT.jar does not seem to work either. Players and admins are able to carry their inventories from the main server world to BSkyBlock.

You are welcome to see this for yourself at server IP: world.krumbledmc.com

Thank you,

**Screenshots**

**Server Information:** KrumbledMC - world.krumbledmc.com

[Please complete the following information:]
 - Database: MySQL
 - OS: Win 10
 - Java Version: Version 8 Update 201
- BentoBox version: BentoBox version: 1.2.1
 - Addons installed? BSkyBlock 1.3.0-SNAPSHOT, Challenges 0.5.1, Invswitcher 0.0.1
 - Other plugins? CleanroomGenerator, LinksOnSigns, BlockLocker, MermaidPlus, PerWorldPlugins, IP-Check, EmeraldTools, TreysCommandBlocker, ObsidianArmor, Broadcaster, CommandSpy, CreeperControl, ChatReaction, RestartTimer, CustomCreatures, Ridables, TreeGravity, ConsoleChat, CoreProtect, dynmap, PluginHider, WorldEdit, JenoRestart, BuycraftX, EnchantedFurnace, Jouster, DisableWither, Awkward, PermissionsEx, Vault, PerWorldInventory, WorldGuard, Essentials, Carz, BannerMaker, Citizens, BentoBox, AdvancedAchievements, EssentialsChat, RFChairs, AntiSwear, PiggyBack, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, Multiverse-Core, Residence, ChestShop, KillerMoney, Multiverse-NetherPortals, MultiWorldMoney

**Additional context**
None

**Comment by BONNe** [comment]
Discord link: https://discord.bentobox.world/

So, issues that you report does not relay on BSkyBlock.
However, Im not sure, but SkyBlock 1.3 does not work with bentobox 1.2.1 correctly.
And invSwitcher... It should work, as noting was changed...

For it would be necessary to print out /bentobox v
or provide console log, till bentoBox logo.

But anyway... for it you must create separate issues in correct places:
Challenges Addon: https://github.com/BentoBoxWorld/Challenges
InvSwitcher: https://github.com/BentoBoxWorld/addon-invSwitcher
