### ISSUE TITLE
SKyBlock and Acidisland commands: "/bsb top" is invalid

### ISSUE THREAD

**Issue by HuJunwei23333** [BentoBoxWorld/BSkyBlock#87]
**Description**

**Steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by BONNe** [comment]
Nice bug report. Everything is clear and understandable :)

Update your config file for a level add-on.

**Comment by Poslovitch** [comment]
This issue is not related to the BSkyBlock addon. Please post it in the Level addon repository and follow the guidelines.
