### ISSUE TITLE
Players Islands get unlinked

### ISSUE THREAD

**Issue by Aberdeener** [BentoBoxWorld/BSkyBlock#88]
**Description**
Suddenly, when players do /island a new island is created for them as if their old islands are unlinked.

**Screenshots**
N/A

**Server Information:**

 - Database being used (Flat file, MySQL, Mongo): Flat File
 - OS: Ubuntu 18.04
 - Java Version: 8
 - BentoBox version: 1.2.1
 - Addons installed? BSkyBlock 1.1
 - Other plugins? 
LuckPerms, WorldEdit, Skript, Essentials, LogBlock, PlaceholderAPI, ClearLag, PlayTime, SkQuery, NametagEdit, WorldGuard, ProtocolLib, MaxBans, Vault, EssentialsSpawn, VaultChatFormatter, NamelessMC, HolographicDisplays, PlotSquared, YangCore, LockettePro, BentoBox, Umbaska, SuperVanish, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals

**Additional context**
I can't think of anything else. One day they work and the next they dont. Worried because I have players who have put hours and hours into their islands.

**Comment by Poslovitch** [comment]
Please update to BentoBox 1.3.0
