### ISSUE TITLE
Adding islands & an Island Selector on Island creation

### ISSUE THREAD

**Issue by FlailoftheLord** [BentoBoxWorld/BSkyBlock#89]
Hey, i couldn't find any tutorials on how to add more Island Schematics... i created several new ones and saved them using the schematic command in bskyblock, but i have no idea how to make a GUI or something to let the player select which island he gets when starting/resetting 

Do i need to make one for each world? or can i just set the names somewhere.... i checked all the config files... couldn't find anything at all relating to schematics.  The whole setup of this plugin is so much more confusing than ASkyblock.

Edit: I do know about the /is create  [schematic-name]
I just don't want to force players to have to type in extra args.

**Comment by tastybento** [comment]
Right now, we're trying to focus on making sure the plugin is stable and works with a core set of features. For the schems side of things, there will be a separate plugin to enable selection of island types but it has not been coded yet.
Before there's a flashy GUI, the current way to enable alternative schems is via the /is create or /is reset commands and permissions.

1. Create an island schem. I recommend you start with the default one. Don't forget to include the spawn here sign.
2. Create corresponding nether and end world schems if they need to exist. They should be named nether-**name** and end-**name** where **name** is the name of the over-world island. For example: donor, nether-donor, end-donor.
3. Now, in order for the player to be able to create or reset to this donor island, they must have the permission that includes that name, e.g., bskyblock.island.create.donor. 
4. The player issues the command **/is create donor** or **/is reset donor** to create their donor island.

For step 4, you can use other plugins that run commands to create your own GUI if you like.

**Comment by FlailoftheLord** [comment]
Awesome, thanks for clarifying that!
Loving the work y'all are putting into this plugin.
And yes, i'm gonna just use BSP to make an island selection Gui for now. thanks!
