### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PetyXbronCZ** [BentoBoxWorld/BSkyBlock#91]
**Description**
How can I install this plugin?

**Server Information:**
Bukkit 1.13.2
 
**Additional context**
Hello, I installed this plugin and I have done all of your installation procedures.
But when I installed the plugin, nothing happened after the reboot did not happen. Like any plugin, I need a .jar file to make my server plugins real! So, can anyone help me? 
Is this at version 1.13.2 at all? Does it work on Bukkit?

**Comment by Poslovitch** [comment]
Hi 🙂 

BentoBox requires **1.13.2** and **Spigot** as server software.
In regards to the installation, BentoBox should be put in the `plugins` folder, whereas addons should be put in the `plugins/BentoBox/addons`, as stated on the installation guide.

Please send us your startup logs if that still doesn't work for you. If BentoBox somehow cannot load, everything's going to be written there.

**Comment by PetyXbronCZ** [comment]
> Hi 🙂
> 
> BentoBox requires **1.13.2** and **Spigot** as server software.
> In regards to the installation, BentoBox should be put in the `plugins` folder, whereas addons should be put in the `plugins/BentoBox/addons`, as stated on the installation guide.
> 
> Please send us your startup logs if that still doesn't work for you. If BentoBox somehow cannot load, everything's going to be written there.

**Comment by PetyXbronCZ** [comment]
So, I installed it again and I cant find file .jar
What I must to do to get .jar?
I downloaded .zip from this site and none .jar here.

**Comment by Poslovitch** [comment]
![image](https://user-images.githubusercontent.com/20014332/53683888-a773e800-3d06-11e9-8180-3356b0bddf1a.png)
(from https://github.com/BentoBoxWorld/BentoBox/wiki/Install-Bentobox#download-bentobox)
