### ISSUE TITLE
Schematic Chest not copy

### ISSUE THREAD

**Issue by CodeDoctorDE** [BentoBoxWorld/BSkyBlock#95]
**Description**
When I copy and save the island, the chest will not copied!

**Steps to reproduce the behavior:**
1. Command /isadmin schem pos1
2. Command /isadmin schem pos2
3. Command /isadmin schem copy
4. Command /isadmin schem save island
5. Command /is

**Expected behavior**
The chest inventory will save!

**Screenshots**
![2019-03-05_17 02 31](https://user-images.githubusercontent.com/20452814/53818525-7db9fb80-3f68-11e9-901c-5d29ed1e905e.png)

**Server Information:**

 - Database Flat file
 - OS: Debian
 - Java Version: Java
 - BentoBox version: 1.4.0-SNAPSHOT
 - Addons installed? BSkyBlock
 - Other plugins? no

**Comment by tastybento** [comment]
You have to restart the server after changing the island schem files.
