### ISSUE TITLE
Adding GUI feature?

### ISSUE THREAD

**Issue by STOOKA** [BentoBoxWorld/BSkyBlock#96]
**Describe the solution you'd like**
Hello dear Developer,
i have a simple question..
When will you create a GUI for BSkyBlock?
Because atm there is no GUI feature avilable..

Greats,
STOOKA :)

**Comment by tastybento** [comment]
This will be done in an another addon or via other menu plugins. :-)

**Comment by STOOKA** [comment]
Okay, thanks dude ^^
