### ISSUE TITLE
End Portal

### ISSUE THREAD

**Issue by Devon557** [BentoBoxWorld/BSkyBlock#98]
When a user tries to access the BSkyBlock end world, they are teleported back into the BSkyBlock world and fall to their death.

1. Enter Nether
2. Use eye of the ender to activate portal
3. Enter portal and begin to plummet. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48629979/54479913-9ba11f00-47f8-11e9-85b2-a51ac26ef91b.png)

![image](https://user-images.githubusercontent.com/48629979/54479916-af4c8580-47f8-11e9-994d-8d0b89390c1c.png)

**Server Information:**

[Please complete the following information:]
 - BentoBox version: 1.3.1
 - Addons installed? 
16.03 14:26:00 [Server] INFO BentoBox version: 1.3.1
16.03 14:26:00 [Server] INFO Loaded Game Worlds:
16.03 14:26:00 [Server] INFO BSkyBlock_world (BSkyBlock)
16.03 14:26:00 [Server] INFO Loaded Addons:
16.03 14:26:00 [Server] INFO BSkyBlock 1.0
16.03 14:26:00 [Server] INFO Challenges 0.5.0
 - Other plugins? 
Plugins (40): CoreProtect, WorldEdit, ColoredSigns, GreatKits, OpenInv, Essentials, MinePacks, BlockLocker, WebsitePlugin, GroupManager, PerWorldPlugins, PlugMan, HolographicDisplays, Discord, Votifier, WorldGuard, XRayShield, VotingPlugin, VoidGenerator, LiteBansGUI, EssentialsChat, TreeCapitator, mcMMO, StaffChat, Vault, EssentialsSpawn, EnjinMinecraftPlugin, ChestShop, Jobs, PerWorldInventory, PlotSquared, RandomTeleport, PluginLibrary, Statz, MultiWorldMoney, Multiverse-Core, BentoBox, Multiverse-NetherPortals, Multiverse-Portals, GriefPrevention

**Additional context**
I can force my tp to the end world, but I spawn between the two islands..
![image](https://user-images.githubusercontent.com/48629979/54479893-4ebd4880-47f8-11e9-8896-864fc2377695.png)

![image](https://user-images.githubusercontent.com/48629979/54479899-70b6cb00-47f8-11e9-80e6-ddd55c8efa26.png)

**Comment by Devon557** [comment]
Update:

For some reason it has now created a superflat world under the islands 

![image](https://user-images.githubusercontent.com/48629979/54480055-7e6d5000-47fa-11e9-9c1e-ad8021ab4ed3.png)

**Comment by tastybento** [comment]
I all looks like there are generator issues or errors in general with the setup. Are you setting up a new world/server? If so, make sure you fully delete all worlds/databases/etc from the previous config. Also, have a look in the console for errors when starting up to see if there are any hints as to what is going on. Right now, my recommendation is a full reset.

**Comment by Devon557** [comment]
It is a new world for everything, so I will do a hard reset. As I have a few players on my server this will have to wait until later this morning. But I will give it a try.

**Comment by tastybento** [comment]
I assume this was fixed by the hard reset.
