### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by swirle** [BentoBoxWorld/BSkyBlock#99]
I mean its quite simple, just need placeholders in BSkyblock (PAPI integration if possible)

**Comment by BONNe** [comment]
No, no placeholders.
You can see it in BentoBox changeLog:
BentoBox 1.4.0-SNAPSHOT:
- remove PAPI integration completely.

**Comment by Poslovitch** [comment]
Joke aside, PAPI integration exists since 1.1. But something didn't go as expected: addons did not add placeholders. That's why default ones for each gamemode addon will be registered in 1.4.0.
